п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro pЕ™Г­stupnost",contents:"Obsah nГЎpovД›dy. Pro uzavЕ™enГ­ tohoto dialogu stisknД›te klГЎvesu ESC.",legend:[{name:"ObecnГ©",items:[{name:"Panel nГЎstrojЕЇ editoru",legend:"StisknД›te${toolbarFocus} k prochГЎzenГ­ panelu nГЎstrojЕЇ. PЕ™ejdД›te na dalЕЎГ­ a pЕ™edchozГ­ skupiny pomocГ­ TAB a SHIFT+TAB. PЕ™echod na dalЕЎГ­ a pЕ™edchozГ­ tlaДЌГ­tko panelu nГЎstrojЕЇ je pomocГ­ Е IPKA VPRAVO nebo Е IPKA VLEVO. StisknutГ­m mezernГ­ku nebo klГЎvesy ENTER tlaДЌГ­tko aktivujete."},{name:"DialogovГ© okno editoru",
legend:"UvnitЕ™ dialogovГ©ho okna stisknД›te TAB pro pЕ™esunutГ­ na dalЕЎГ­ prvek okna, stisknД›te SHIFT+TAB pro pЕ™esun na pЕ™edchozГ­ prvek okna, stisknД›te ENTER pro odeslГЎnГ­ dialogu, stisknД›te ESC pro jeho zruЕЎenГ­. Pro dialogovГЎ okna, kterГЎ majГ­ mnoho karet stisknД›te ALT+F10 pro zamД›Е™enГ­ seznamu karet, nebo TAB, pro posun podle poЕ™adГ­ karet.PЕ™i zamД›Е™enГ­ seznamu karet se mЕЇЕѕete jimi posouvat pomocГ­ Е IPKY VPRAVO a VLEVO."},{name:"KontextovГ© menu editoru",legend:"StisknД›te ${contextMenu} nebo klГЎvesu APPLICATION k otevЕ™enГ­ kontextovГ©ho menu. Pak se pЕ™esuЕ€te na dalЕЎГ­ moЕѕnost menu pomocГ­ TAB nebo Е IPKY DOLЕ®. PЕ™esuЕ€te se na pЕ™edchozГ­ moЕѕnost pomocГ­  SHIFT+TAB nebo Е IPKY NAHORU. StisknД›te MEZERNГЌK nebo ENTER pro zvolenГ­ moЕѕnosti menu. Podmenu souДЌasnГ© moЕѕnosti otevЕ™ete pomocГ­ MEZERNГЌKU nebo ENTER ДЌi Е IPKY DOLEVA. KontextovГ© menu uzavЕ™ete stiskem ESC."},
{name:"RГЎmeДЌek seznamu editoru",legend:"UvnitЕ™ rГЎmeДЌku seznamu se pЕ™esunete na dalЕЎГ­ poloЕѕku menu pomocГ­ TAB nebo Е IPKA DOLЕ®. Na pЕ™edchozГ­ poloЕѕku se pЕ™esunete SHIFT+TAB nebo Е IPKA NAHORU. StisknД›te MEZERNГЌK nebo ENTER pro zvolenГ­ moЕѕnosti seznamu. StisknД›te ESC pro uzavЕ™enГ­ seznamu."},{name:"LiЕЎta cesty prvku v editoru",legend:"StisknД›te ${elementsPathFocus} pro prochГЎzenГ­ liЕЎty cesty prvku. Na dalЕЎГ­ tlaДЌГ­tko prvku se pЕ™esunete pomocГ­ TAB nebo Е IPKA VPRAVO. Na pЕ™edchozГ­ tlaДЌГ­tko se pЕ™esunete pomocГ­ SHIFT+TAB nebo Е IPKA VLEVO. StisknД›te MEZERNГЌK nebo ENTER pro vybrГЎnГ­ prvku v editoru."}]},
{name:"PЕ™Г­kazy",items:[{name:" PЕ™Г­kaz ZpД›t",legend:"StisknД›te ${undo}"},{name:" PЕ™Г­kaz Znovu",legend:"StisknД›te ${redo}"},{name:" PЕ™Г­kaz TuДЌnГ©",legend:"StisknД›te ${bold}"},{name:" PЕ™Г­kaz KurzГ­va",legend:"StisknД›te ${italic}"},{name:" PЕ™Г­kaz PodtrЕѕenГ­",legend:"StisknД›te ${underline}"},{name:" PЕ™Г­kaz Odkaz",legend:"StisknД›te ${link}"},{name:" PЕ™Г­kaz SkrГЅt panel nГЎstrojЕЇ",legend:"StisknД›te ${toolbarCollapse}"},{name:"PЕ™Г­kaz pro pЕ™Г­stup k pЕ™edchozГ­mu prostoru zamД›Е™enГ­",legend:"StisknД›te ${accessPreviousSpace} pro pЕ™Г­stup k nejbliЕѕЕЎГ­mu nedosaЕѕitelnГ©mu prostoru zamД›Е™enГ­ pЕ™ed stЕ™Г­ЕЎkou, napЕ™Г­klad: dva pЕ™ilehlГ© prvky HR. Pro dosaЕѕenГ­ vzdГЎlenГЅch prostorЕЇ zamД›Е™enГ­ tuto kombinaci klГЎves opakujte."},
{name:"PЕ™Г­kaz pro pЕ™Г­stup k dalЕЎГ­mu prostoru zamД›Е™enГ­",legend:"StisknД›te ${accessNextSpace} pro pЕ™Г­stup k nejbliЕѕЕЎГ­mu nedosaЕѕitelnГ©mu prostoru zamД›Е™enГ­ po stЕ™Г­ЕЎce, napЕ™Г­klad: dva pЕ™ilehlГ© prvky HR. Pro dosaЕѕenГ­ vzdГЎlenГЅch prostorЕЇ zamД›Е™enГ­ tuto kombinaci klГЎves opakujte."},{name:" NГЎpovД›da pЕ™Г­stupnosti",legend:"StisknД›te ${a11yHelp}"}]}],tab:"TabulГЎtor",pause:"Pauza",capslock:"Caps lock",escape:"Escape",pageUp:"StrГЎnka nahoru",pageDown:"StrГЎnka dolЕЇ",leftArrow:"Е ipka vlevo",upArrow:"Е ipka nahoru",
rightArrow:"Е ipka vpravo",downArrow:"Е ipka dolЕЇ",insert:"VloЕѕit",leftWindowKey:"LevГЎ klГЎvesa Windows",rightWindowKey:"PravГЎ klГЎvesa Windows",selectKey:"Vyberte klГЎvesu",numpad0:"NumerickГЎ klГЎvesa 0",numpad1:"NumerickГЎ klГЎvesa 1",numpad2:"NumerickГЎ klГЎvesa 2",numpad3:"NumerickГЎ klГЎvesa 3",numpad4:"NumerickГЎ klГЎvesa 4",numpad5:"NumerickГЎ klГЎvesa 5",numpad6:"NumerickГЎ klГЎvesa 6",numpad7:"NumerickГЎ klГЎvesa 7",numpad8:"NumerickГЎ klГЎvesa 8",numpad9:"NumerickГЎ klГЎvesa 9",multiply:"NumerickГЎ klГЎvesa nГЎsobenГ­",
add:"PЕ™idat",subtract:"NumerickГЎ klГЎvesa odeДЌГ­tГЎnГ­",decimalPoint:"DesetinnГЎ teДЌka",divide:"NumerickГЎ klГЎvesa dД›lenГ­",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"StЕ™ednГ­k",equalSign:"RovnГ­tko",comma:"ДЊГЎrka",dash:"PomlДЌka",period:"TeДЌka",forwardSlash:"LomГ­tko",graveAccent:"PЕ™Г­zvuk",openBracket:"OtevЕ™enГЎ hranatГЎ zГЎvorka",backSlash:"ObrГЎcenГ© lomГ­tko",closeBracket:"UzavЕ™enГЎ hranatГЎ zГЎvorka",
singleQuote:"JednoduchГЎ uvozovka"});