п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sisГ¤llГ¶t. Sulkeaksesi tГ¤mГ¤n dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin tyГ¶kalupalkki",legend:"Paina ${toolbarFocus} siirtyГ¤ksesi tyГ¶kalupalkkiin. Siirry seuraavaan ja edelliseen tyГ¶kalupalkin ryhmГ¤Г¤n TAB ja SHIFT+TAB nГ¤ppГ¤imillГ¤. Siirry seuraavaan ja edelliseen tyГ¶kalupainikkeeseen kГ¤yttГ¤mГ¤llГ¤ NUOLI OIKEALLE tai NUOLI VASEMMALLE nГ¤ppГ¤imillГ¤. Paina VГ„LILYГ–NTI tai ENTER nГ¤ppГ¤intГ¤ aktivoidaksesi tyГ¶kalupainikkeen."},
{name:"Editorin dialogi",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editorin oheisvalikko",legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS nГ¤ppГ¤imillГ¤. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YLГ–S nГ¤ppГ¤imillГ¤. Paina VГ„LILYГ–NTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina VГ„LILYГ–NTI tai ENTER tai NUOLI OIKEALLE painiketta. SiirtyГ¤ksesi takaisin valikon ylemmГ¤lle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},
{name:"Editorin listalaatikko",legend:"Listalaatikon sisГ¤llГ¤ siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YLГ–S painikkeilla. Paina VГ„LILYГ–NTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirtyГ¤ksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina VГ„LILYГ–NTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"PienennГ¤ tyГ¶kalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:"Siirry aiempaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryГ¤ksesi lГ¤himpГ¤Г¤n kursorin edellГ¤ olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkГ¤istГ¤ HR elementtiГ¤. Toista nГ¤ppГ¤inyhdistelmГ¤Г¤ pГ¤Г¤stГ¤ksesi kauempana oleviin fokustiloihin."},
{name:"Siirry seuraavaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiryГ¤ksesi lГ¤himpГ¤Г¤n kursorin jГ¤lkeen olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekkГ¤istГ¤ HR elementtiГ¤. Toista nГ¤ppГ¤inyhdistelmГ¤Г¤ pГ¤Г¤stГ¤ksesi kauempana oleviin fokustiloihin."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",
downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"NumeronГ¤ppГ¤imistГ¶ 0",numpad1:"NumeronГ¤ppГ¤imistГ¶ 1",numpad2:"NumeronГ¤ppГ¤imistГ¶ 2",numpad3:"NumeronГ¤ppГ¤imistГ¶ 3",numpad4:"NumeronГ¤ppГ¤imistГ¶ 4",numpad5:"NumeronГ¤ppГ¤imistГ¶ 5",numpad6:"NumeronГ¤ppГ¤imistГ¶ 6",numpad7:"NumeronГ¤ppГ¤imistГ¶ 7",numpad8:"NumeronГ¤ppГ¤imistГ¶ 8",numpad9:"NumeronГ¤ppГ¤imistГ¶ 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",
divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Puolipiste",equalSign:"Equal Sign",comma:"Pilkku",dash:"Dash",period:"Piste",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});