п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilitГ©",contents:"Contenu de l'aide. Pour fermer cette fenГЄtre, appuyez sur la touche Г‰chap.",legend:[{name:"GГ©nГ©ral",items:[{name:"Barre d'outils de l'Г©diteur",legend:"Appuyer sur ${toolbarFocus} pour accГ©der Г  la barre d'outils. Se dГ©placer vers le groupe suivant ou prГ©cГ©dent de la barre d'outils avec les touches Tab et Maj+Tab. Se dГ©placer vers le bouton suivant ou prГ©cГ©dent de la barre d'outils avec les touches FlГЁche droite et FlГЁche gauche. Appuyer sur la barre d'espace ou la touche EntrГ©e pour activer le bouton de barre d'outils."},
{name:"FenГЄtre de l'Г©diteur",legend:"Dans une boГ®te de dialogue, appuyer sur Tab pour passer Г  l'Г©lГ©ment suivant, appuyer sur Maj+Tab pour passer Г  l'Г©lГ©ment prГ©cГ©dent, appuyer sur EntrГ©e pour valider, appuyer sur Г‰chap pour annuler. Quand une boГ®te de dialogue possГЁde des onglets, la liste peut ГЄtre atteinte avec Alt+F10 ou avec Tab. Dans la liste des onglets, se dГ©placer vers le suivant et le prГ©cГ©dent avec les touches FlГЁche droite et FlГЁche gauche respectivement."},{name:"Menu contextuel de l'Г©diteur",
legend:"Appuyer sur ${contextMenu} ou sur la touche Menu pour ouvrir le menu contextuel. Se dГ©placer ensuite vers l'option suivante du menu avec les touches Tab ou FlГЁche bas. Se dГ©placer vers l'option prГ©cГ©dente avec les touches Maj+Tab ou FlГЁche haut. Appuyer sur la barre d'espace ou la touche EntrГ©e pour sГ©lectionner l'option du menu. Appuyer sur la barre d'espace, la touche EntrГ©e ou FlГЁche droite pour ouvrir le sous-menu de l'option sГ©lectionnГ©e. Revenir Г  l'Г©lГ©ment de menu parent avec la touche Г‰chap ou FlГЁche gauche. Fermer le menu contextuel avec Г‰chap."},
{name:"Zone de liste de l'Г©diteur",legend:"Dans une liste en menu dГ©roulant, se dГ©placer vers l'Г©lГ©ment suivant de la liste avec les touches Tab ou FlГЁche bas. Se dГ©placer vers l'Г©lГ©ment prГ©cГ©dent de la liste avec les touches Maj+Tab ou FlГЁche haut. Appuyer sur la barre d'espace ou sur EntrГ©e pour sГ©lectionner l'option dans la liste. Appuyer sur Г‰chap pour fermer le menu dГ©roulant."},{name:"Barre du chemin d'Г©lГ©ments de l'Г©diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre du fil d'Ariane des Г©lГ©ments. Se dГ©placer vers le bouton de l'Г©lГ©ment suivant avec les touches Tab ou FlГЁche droite. Se dГ©placer vers le bouton prГ©cГ©dent avec les touches Maj+Tab ou FlГЁche gauche. Appuyer sur la barre d'espace ou sur EntrГ©e pour sГ©lectionner l'Г©lГ©ment dans l'Г©diteur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Commande restaurer",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande soulignГ©",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Commande d'accГЁs Г  l'Г©lГ©ment sГ©lectionnable prГ©cГ©dent",
legend:"Appuyer sur ${accessNextSpace} pour accГ©der Г  l'Г©lГ©ment sГ©lectionnable inatteignable le plus proche avant le curseur, par exempleВ : deux lignes horizontales adjacentes. RГ©pГ©ter la combinaison de touches pour atteindre les Г©lГ©ments sГ©lectionnables prГ©cГ©dents."},{name:"Commande d'accГЁs Г  l'Г©lГ©ment sГ©lectionnable suivant",legend:"Appuyer sur ${accessNextSpace} pour accГ©der Г  l'Г©lГ©ment sГ©lectionnable inatteignable le plus proche aprГЁs le curseur, par exempleВ : deux lignes horizontales adjacentes. RГ©pГ©ter la combinaison de touches pour atteindre les Г©lГ©ments sГ©lectionnables suivants."},
{name:" Aide sur l'accessibilitГ©",legend:"Appuyer sur ${a11yHelp}"}]}],tab:"Tabulation",pause:"Pause",capslock:"Verr. Maj.",escape:"Г‰chap",pageUp:"Page supГ©rieure",pageDown:"Page suivante",leftArrow:"FlГЁche gauche",upArrow:"FlГЁche haut",rightArrow:"FlГЁche droite",downArrow:"FlГЁche basse",insert:"Inser",leftWindowKey:"Touche Windows gauche",rightWindowKey:"Touche Windows droite",selectKey:"Touche SГ©lectionner",numpad0:"0 du pavГ© numГ©rique",numpad1:"1 du pavГ© numГ©rique",numpad2:"2 du pavГ© numГ©rique",
numpad3:"3 du pavГ© numГ©rique",numpad4:"4 du pavГ© numГ©rique",numpad5:"5 du pavГ© numГ©rique",numpad6:"6 du pavГ© numГ©rique",numpad7:"7 du pavГ© numГ©rique",numpad8:"PavГ© numГ©rique 8",numpad9:"9 du pavГ© numГ©rique",multiply:"Multiplier",add:"Plus",subtract:"Moins",decimalPoint:"Point dГ©cimal",divide:"Diviser",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Verr. Num.",scrollLock:"ArrГЄt dГ©fil.",semiColon:"Point-virgule",equalSign:"Signe Г©gal",
comma:"Virgule",dash:"Tiret",period:"Point",forwardSlash:"Barre oblique",graveAccent:"Accent grave",openBracket:"ParenthГЁse ouvrante",backSlash:"Barre oblique inverse",closeBracket:"ParenthГЁse fermante",singleQuote:"Apostrophe"});