п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","gl",{title:"InstruciГіns de accesibilidade",contents:"Axuda. Para pechar este diГЎlogo prema ESC.",legend:[{name:"Xeral",items:[{name:"Barra de ferramentas do editor",legend:"Prema ${toolbarFocus} para navegar pola barra de ferramentas. Para moverse polos distintos grupos de ferramentas use as teclas TAB e MAIГљS+TAB. Para moverse polas distintas ferramentas use FRECHA DEREITA ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para activar o botГіn da barra de ferramentas."},
{name:"Editor de diГЎlogo",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor do menГє contextual",legend:"Prema ${contextMenu} ou a TECLA MENГљ para abrir o menГє contextual. A seguir mГіvase ГЎ seguinte opciГіn do menГє con TAB ou FRECHA ABAIXO. MГіvase ГЎ opciГіn anterior con MAIГљS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para seleccionar a opciГіn do menГє. Abra o submenГє da opciГіn actual con ESPAZO ou INTRO ou FRECHA DEREITA. Regrese ao elemento principal do menГє con ESC ou FRECHA ESQUERDA. Peche o menГє contextual con ESC."},
{name:"Lista do editor",legend:"Dentro dunha lista, mГіvase ao seguinte elemento da lista con TAB ou FRECHA ABAIXO. MГіvase ao elemento anterior da lista con MAIГљS+TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para escoller a opciГіn da lista. Prema ESC para pechar a lista."},{name:"Barra da ruta ao elemento no editor",legend:"Prema ${elementsPathFocus} para navegar ata os elementos da barra de ruta. MГіvase ao seguinte elemento botГіn con TAB ou FRECHA DEREITA. MГіvase ao botГіn anterior con MAIГљS+TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar o elemento no editor."}]},
{name:"Ordes",items:[{name:"Orde В«desfacerВ»",legend:"Prema ${undo}"},{name:"Orde В«refacerВ»",legend:"Prema ${redo}"},{name:"Orde В«negraВ»",legend:"Prema ${bold}"},{name:"Orde В«cursivaВ»",legend:"Prema ${italic}"},{name:"Orde В«subliГ±arВ»",legend:"Prema ${underline}"},{name:"Orde В«ligazГіnВ»",legend:"Prema ${link}"},{name:"Orde В«contraer a barra de ferramentasВ»",legend:"Prema ${toolbarCollapse}"},{name:"Orde В«acceder ao anterior espazo en focoВ»",legend:"Prema ${accessPreviousSpace} para acceder ao espazo mГЎis prГіximo de foco inalcanzГЎbel anterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinaciГіn de teclas para chegar a espazos de foco distantes."},
{name:"Orde В«acceder ao seguinte espazo en focoВ»",legend:"Prema ${accessNextSpace} para acceder ao espazo mГЎis prГіximo de foco inalcanzГЎbel posterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinaciГіn de teclas para chegar a espazos de foco distantes."},{name:"Axuda da accesibilidade",legend:"Prema ${a11yHelp}"}]}],tab:"Tabulador",pause:"Pausa",capslock:"Bloq. MaiГєs",escape:"Escape",pageUp:"PГЎxina arriba",pageDown:"PГЎxina abaixo",leftArrow:"Frecha esquerda",upArrow:"Frecha arriba",
rightArrow:"Frecha dereita",downArrow:"Frecha abaixo",insert:"Inserir",leftWindowKey:"Tecla Windows esquerda",rightWindowKey:"Tecla Windows dereita",selectKey:"Escolla a tecla",numpad0:"Tec. numГ©rico 0",numpad1:"Tec. numГ©rico 1",numpad2:"Tec. numГ©rico 2",numpad3:"Tec. numГ©rico 3",numpad4:"Tec. numГ©rico 4",numpad5:"Tec. numГ©rico 5",numpad6:"Tec. numГ©rico 6",numpad7:"Tec. numГ©rico 7",numpad8:"Tec. numГ©rico 8",numpad9:"Tec. numГ©rico 9",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto decimal",
divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Bloq. num.",scrollLock:"Bloq. despraz.",semiColon:"Punto e coma",equalSign:"Signo igual",comma:"Coma",dash:"GuiГіn",period:"Punto",forwardSlash:"Barra inclinada",graveAccent:"Acento grave",openBracket:"Abrir corchete",backSlash:"Barra invertida",closeBracket:"Pechar corchete",singleQuote:"ComiГ±a simple"});