п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","he",{title:"Ч”Ч•ЧЁЧђЧ•ЧЄ Ч Ч’Ч™Ч©Ч•ЧЄ",contents:"Ч”Ч•ЧЁЧђЧ•ЧЄ Ч Ч’Ч™Ч©Ч•ЧЄ. ЧњЧЎЧ’Ч™ЧЁЧ” ЧњЧ—ЧҐ ЧђЧЎЧ§Ч™Ч™Ч¤ (ESC).",legend:[{name:"Ч›ЧњЧњЧ™",items:[{name:"ЧЎЧЁЧ’Чњ Ч”Ч›ЧњЧ™Чќ",legend:"ЧњЧ—ЧҐ ЧўЧњ ${toolbarFocus} Ч›Ч“Ч™ ЧњЧ Ч•Ч•Ч� ЧњЧЎЧЁЧ’Чњ Ч”Ч›ЧњЧ™Чќ. ЧўЧ‘Ч•ЧЁ ЧњЧ›Ч¤ЧЄЧ•ЧЁ Ч”Ч‘Чђ ЧўЧќ ЧћЧ§Ч© Ч”Ч�ЧђЧ‘ (TAB) ЧђЧ• Ч—ЧҐ Ч©ЧћЧђЧњЧ™. ЧўЧ‘Ч•ЧЁ ЧњЧ›Ч¤ЧЄЧ•ЧЁ Ч”Ч§Ч•Ч“Чќ ЧўЧќ ЧћЧ§Ч© Ч”Ч©Ч™Ч¤Ч� (SHIFT) + Ч�ЧђЧ‘ (TAB) ЧђЧ• Ч—ЧҐ Ч™ЧћЧ Ч™. ЧњЧ—ЧҐ ЧЁЧ•Ч•Ч— ЧђЧ• ЧђЧ Ч�ЧЁ (ENTER) Ч›Ч“Ч™ ЧњЧ”Ч¤ЧўЧ™Чњ ЧђЧЄ Ч”Ч›Ч¤ЧЄЧ•ЧЁ Ч”Ч Ч‘Ч—ЧЁ."},{name:"Ч“Ч™ЧђЧњЧ•Ч’Ч™Чќ (Ч—ЧњЧ•Ч Ч•ЧЄ ЧЄЧ©ЧђЧ•Чњ)",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"ЧЄЧ¤ЧЁЧ™Ч� Ч”Ч”Ч§Ч©ЧЁ (Context Menu)",legend:"ЧњЧ—ЧҐ ${contextMenu} ЧђЧ• APPLICATION KEYЧ›Ч“Ч™ ЧњЧ¤ЧЄЧ•Ч— ЧђЧЄ ЧЄЧ¤ЧЁЧ™Ч� Ч”Ч”Ч§Ч©ЧЁ. ЧўЧ‘Ч•ЧЁ ЧњЧђЧ¤Ч©ЧЁЧ•ЧЄ Ч”Ч‘ЧђЧ” ЧўЧќ Ч�ЧђЧ‘ (TAB) ЧђЧ• Ч—ЧҐ ЧњЧћЧ�Ч”. ЧўЧ‘Ч•ЧЁ ЧњЧђЧ¤Ч©ЧЁЧ•ЧЄ Ч”Ч§Ч•Ч“ЧћЧЄ ЧўЧќ Ч©Ч™Ч¤Ч� (SHIFT) + Ч�ЧђЧ‘ (TAB) ЧђЧ• Ч—ЧҐ ЧњЧћЧўЧњЧ”. ЧњЧ—ЧҐ ЧЁЧ•Ч•Ч— ЧђЧ• ЧђЧ Ч�ЧЁ (ENTER) Ч›Ч“Ч™ ЧњЧ‘Ч—Ч•ЧЁ ЧђЧЄ Ч”ЧђЧ¤Ч©ЧЁЧ•ЧЄ. Ч¤ЧЄЧ— ЧђЧЄ ЧЄЧЄ Ч”ЧЄЧ¤ЧЁЧ™Ч� (Sub-menu) Ч©Чњ Ч”ЧђЧ¤Ч©ЧЁЧ•ЧЄ Ч”Ч Ч•Ч›Ч—Ч™ЧЄ ЧўЧќ ЧЁЧ•Ч•Ч— ЧђЧ• ЧђЧ Ч�ЧЁ (ENTER) ЧђЧ• Ч—ЧҐ Ч©ЧћЧђЧњЧ™. Ч—Ч–Ч•ЧЁ ЧњЧЄЧ¤ЧЁЧ™Ч� Ч”ЧђЧ‘ ЧўЧќ ЧђЧЎЧ§Ч™Ч™Ч¤ (ESC) ЧђЧ• Ч—ЧҐ Ч©ЧћЧђЧњЧ™. ЧЎЧ’Ч•ЧЁ ЧђЧЄ ЧЄЧ¤ЧЁЧ™Ч� Ч”Ч”Ч§Ч©ЧЁ ЧўЧќ ЧђЧЎЧ§Ч™Ч™Ч¤ (ESC)."},{name:"ЧЄЧ¤ЧЁЧ™Ч�Ч™Чќ Ч¦Ч¤Ч™Чќ (List boxes)",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"ЧўЧҐ ЧђЧњЧћЧ Ч�Ч™Чќ (Elements Path)",legend:"ЧњЧ—ЧҐ ${elementsPathFocus} Ч›Ч“Ч™ ЧњЧ Ч•Ч•Ч� ЧњЧўЧҐ Ч”ЧђЧњЧћЧ Ч�Ч™Чќ. ЧўЧ‘Ч•ЧЁ ЧњЧ¤ЧЁЧ™Ч� Ч”Ч‘Чђ ЧўЧќ Ч�ЧђЧ‘ (TAB) ЧђЧ• Ч—ЧҐ Ч™ЧћЧ Ч™. ЧўЧ‘Ч•ЧЁ ЧњЧ¤ЧЁЧ™Ч� Ч”Ч§Ч•Ч“Чќ ЧўЧќ Ч©Ч™Ч¤Ч� (SHIFT) + Ч�ЧђЧ‘ (TAB) ЧђЧ• Ч—ЧҐ Ч©ЧћЧђЧњЧ™. ЧњЧ—ЧҐ ЧЁЧ•Ч•Ч— ЧђЧ• ЧђЧ Ч�ЧЁ (ENTER) Ч›Ч“Ч™ ЧњЧ‘Ч—Ч•ЧЁ ЧђЧЄ Ч”ЧђЧњЧћЧ Ч� Ч‘ЧўЧ•ЧЁЧљ."}]},{name:"Ч¤Ч§Ч•Ч“Ч•ЧЄ",items:[{name:" Ч‘Ч™Ч�Ч•Чњ Ч¦ЧўЧ“ ЧђЧ—ЧЁЧ•Чџ",legend:"ЧњЧ—ЧҐ ${undo}"},{name:" Ч—Ч–ЧЁЧ” ЧўЧњ Ч¦ЧўЧ“ ЧђЧ—ЧЁЧ•Чџ",legend:"ЧњЧ—ЧҐ ${redo}"},{name:" Ч”Ч“Ч’Ч©Ч”",legend:"ЧњЧ—ЧҐ ${bold}"},{name:" Ч”Ч�Ч™Ч™Ч”",legend:"ЧњЧ—ЧҐ ${italic}"},{name:" Ч”Ч•ЧЎЧ¤ЧЄ Ч§Ч• ЧЄЧ—ЧЄЧ•Чџ",legend:"ЧњЧ—ЧҐ ${underline}"},{name:" Ч”Ч•ЧЎЧ¤ЧЄ ЧњЧ™Ч Ч§",
legend:"ЧњЧ—ЧҐ ${link}"},{name:" Ч›Ч™Ч•Ч•ЧҐ ЧЎЧЁЧ’Чњ Ч”Ч›ЧњЧ™Чќ",legend:"ЧњЧ—ЧҐ ${toolbarCollapse}"},{name:"Ч’Ч™Ч©Ч” ЧњЧћЧ™Ч§Ч•Чќ Ч”ЧћЧ™Ч§Ч•Ч“ Ч”Ч§Ч•Ч“Чќ",legend:"ЧњЧ—ЧҐ ${accessPreviousSpace} Ч›Ч“Ч™ ЧњЧ’Ч©ЧЄ ЧњЧћЧ™Ч§Ч•Чќ Ч”ЧћЧ™Ч§Ч•Ч“ Ч”ЧњЧђ-Ч Ч’Ч™Ч© Ч”Ч§ЧЁЧ•Ч‘ ЧњЧ¤Ч Ч™ Ч”ЧЎЧћЧџ, ЧњЧћЧ©Чњ Ч‘Ч™Чџ Ч©Ч Ч™ ЧђЧњЧћЧ Ч�Ч™Чќ ЧЎЧћЧ•Ч›Ч™Чќ ЧћЧЎЧ•Ч’ HR. Ч—Ч–Ч•ЧЁ ЧўЧњ Ч¦Ч™ЧЁЧ•ЧЈ ЧћЧ§Ч©Ч™Чќ Ч–Ч” Ч›Ч“Ч™ ЧњЧ”Ч’Ч™Чў ЧњЧћЧ§Ч•ЧћЧ•ЧЄ ЧћЧ™Ч§Ч•Ч“ ЧЁЧ—Ч•Ч§Ч™Чќ Ч™Ч•ЧЄЧЁ."},{name:"Ч’Ч™Ч©Ч” ЧњЧћЧ™Ч§Ч•Чќ Ч”ЧћЧ™Ч§Ч•Ч“ Ч”Ч‘Чђ",legend:"ЧњЧ—ЧҐ ${accessNextSpace} Ч›Ч“Ч™ ЧњЧ’Ч©ЧЄ ЧњЧћЧ™Ч§Ч•Чќ Ч”ЧћЧ™Ч§Ч•Ч“ Ч”ЧњЧђ-Ч Ч’Ч™Ч© Ч”Ч§ЧЁЧ•Ч‘ ЧђЧ—ЧЁЧ™ Ч”ЧЎЧћЧџ, ЧњЧћЧ©Чњ Ч‘Ч™Чџ Ч©Ч Ч™ ЧђЧњЧћЧ Ч�Ч™Чќ ЧЎЧћЧ•Ч›Ч™Чќ ЧћЧЎЧ•Ч’ HR. Ч—Ч–Ч•ЧЁ ЧўЧњ Ч¦Ч™ЧЁЧ•ЧЈ ЧћЧ§Ч©Ч™Чќ Ч–Ч” Ч›Ч“Ч™ ЧњЧ”Ч’Ч™Чў ЧњЧћЧ§Ч•ЧћЧ•ЧЄ ЧћЧ™Ч§Ч•Ч“ ЧЁЧ—Ч•Ч§Ч™Чќ Ч™Ч•ЧЄЧЁ."},
{name:" Ч”Ч•ЧЁЧђЧ•ЧЄ Ч Ч’Ч™Ч©Ч•ЧЄ",legend:"ЧњЧ—ЧҐ ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Ч—ЧҐ Ч©ЧћЧђЧњЧ”",upArrow:"Ч—ЧҐ ЧњЧћЧўЧњЧ”",rightArrow:"Ч—ЧҐ Ч™ЧћЧ™Ч Ч”",downArrow:"Ч—ЧҐ ЧњЧћЧ�Ч”",insert:"Ч”Ч›Ч ЧЎ",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Ч‘Ч—ЧЁ ЧћЧ§Ч©",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",
numpad9:"Numpad 9",multiply:"Multiply",add:"Ч”Ч•ЧЎЧЈ",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"ЧЎЧњЧђЧ©",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"ЧЎЧњЧђЧ© Ч”Ч¤Ч•Чљ",closeBracket:"Close Bracket",singleQuote:"Ч¦Ч™Ч�Ч•Ч� Ч™Ч—Ч™Ч“"});