п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"KisegГ­tЕ‘ utasГ­tГЎsok",contents:"SГєgГі tartalmak. A pГЎrbeszГ©dablak bezГЎrГЎsГЎhoz nyomjon ESC-et.",legend:[{name:"ГЃltalГЎnos",items:[{name:"SzerkesztЕ‘ EszkГ¶ztГЎr",legend:"Nyomjon ${toolbarFocus} hogy kijelГ¶lje az eszkГ¶ztГЎrat. A kГ¶vetkezЕ‘ Г©s elЕ‘zЕ‘ eszkГ¶ztГЎr csoporthoz a TAB Г©s SHIFT+TAB-al juthat el. A kГ¶vetkezЕ‘ Г©s elЕ‘zЕ‘ eszkГ¶ztГЎr gombhoz a BAL NYГЌL vagy JOBB NYГЌL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktivГЎlja az eszkГ¶ztГЎr gombot."},{name:"SzerkeszЕ‘ pГЎrbeszГ©d ablak",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"SzerkesztЕ‘ helyi menГј",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZГЃS BILLENTYЕ°T a helyi menГј megnyitГЎsГЎhoz. EzutГЎn a kГ¶vetkezЕ‘ menГјpontra lГ©phet a TAB vagy LEFELГ‰ NYГЌLLAL. Az elЕ‘zЕ‘ opciГіt a SHIFT+TAB vagy FELFELГ‰ NYГЌLLAL Г©rheti el. Nyomjon SPACE-t vagy ENTER-t a menГјpont kivГЎlasztГЎsГЎhoz. A jelenlegi menГјpont almenГјjГ©nek megnyitГЎsГЎhoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A fЕ‘menГјhГ¶z valГі visszatГ©rГ©shez nyomjon ESC-et vagy BAL NYILAT. A helyi menГј bezГЎrГЎsa az ESC billentyЕ±vel lehetsГ©ges."},
{name:"SzerkesztЕ‘ lista",legend:"A listГЎn belГјl a kГ¶vetkezЕ‘ elemre a TAB vagy LEFELГ‰ NYГЌLLAL mozoghat. Az elЕ‘zЕ‘ elem kivГЎlasztГЎsГЎhoz nyomjon SHIFT+TAB-ot vagy FELFELГ‰ NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kivГЎlasztГЎsГЎhoz. Az ESC billentyЕ± megnyomГЎsГЎval bezГЎrhatja a listГЎt."},{name:"SzerkesztЕ‘ elem utak sГЎv",legend:"Nyomj ${elementsPathFocus} hogy kijelГ¶ld a elemek Гєt sГЎvjГЎt. A kГ¶vetkezЕ‘ elem gombhoz a TAB-al vagy a JOBB NYГЌLLAL juthatsz el. Az elЕ‘zЕ‘ gombhoz a SHIFT+TAB vagy BAL NYГЌLLAL mehetsz. A SPACE vagy ENTER billentyЕ±vel kivГЎlaszthatod az elemet a szerkesztЕ‘ben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonГЎsa",legend:"Nyomj ${undo}"},{name:"Parancs megismГ©tlГ©se",legend:"Nyomjon ${redo}"},{name:"FГ©lkГ¶vГ©r parancs",legend:"Nyomjon ${bold}"},{name:"DЕ‘lt parancs",legend:"Nyomjon ${italic}"},{name:"AlГЎhГєzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"SzerkesztЕ‘sГЎv Г¶sszecsukГЎsa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"HozzГЎfГ©rГ©s az elЕ‘zЕ‘ fГіkusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzГЎfГ©rj a legkГ¶zelebbi elГ©rhetetlen fГіkusz helyhez a hiГЎnyjel elЕ‘tt, pГ©ldГЎul: kГ©t szomszГ©dos HR elemhez. IsmГ©teld meg a billentyЕ±kombinГЎciГіt hogy megtalГЎld a tГЎvolabbi fГіkusz helyeket."},
{name:"HozzГЎfГ©rГ©s a kГ¶vetkezЕ‘ fГіkusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzГЎfГ©rj a legkГ¶zelebbi elГ©rhetetlen fГіkusz helyhez a hiГЎnyjel utГЎn, pГ©ldГЎul: kГ©t szomszГ©dos HR elemhez. IsmГ©teld meg a billentyЕ±kombinГЎciГіt hogy megtalГЎld a tГЎvolabbi fГіkusz helyeket."},{name:"KisegГ­tЕ‘ sГєgГі",legend:"Nyomjon ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"balra nyГ­l",upArrow:"felfelГ© nyГ­l",rightArrow:"jobbra nyГ­l",
downArrow:"lefelГ© nyГ­l",insert:"Insert",leftWindowKey:"bal Windows-billentyЕ±",rightWindowKey:"jobb Windows-billentyЕ±",selectKey:"BillentyЕ± vГЎlasztГЎsa",numpad0:"SzГЎmbillentyЕ±k 0",numpad1:"SzГЎmbillentyЕ±k 1",numpad2:"SzГЎmbillentyЕ±k 2",numpad3:"SzГЎmbillentyЕ±k 3",numpad4:"SzГЎmbillentyЕ±k 4",numpad5:"SzГЎmbillentyЕ±k 5",numpad6:"SzГЎmbillentyЕ±k 6",numpad7:"SzГЎmbillentyЕ±k 7",numpad8:"SzГЎmbillentyЕ±k 8",numpad9:"SzГЎmbillentyЕ±k 9",multiply:"SzorzГЎs",add:"HozzГЎadГЎs",subtract:"KivonГЎs",decimalPoint:"Tizedespont",
divide:"OsztГЎs",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"PontosvesszЕ‘",equalSign:"EgyenlЕ‘sГ©gjel",comma:"VesszЕ‘",dash:"KГ¶tЕ‘jel",period:"Pont",forwardSlash:"Perjel",graveAccent:"VisszafelГ© dЕ‘lЕ‘ Г©kezet",openBracket:"NyitГі szГ¶gletes zГЎrГіjel",backSlash:"fordГ­tott perjel",closeBracket:"ZГЎrГі szГ¶gletes zГЎrГіjel",singleQuote:"szimpla idГ©zЕ‘jel"});