п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","km",{title:"Accessibility Instructions",contents:"бћ�бћ¶бћЏбћ·бћЂбћ¶вЂ‹бћ‡бџ†бћ“бћЅбћ™бџ” бћЉбћѕбћ�бџ’бћ”бћёвЂ‹бћ”бћ·бћ‘вЂ‹бћ•бџ’бћ‘бћ¶бџ†бћ„вЂ‹бћ“бџЃбџ‡ бћџбћјбћ�вЂ‹бћ…бћ»бћ… ESC бџ”",legend:[{name:"бћ‘бћјбћ‘бџ…",items:[{name:"бћљбћ”бћ¶бћљвЂ‹бћ§бћ”бћЂбћљбћЋбџЌвЂ‹бћЂбћ�бџ’бћ�бћњбћ·бћ’бћёвЂ‹бћ“бћ·бћ–бћ“бџ’бћ’",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"бћ•бџ’бћ‘бћ¶бџ†бћ„вЂ‹бћЂбћ�бџ’бћ�бћњбћ·бћ’бћёбћ“бћ·бћ–бћ“бџ’бћ’",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"бћ�бџ‰бћёбћ“бћ»бћ™бћ”бћљбћ·бћ”бћ‘бћўбџ’бћ“бћЂбћЂбџ‚бћџбћ�бџ’бћљбћЅбћ›",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"бћ”бџ’бћљбћўбћ”бџ‹бћ”бћ‰бџ’бћ‡бћёбћўбџ’бћ“бћЂбћЂбџ‚бћџбћ�бџ’бћљбћЅбћ›",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"бћ–бћ¶бћЂбџ’бћ™бћ”бћ‰бџ’бћ‡бћ¶",items:[{name:"бћЂбћ¶бћљвЂ‹бћ”бћ‰бџ’бћ‡бћ¶вЂ‹бћ�бћ·бћ“бћ’бџ’бћњбћѕбћњбћ·бћ‰",legend:"бћ…бћ»бћ… ${undo}"},{name:"бћЂбћ¶бћљбћ”бћ‰бџ’бћ‡бћ¶вЂ‹бћ’бџ’бћњбћѕбћњбћ·бћ‰",legend:"бћ…бћ»бћ… ${redo}"},{name:"бћЂбћ¶бћљбћ”бћ‰бџ’бћ‡бћ¶вЂ‹бћўбћЂбџ’бћџбћљвЂ‹бћЉбћ·бћЏ",legend:"бћ…бћ»бћ… ${bold}"},{name:"бћЂбћ¶бћљбћ”бћ‰бџ’бћ‡бћ¶вЂ‹бћўбћЂбџ’бћџбћљвЂ‹бћ‘бџ’бћљбџЃбћЏ",legend:"бћ…бћ»бћ… ${italic}"},{name:"бћ–бћ¶бћЂбџ’бћ™бћ”бћ‰бџ’бћ‡бћ¶вЂ‹бћ”бћ“бџ’бћ‘бћ¶бћЏбџ‹вЂ‹бћ–бћёбћЂбџ’бћљбџ„бћ�",
legend:"бћ…бћ»бћ… ${underline}"},{name:"бћ–бћ¶бћЂбџ’бћ™бћ”бћ‰бџ’бћ‡бћ¶вЂ‹бћЏбџ†бћЋ",legend:"бћ…бћ»бћ… ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"бћ‡бџ†бћ“бћЅбћ™вЂ‹бћ–бћёвЂ‹бћ—бћ¶бћ–вЂ‹бћ„бћ¶бћ™бћџбџ’бћљбћЅбћ›",legend:"бћ‡бћЅбћ™ ${a11yHelp}"}]}],tab:"Tab",pause:"бћ•бџ’бћўбћ¶бћЂ",capslock:"Caps Lock",escape:"бћ…бћ¶бћЂбћ…бџЃбћ‰",pageUp:"бћ‘бџ†бћ–бџђбћљвЂ‹бћ›бћѕ",pageDown:"бћ‘бџ†бћ–бџђбћљвЂ‹бћЂбџ’бћљбџ„бћ�",leftArrow:"бћ–бџ’бћљбћЅбћ‰вЂ‹бћ†бџ’бћњбџЃбћ„",upArrow:"бћ–бџ’бћљбћЅбћ‰вЂ‹бћ›бћѕ",rightArrow:"бћ–бџ’бћљбћЅбћ‰вЂ‹бћџбџ’бћЉбћ¶бџ†",downArrow:"бћ–бџ’бћљбћЅбћ‰вЂ‹бћЂбџ’бћљбџ„бћ�",insert:"бћ”бћ‰бџ’бћ…бћјбћ›",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"бћ‡бџ’бћљбћѕбћџвЂ‹бћ‚бџ’бћљбћ¶бћ”бџ‹вЂ‹бћ…бћ»бћ…",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",
numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"бћ‚бћ»бћЋ",add:"бћ”бћ“бџ’бћђбџ‚бћ�",subtract:"бћЉбћЂ",decimalPoint:"бћ…бџ†бћЋбћ»бћ…бћ‘бћџбћ—бћ¶бћ‚",divide:"бћ…бџ‚бћЂ",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"бћ”бћ·бћ‘вЂ‹бћљбџ†бћЂбћ·бћ›",semiColon:"бћ…бћ»бћ…вЂ‹бћЂбџ’бћ”бџЂбћџ",equalSign:"бћџбћ‰бџ’бћ‰бћ¶вЂ‹бћўбћєбћљбџ‰бћј",comma:"бћЂбџ’бћ”бџЂбћџ",dash:"Dash",period:"бћ…бћ»бћ…",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"бћЏбћ„бџ’бћЂбџЂбћ”вЂ‹бћ”бћѕбћЂ",backSlash:"Backslash",closeBracket:"бћЏбћ„бџ’бћЂбџЂбћ”вЂ‹бћ”бћ·бћ‘",singleQuote:"бћ”бћ“бџ’бћЏбћЂбџ‹вЂ‹бћ�бћЅбћ™"});