п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ku",{title:"Ъ•ЫЋЩ†Щ…Ш§ЫЊ Щ„Ы•ШЁЫ•Ш±ШЇЫ•ШіШЄШЇШ§ШЁЩ€Щ€Щ†",contents:"ЩѕЫЋЪ©Щ‡Ш§ШЄЫ•ЫЊ ЫЊШ§Ш±Щ…Ы•ШЄЫЊ. Ъ©Щ„ЫЊЩѓ ESC ШЁЫ† ШЇШ§Ш®ШіШЄЩ†ЫЊ Ш¦Ы•Щ… ШЇЫЊШ§Щ„Ы†ЪЇЩ‡.",legend:[{name:"ЪЇШґШЄЫЊ",items:[{name:"ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІЫЊ ШЇЫ•ШіШЄЩѓШ§Ш±ЫЊЩѓЫ•Ш±",legend:"Ъ©Щ„ЫЊЩѓ ${toolbarFocus} ШЁЫ† Ъ•Ш§ШЁЫ•Ш±ЫЊ ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІ. ШЁЫ† ЪЇЩ€Ш§ШіШЄЩ†Ы•Щ€Ы•ЫЊ ЩѕЫЋШґЩ€Щ€ ШЇШ§Щ‡Ш§ШЄЩ€Щ€ЫЊ ЪЇШ±Щ€Щ€ЩѕЫЊ ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІЫЊ ШЇШ§ЪЇШ±ШЄЩ†ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ TAB Щ„Ы•ЪЇЫ•ЪµвЂЊ SHIFT+TAB. ШЁЫ† ЪЇЩ€Ш§ШіШЄЩ†Ы•Щ€Ы•ЫЊ ЩѕЫЋШґЩ€Щ€ ШЇШ§Щ‡Ш§ШЄЩ€Щ€ЫЊ ШЇЩ€Щ€ЪЇЩ…Ы•ЫЊ ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІЫЊ Щ„Ы•Ъ•ЫЋЫЊ Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ ШЇЫ•ШіШЄЫЊ Ъ•Ш§ШіШЄ ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ ШЇЫ•ШіШЄЫЊ Ъ†Ы•Щѕ. Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SPACE ЫЊШ§Щ† ENTER ШЁЫ† Ъ†Ш§Щ„Ш§Ъ©Ъ©Ш±ШЇЩ†ЫЊ ШЇЩ€Щ€ЪЇЩ…Ы•ЫЊ ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІ."},{name:"ШЇЫЊШ§Щ„Ы†ЪЇЫЊ ШЇЫ•ШіШЄЩѓШ§Ш±ЫЊЩѓЫ•Ш±",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"ЩѕЫЋЪ•ШіШЄЫЊ ШіЫ•Ш±Щ†Щ€Щ€ШіЫ•Ш±",legend:"Ъ©Щ„ЫЊЩѓ ${contextMenu} ЫЊШ§Щ† ШЇЩ€ЪЇЩ…Ы•ЫЊ Щ„ЫЊШіШЄЩ‡вЂЊ(Menu) ШЁЫ† Ъ©Ш±ШЇЩ†Ы•Щ€Ы•ЫЊ Щ„ЫЊШіШЄЫ•ЫЊ ШЇЫ•Щ‚. ШЁЫ† Ъ†Щ€Щ€Щ†Ы• Щ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЫ•ЫЊЫ•Ъ©ЫЊ ШЄШ± Щ„Щ‡вЂЊ Щ„ЫЊШіШЄЩ‡вЂЊ Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ TAB ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ Ъ•Щ€Щ€ Щ„Ы•Ш®Щ€Ш§Ш±Ы•Щ€Щ‡вЂЊ ШЁЫ† Ъ†Щ€Щ€Щ† ШЁЫ† Щ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЫ•ЫЊ ЩѕЫЋШґЩ€Щ€ Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SHIFT+TAB ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ Ъ•Щ€Щ€ Щ„Щ‡вЂЊ ШіЫ•Ш±Ы•Щ€Ы•. ШЇШ§ЪЇШ±ШЄЩ†ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SPACE ЫЊШ§Щ† ENTER ШЁЫ† Щ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЩ†ЫЊ Щ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЫ•ЫЊ Щ„ЫЊШіШЄЩ‡вЂЊ. ШЁЫ† Ъ©Ш±ШЇЩ†Ы•Щ€Ы•ЫЊ Щ„Щ‚ЫЊ Ъ�ЫЋШ± Щ„ЫЊШіШЄЩ‡вЂЊ Щ„Ы•Щ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЫ•ЫЊ Щ„ЫЊШіШЄЫ• Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SPACE ЫЊШ§Щ† ENTER ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ ШЇЫ•ШіШЄЫЊ Ъ•Ш§ШіШЄ. ШЁЫ† ЪЇЫ•Ъ•Ш§Щ†Ы•Щ€Щ‡ ШЁЫ† ШіЫ•Ш±Ы•Щ€Ы•ЫЊ Щ„ЫЊШіШЄЩ‡вЂЊ Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ ESC ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ ШЇЫ•ШіШЄЫЊ Ъ†Ы•Щѕ. ШЁЫ† ШЇШ§Ш®ШіШЄЩ†ЫЊ Щ„ЫЊШіШЄЫ• Ъ©Щ„ЫЊЩѓЫЊ Ъ©Щ„ЫЊЩ„ЫЊ ESC ШЁЪ©Ы•."},
{name:"Щ„ЫЊШіШЄЫЊ ШіЩ†Щ€Щ€Щ‚ЫЊ ШіЫ•Ш±Щ†Щ€Щ€ШіЫ•Ш±",legend:"Щ„Ы•Щ†Ш§Щ€ ШіЩ†Щ€Щ‚ЫЊ Щ„ЫЊШіШЄ, Ъ†Ы†Щ† ШЁЫ† Щ‡Ы•ЪµЩ†ШЁЪ�Ш§Ш±ШЇЫ•ЫЊ Щ„ЫЊШіШЄЫЋЪ©ЫЊ ШЄШ± Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ TAB ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ Ъ•Щ€Щ€ Щ„Ы•Ш®Щ€Ш§Ш±. Ъ†Щ€Щ€Щ† ШЁЫ† Щ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЫ•ЫЊ Щ„ЫЊШіШЄЫЊ ЩѕЫЋШґЩ€Щ€ Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SHIFT+TAB ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ Ъ•Щ€Щ€ Щ„Ы•ШіЫ•Ш±Ы•Щ€Щ‡вЂЊ. Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SPACE ЫЊШ§Щ† ENTER ШЁЫ† ШЇЫЊШ§Ш±ЫЊЪ©Ш±ШЇЩ†ЫЊ вЂЊЩ‡Ы•ЪµШЁЪ�Ш§Ш±ШЇЫ•ЫЊ Щ„ЫЊШіШЄ. Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ ESC ШЁЫ† ШЇШ§Ш®ШіШЄЩ†ЫЊ ШіЩ†Щ€Щ‚ЫЊ Щ„ЫЊШіШЄ."},{name:"ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІЫЊ ШЄЩ€Ш®Щ…",legend:"Ъ©Щ„ЫЊЩѓ ${elementsPathFocus} ШЁЫ† Ъ•Ш§ШЁЫ•Ш±ЫЊ ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІЫЊ ШЄЩ€Ш®Щ…Ы•Ъ©Ш§Щ†. Ъ†Щ€Щ€Щ† ШЁЫ† ШЇЩ€ЪЇЩ…Ы•ЫЊ ШЄЩ€Ш®Щ…ЫЋЪ©ЫЊ ШЄШ± Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ TAB ЫЊШ§Щ† Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ ШЇЫ•ШіШЄЫЊ Ъ•Ш§ШіШЄ. Ъ†Щ€Щ€Щ† ШЁЫ† ШЇЩ€ЪЇЩ…Ы•ЫЊ ШЄЩ€Ш®Щ…ЫЊ ЩѕЫЋШґЩ€Щ€ Ъ©Щ„ЫЊЩ„ЫЊ SHIFT+TAB ЫЊШ§Щ† Ъ©Щ„ЫЊЪ©ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ ШЄЫЊШ±ЫЊ ШЇЫ•ШіШЄЫЊ Ъ†Ы•Щѕ. ШЇШ§ЪЇШ±ШЄЩ†ЫЊ Ъ©Щ„ЫЊЩ„ЫЊ SPACE ЫЊШ§Щ† ENTER ШЁЫ† ШЇЫЊШ§Ш±ЫЊЪ©Ш±ШЇЩ†ЫЊ ШЄЩ€Ш®Щ…Ы•Ъ©Щ‡вЂЊ Щ„Ы•ШіЫ•Ш±Щ†Щ€Щ€ШіЩ‡."}]},
{name:"ЩЃЫ•Ш±Щ…Ш§Щ†Ы•Ъ©Ш§Щ†",items:[{name:"ЩѕЩ€Щ€Ъ†Ъ©Ш±ШЇЩ†Ы•Щ€Ы•ЫЊ ЩЃЫ•Ш±Щ…Ш§Щ†",legend:"Ъ©Щ„ЫЊЩѓ ${undo}"},{name:"Щ‡Ы•ЪµЪЇЫ•Ъ•Ш§Щ†Ы•Щ€Ы•ЫЊ ЩЃЫ•Ш±Щ…Ш§Щ†",legend:"Ъ©Щ„ЫЊЩѓ ${redo}"},{name:"ЩЃЫ•Ш±Щ…Ш§Щ†ЫЊ ШЇЫ•Щ‚ЫЊ Щ‚Ы•ЪµЫ•Щ€",legend:"Ъ©Щ„ЫЊЩѓ ${bold}"},{name:"ЩЃЫ•Ш±Щ…Ш§Щ†ЫЊ ШЇЫ•Щ‚ЫЊ Щ„Ш§Ш±",legend:"Ъ©Щ„ЫЊЩѓ ${italic}"},{name:"ЩЃЫ•Ш±Щ…Ш§Щ†ЫЊ Ъ�ЫЋШ±Щ‡ЫЋЪµ",legend:"Ъ©Щ„ЫЊЩѓ ${underline}"},{name:"ЩЃЫ•Ш±Щ…Ш§Щ†ЫЊ ШЁЩ‡вЂЊШіШЄЫ•Ш±",legend:"Ъ©Щ„ЫЊЩѓ ${link}"},{name:"ШґШ§Ш±ШЇЫ•Щ†Ы•Щ€Ы•ЫЊ ШЄЩ€Щ€ЪµШ§Щ…Ш±Ш§ШІ",legend:"Ъ©Щ„ЫЊЩѓ ${toolbarCollapse}"},{name:"Ъ†Щ€Щ€Щ†Ы•Щ†Ш§Щ€ ШіЫ•Ш±Щ†Ш¬ШЇШ§Щ†ЫЊ ЩѕЫЋШґЩ€ЫЊ ЩЃЫ•Ш±Щ…Ш§Щ†ЫЊ ШЁЫ†ШґШ§ЫЊЫЊ",legend:"Ъ©Щ„ЫЊЪ© ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"Ъ†Щ€Щ€Щ†Ы•Щ†Ш§Щ€ ШіЫ•Ш±Щ†Ш¬ШЇШ§Щ†ЫЊ ШЇШ§Щ‡Ш§ШЄЩ€Щ€ЫЊ ЩЃЫ•Ш±Щ…Ш§Щ†ЫЊ ШЁЫ†ШґШ§ЫЊЫЊ",legend:"Ъ©Щ„ЫЊЪ© ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"ШЇЫ•ШіШЄЩѕЫЋЪЇЫ•ЫЊШґШЄЩ†ЫЊ ЫЊШ§Ш±Щ…Ы•ШЄЫЊ",legend:"Ъ©Щ„ЫЊЩѓ ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert",
leftWindowKey:"ЩѕЫ•Щ†Ш¬Ы•Ш±Ы•ЫЊ Ъ†Ы•Щѕ",rightWindowKey:"ЩѕЫ•Щ†Ш¬Ы•Ш±Ы•ЫЊ Ъ•Ш§ШіШЄ",selectKey:"Select",numpad0:"Numpad 0",numpad1:"1",numpad2:"2",numpad3:"3",numpad4:"4",numpad5:"5",numpad6:"6",numpad7:"7",numpad8:"8",numpad9:"9",multiply:"*",add:"+",subtract:"-",decimalPoint:".",divide:"/",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:";",equalSign:"\x3d",comma:",",dash:"-",period:".",forwardSlash:"/",graveAccent:"`",
openBracket:"[",backSlash:"\\\\",closeBracket:"}",singleQuote:"'"});