п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"PieejamД«bas instrukcija",contents:"PalД«dzД«bas saturs. Lai aizvД“rtu ciet ЕЎo dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora rД«kjosla",legend:"Nospiediet ${toolbarFocus} lai pДЃrvietotos uz rД«kjoslu. Lai pДЃrvietotos uz nДЃkoЕЎo vai iepriekЕЎД“jo rД«kjoslas grupu izmantojiet pogu TAB un SHIFT+TAB. Lai pДЃrvietotos uz nДЃkoЕЎo vai iepriekЕЎД“jo rД«kjoslas pogu izmantojiet Kreiso vai Labo bultiЕ†u. Nospiediet Atstarpi vai ENTER lai aktivizД“tu rД«kjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Redaktora satura izvД“le",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvД“rtu satura izvД“lni. Lai pДЃrvietotos uz nДЃkoЕЎo izvД“lnes opciju izmantojiet pogu TAB vai pogu BultiЕ†u uz leju. Lai pДЃrvietotos uz iepriekЕЎД“jo opciju izmantojiet  SHIFT+TAB vai pogu BultiЕ†a uz augЕЎu. Nospiediet SPACE vai ENTER lai izvelД“tos izvД“lnes opciju. Atveriet tekoЕЎajДЃ opcija apakЕЎizvД“lni ar SAPCE vai ENTER ka ari to var izdarД«t ar Labo bultiЕ†u. Lai atgrieztos atpakaДј uz sakuma izvД“lni nospiediet ESC vai Kreiso bultiЕ†u. Lai aizvД“rtu ciet izvД“lnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta laukДЃ, lai pДЃrvietotos uz nДЃkoЕЎo saraksta elementu nospiediet TAB vai pogu BultiЕ†a uz leju. Lai pДЃrvietotos uz iepriekЕЎД“jo saraksta elementu nospiediet SHIFT+TAB vai pogu BultiЕ†a uz augЕЎu. Nospiediet SPACE vai ENTER lai izvД“lД“tos saraksta opcijas. Nospiediet ESC lai aizvД“rtu saraksta lauku."},{name:"Redaktora elementa ceДјa josla",legend:"Nospiediet ${elementsPathFocus} lai pДЃrvietotos uz elementa ceДјa joslu. Lai pДЃrvietotos uz nДЃkoЕЎo elementa pogu izmantojiet TAB vai Labo bultiЕ†u. Lai pДЃrvietotos uz iepriekЕЎД“jo elementa pogu izmantojiet SHIFT+TAB vai Kreiso bultiЕ†u. Nospiediet SPACE vai ENTER lai izvД“lД“tos elementu redaktorДЃ."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darbД«bu",legend:"Nospiediet ${undo}"},{name:"Komanda atkДЃrtot darbД«bu",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"KursД«va komanda",legend:"Nospiediet ${italic}"},{name:"ApakЕЎsvД«tras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"RД«kjoslas aizvД“rЕЎanas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"PiekДјЕ«t iepriekЕЎД“jai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai piekДјЕ«tu tuvДЃkajai nepieejamajai fokusa vietai pirms kursora. PiemД“ram: diviem blakus esoЕЎiem lД«nijas HR elementiem. AtkДЃrtojiet taustiЕ†u kombinДЃciju lai piekДјЕ«tu pie tДЃlДЃkДЃm vietДЃm."},{name:"PiekДјЕ«t nДЃkoЕЎДЃ fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai piekДјЕ«tu tuvДЃkajai nepieejamajai fokusa vietai pД“c kursora. PiemД“ram: diviem blakus esoЕЎiem lД«nijas HR elementiem. AtkДЃrtojiet taustiЕ†u kombinДЃciju lai piekДјЕ«tu pie tДЃlДЃkДЃm vietДЃm."},
{name:"PieejamД«bas palД«dzД«ba",legend:"Nospiediet ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",
numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});