п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","nb",{title:"Instruksjoner for tilgjengelighet",contents:"Innhold for hjelp. Trykk ESC for ГҐ lukke denne dialogen.",legend:[{name:"Generelt",items:[{name:"VerktГёylinje for editor",legend:"Trykk ${toolbarFocus} for ГҐ navigere til verktГёylinjen. Flytt til neste og forrige verktГёylinjegruppe med TAB og SHIFT+TAB. Flytt til neste og forrige verktГёylinjeknapp med HГ�YRE PILTAST og VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for ГҐ aktivere verktГёylinjeknappen."},{name:"Dialog for editor",
legend:"Mens du er i en dialog, trykk TAB for ГҐ navigere til neste dialogelement, trykk SHIFT+TAB for ГҐ flytte til forrige dialogelement, trykk ENTER for ГҐ akseptere dialogen, trykk ESC for ГҐ avbryte dialogen. NГҐr en dialog har flere faner, kan fanelisten nГҐs med enten ALT+F10 eller med TAB. NГҐr fanelisten er fokusert, gГҐr man til neste og forrige fane med henholdsvis HГ�YRE og VENSTRE PILTAST."},{name:"Kontekstmeny for editor",legend:"Trykk ${contextMenu} eller MENYKNAPP for ГҐ ГҐpne kontekstmeny. GГҐ til neste alternativ i menyen med TAB eller PILTAST NED. GГҐ til forrige alternativ med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for ГҐ velge menyalternativet. Г…pne undermenyen pГҐ valgt alternativ med MELLOMROM eller ENTER eller HГ�YRE PILTAST. GГҐ tilbake til overordnet menyelement med ESC eller VENSTRE PILTAST. Lukk kontekstmenyen med ESC."},
{name:"Listeboks for editor",legend:"I en listeboks, gГҐ til neste alternativ i listen med TAB eller PILTAST NED. GГҐ til forrige alternativ i listen med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for ГҐ velge alternativet i listen. Trykk ESC for ГҐ lukke listeboksen."},{name:"VerktГёylinje for elementsti",legend:"Trykk ${elementsPathFocus} for ГҐ navigere til verktГёylinjen som viser elementsti. GГҐ til neste elementknapp med TAB eller HГ�YRE PILTAST. GГҐ til forrige elementknapp med SHIFT+TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for ГҐ velge elementet i editoren."}]},
{name:"Hurtigtaster",items:[{name:"Angre",legend:"Trykk ${undo}"},{name:"GjГёr om",legend:"Trykk ${redo}"},{name:"Fet tekst",legend:"Trykk ${bold}"},{name:"Kursiv tekst",legend:"Trykk ${italic}"},{name:"Understreking",legend:"Trykk ${underline}"},{name:"Lenke",legend:"Trykk ${link}"},{name:"Skjul verktГёylinje",legend:"Trykk ${toolbarCollapse}"},{name:"GГҐ til forrige fokusomrГҐde",legend:"Trykk ${accessPreviousSpace} for ГҐ komme til nГ¦rmeste fokusomrГҐde fГёr skrivemarkГёren som ikke kan nГҐs pГҐ vanlig mГҐte, for eksempel to tilstГёtende HR-elementer. Gjenta tastekombinasjonen for ГҐ komme til fokusomrГҐder lenger unna i dokumentet."},
{name:"GГҐ til neste fokusomrГҐde",legend:"Trykk ${accessNextSpace} for ГҐ komme til nГ¦rmeste fokusomrГҐde etter skrivemarkГёren som ikke kan nГҐs pГҐ vanlig mГҐte, for eksempel to tilstГёtende HR-elementer. Gjenta tastekombinasjonen for ГҐ komme til fokusomrГҐder lenger unna i dokumentet."},{name:"Hjelp for tilgjengelighet",legend:"Trykk ${a11yHelp}"}]}],tab:"Tabulator",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Venstre piltast",upArrow:"Opp-piltast",
rightArrow:"HГёyre piltast",downArrow:"Ned-piltast",insert:"Insert",leftWindowKey:"Venstre Windows-tast",rightWindowKey:"HГёyre Windows-tast",selectKey:"Velg nГёkkel",numpad0:"Numerisk tastatur 0",numpad1:"Numerisk tastatur 1",numpad2:"Numerisk tastatur 2",numpad3:"Numerisk tastatur 3",numpad4:"Numerisk tastatur 4",numpad5:"Numerisk tastatur 5",numpad6:"Numerisk tastatur 6",numpad7:"Numerisk tastatur 7",numpad8:"Numerisk tastatur 8",numpad9:"Numerisk tastatur 9",multiply:"Multipliser",add:"Legg til",
subtract:"Trekk fra",decimalPoint:"Desimaltegn",divide:"Divider",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Likhetstegn",comma:"Komma",dash:"Bindestrek",period:"Punktum",forwardSlash:"Forover skrГҐstrek",graveAccent:"Grav aksent",openBracket:"Г…pne parentes",backSlash:"Bakover skrГҐstrek",closeBracket:"Lukk parentes",singleQuote:"Enkelt sitattegn"});