п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","oc",{title:"Instruccions d'accessibilitat",contents:"Contengut de l'ajuda. Per tampar aquesta fenГЁstra, quichatz sus la tГІca Escap.",legend:[{name:"General",items:[{name:"Barra d'aisinas de l'editor",legend:"Quichar sus ${toolbarFocus} per accedir a la barra d'aisinas. Se desplaГ§ar cap al groupe seguent o precedent de la barra d'aisinas amb las tГІcas Tab e Maj+Tab. Se desplaГ§ar cap al boton seguent o precedent de la barra d'aisinas amb las tГІcas Sageta dreita e Sageta esquГЁrra. Quichar sus la barra d'espaci o la tГІca Entrada per activer lo boton de barra d'aisinas."},
{name:"FenГЁstra de l'editor",legend:"Dins una bГіstia de dialГІg, quichar sus Tab per passar a l'element seguent, quichar sus Maj+Tab per passar a l'element precedent, quichar sus Entrada per validar, quichar sus Escap per anullar. Quand una bГіstia de dialГІg possedГ­s des onglets, la lista pГІt ГЁsser atenta amb Alt+F10 o amb Tab. Dins la lista dels onglets, se desplaГ§ar cap al seguent e lo precedent amb las tГІcas Sageta dreita e Sageta esquГЁrra respectivament."},{name:"MenГє contextual de l'editor",legend:"Quichar sus ${contextMenu} o sus la tГІca MenГє per dobrir lo menГє contextual. Se desplaГ§ar ensuite cap a l'opcion seguenta del menГє amb las tГІcas Tab o Sageta bas. Se desplaГ§ar cap a l'opcion precedenta amb las tГІcas Maj+Tab o Sageta naut. Quichar sus la barra d'espaci o la tГІca Entrada per seleccionar l'opcion del menu. Quichar sus la barra d'espaci, la tГІca Entrada o Sageta dreita per dobrir lo sosmenГє de l'opcion seleccionada. Tornar a l'element de menГє parent amb la tГІca Escap o Sageta esquГЁrra. Tampar lo menГє contextual amb Escap."},
{name:"ZГІna de lista de l'editor",legend:"Dins una lista en menГє desenrotlant, se desplaГ§ar cap a l'element seguent de la lista amb las tГІcas Tab o Sageta bas. Se desplaГ§ar cap a l'element precedent de la lista amb las tГІcas Maj+Tab o Sageta naut. Quichar sus la barra d'espaci o sus Entrada per seleccionar l'opcion dins la lista. Quichar sus Escap per tampar lo menГє desenrotlant."},{name:"Barra del camin d'elements de l'editor",legend:"Quichar sus ${elementsPathFocus} per naviguer cap a la barra del fial d'Ariana dels elements. Se desplaГ§ar cap al boton de l'element seguent amb las tГІcas Tab o Sageta dreita. Se desplaГ§ar cap al boton precedent amb las tГІcas Maj+Tab o Sageta esquГЁrra. Quichar sus la barra d'espaci o sus Entrada per seleccionar l'element dins l'editor."}]},
{name:"Comandas",items:[{name:"Anullar la comanda",legend:"Quichar sus ${undo}"},{name:"Comanda restablir",legend:"Quichar sus ${redo}"},{name:" Comanda gras",legend:"Quichar sus ${bold}"},{name:" Comanda italica",legend:"Quichar sus ${italic}"},{name:" Comanda solinhat",legend:"Quichar sus ${underline}"},{name:" Comanda ligam",legend:"Quichar sus ${link}"},{name:"Comanda enrotlar la barra d'aisinas",legend:"Quichar sus ${toolbarCollapse}"},{name:"Comanda d'accГЁs a l'element seleccionable precedent",
legend:"Quichar sus ${accessNextSpace} per accedir a l'element seleccionable inategnible lo mai prГІche abans lo cursor, per exempleВ : doas linhas orizontalas adjacentas. Repetir la combinason de tГІcas per atГ©nher los elements seleccionables precedents."},{name:"Comanda d'accГЁs a l'element seleccionable seguent",legend:"Quichar sus ${accessNextSpace} per accedir a l'element seleccionable inatenhible lo mai prГІche aprГЁp lo cursor, per exempleВ : doas linhas orizontalas adjacentas. Repetir la combinason de tГІcas per atГ©nher los elements seleccionables seguents."},
{name:" Ajuda sus l'accessibilitat",legend:"Quichar sus ${a11yHelp}"}]}],tab:"Tabulacion",pause:"Pausa",capslock:"Verr. Maj.",escape:"Escap",pageUp:"Pagina superiora",pageDown:"Pagina seguenta",leftArrow:"Sageta esquГЁrra",upArrow:"Sageta naut",rightArrow:"Sageta dreita",downArrow:"Sageta bassa",insert:"Inser",leftWindowKey:"TГІca Windows esquГЁrra",rightWindowKey:"TГІca Windows dreita",selectKey:"TГІca Seleccionar",numpad0:"0 del pavat numeric",numpad1:"1 del pavat numeric",numpad2:"2 del pavat numeric",
numpad3:"3 del pavat numeric",numpad4:"4 del pavat numeric",numpad5:"5 del pavat numeric",numpad6:"6 del pavat numeric",numpad7:"7 del pavat numeric",numpad8:"Pavat numeric 8",numpad9:"9 del pavat numeric",multiply:"Multiplicar",add:"Plus",subtract:"Mens",decimalPoint:"Punt decimal",divide:"Devesir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Verr. Num.",scrollLock:"ArrГЁst desfil.",semiColon:"Punt-virgula",equalSign:"Signe egal",comma:"Virgula",
dash:"Jonhent",period:"Punt",forwardSlash:"Barra oblica",graveAccent:"Accent grГЁu",openBracket:"ParentГЁsi dobГЁrta",backSlash:"Barra oblica invГЁrsa",closeBracket:"ParentГЁsi tampanta",singleQuote:"ApostrГІfa"});