п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt-br",{title:"InstruГ§Гµes de Acessibilidade",contents:"ConteГєdo da Ajuda. Para fechar este diГЎlogo pressione ESC.",legend:[{name:"Geral",items:[{name:"Barra de Ferramentas do Editor",legend:"Pressione ${toolbarFocus} para navegar para a barra de ferramentas. Mova para o anterior ou prГіximo grupo de ferramentas com TAB e SHIFT+TAB. Mova para o anterior ou prГіximo botГЈo com SETA PARA DIREITA or SETA PARA ESQUERDA. Pressione ESPAГ‡O ou ENTER para ativar o botГЈo da barra de ferramentas."},
{name:"DiГЎlogo do Editor",legend:"Dentro de um diГЎlogo, pressione TAB para navegar para o prГіximo elemento. Pressione SHIFT+TAB para mover para o elemento anterior. Pressione ENTER ara enviar o diГЎlogo. pressione ESC para cancelar o diГЎlogo. Quando um diГЎlogo tem mГєltiplas abas, a lista de abas pode ser acessada com ALT+F10 ou TAB, como parte da ordem de tabulaГ§ГЈo do diГЎlogo. Com a lista de abas em foco, mova para a prГіxima aba e para a aba anterior com a SETA DIREITA ou SETA ESQUERDA, respectivamente."},
{name:"Menu de Contexto do Editor",legend:"Pressione ${contextMenu} ou TECLA DE MENU para abrir o menu de contexto, entГЈo mova para a prГіxima opГ§ГЈo com TAB ou SETA PARA BAIXO. Mova para a anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAГ‡O ou ENTER para selecionar a opГ§ГЈo do menu. Abra o submenu da opГ§ГЈo atual com ESPAГ‡O ou ENTER ou SETA PARA DIREITA. Volte para o menu pai com ESC ou SETA PARA ESQUERDA. Feche o menu de contexto com ESC."},{name:"Caixa de Lista do Editor",legend:"Dentro de uma caixa de lista, mova para o prГіximo item com TAB ou SETA PARA BAIXO. Mova para o item anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAГ‡O ou ENTER para selecionar uma opГ§ГЈo na lista. Pressione ESC para fechar a caixa de lista."},
{name:"Barra de Caminho do Elementos do Editor",legend:"Pressione ${elementsPathFocus} para a barra de caminho dos elementos. Mova para o prГіximo botГЈo de elemento com TAB ou SETA PARA DIREITA. Mova para o botГЈo anterior com SHIFT+TAB ou SETA PARA ESQUERDA. Pressione ESPAГ‡O ou ENTER para selecionar o elemento no editor."}]},{name:"Comandos",items:[{name:" Comando Desfazer",legend:"Pressione ${undo}"},{name:" Comando Refazer",legend:"Pressione ${redo}"},{name:" Comando Negrito",legend:"Pressione ${bold}"},
{name:" Comando ItГЎlico",legend:"Pressione ${italic}"},{name:" Comando Sublinhado",legend:"Pressione ${underline}"},{name:" Comando Link",legend:"Pressione ${link}"},{name:" Comando Fechar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acessar o comando anterior de spaГ§o de foco",legend:"Pressione ${accessNextSpace} para acessar o espaГ§o de foco nГЈo alcanГ§ГЎvel mais prГіximo antes do cursor, por exemplo: dois elementos HR adjacentes. Repita a combinaГ§ГЈo de teclas para alcanГ§ar espaГ§os de foco distantes."},
{name:"Acessar prГіximo fomando de spaГ§o de foco",legend:"Pressione ${accessNextSpace} para acessar o espaГ§o de foco nГЈo alcanГ§ГЎvel mais prГіximo apГіs o cursor, por exemplo: dois elementos HR adjacentes. Repita a combinaГ§ГЈo de teclas para alcanГ§ar espaГ§os de foco distantes."},{name:" Ajuda de Acessibilidade",legend:"Pressione ${a11yHelp}"}]}],tab:"Tecla Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Seta Г  Esquerda",upArrow:"Seta Г  Cima",rightArrow:"Seta Г  Direita",
downArrow:"Seta Г  Baixo",insert:"Insert",leftWindowKey:"Tecla do Windows Esquerda",rightWindowKey:"Tecla do Windows Direita",selectKey:"Tecla Selecionar",numpad0:"0 do Teclado NumГ©rico",numpad1:"1 do Teclado NumГ©rico",numpad2:"2 do Teclado NumГ©rico",numpad3:"3 do Teclado NumГ©rico",numpad4:"4 do Teclado NumГ©rico",numpad5:"5 do Teclado NumГ©rico",numpad6:"6 do Teclado NumГ©rico",numpad7:"7 do Teclado NumГ©rico",numpad8:"8 do Teclado NumГ©rico",numpad9:"9 do Teclado NumГ©rico",multiply:"Multiplicar",add:"Mais",
subtract:"Subtrair",decimalPoint:"Ponto",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Ponto-e-vГ­rgula",equalSign:"Igual",comma:"VГ­rgula",dash:"HГ­fen",period:"Ponto",forwardSlash:"Barra",graveAccent:"Acento Grave",openBracket:"Abrir Conchetes",backSlash:"Contra-barra",closeBracket:"Fechar Colchetes",singleQuote:"Aspas Simples"});