п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"InЕЎtrukcie prГ­stupnosti",contents:"PomocnГЅ obsah. Pre zatvorenie tohto okna, stlaДЌte ESC.",legend:[{name:"VЕЎeobecne",items:[{name:"LiЕЎta nГЎstrojov editora",legend:"StlaДЌte ${toolbarFocus} pre navigГЎciu na liЕЎtu nГЎstrojov. Medzi ДЏalЕЎou a predchГЎdzajГєcou liЕЎtou nГЎstrojov sa pohybujete s TAB a SHIFT+TAB. Medzi ДЏalЕЎГ­m a predchГЎdzajГєcim tlaДЌidlom na liЕЎte nГЎstrojov sa pohybujete s pravou ЕЎГ­pkou a Дѕavou ЕЎГ­pkou. StlaДЌte medzernГ­k alebo ENTER pre aktivГЎciu tlaДЌidla liЕЎty nГЎstrojov."},
{name:"EditorovГЅ dialГіg",legend:"V dialГіgovom okne stlaДЌte TAB pre presun na ДЏalЕЎГ­ prvok, SHIFT+TAB pre presun na predchГЎdzajГєci prvok, ENTER pre odoslanie, ESC pre zruЕЎenie. KeДЏ mГЎ dialГіgovГ© okno viacero kariet, zoznam kariet dosiahnete buДЏ stlaДЌenГ­m ALT+F10 alebo s TAB v prГ­sluЕЎnom poradГ­ kariet. So zameranГЅm zoznamom kariet sa pohybujte k ДЏalЕЎej alebo predchГЎdzajГєcej karte cez PRAVГљ a ДЅAVГљ Е ГЌPKU."},{name:"EditorovГ© kontextovГ© menu",legend:"StlaДЌte ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextovГ©ho menu. Potom sa presГєvajte na ДЏalЕЎie moЕѕnosti menu s TAB alebo dolnou ЕЎГ­pkou. Presunte sa k predchГЎdzajГєcej moЕѕnosti s SHIFT+TAB alebo hornou ЕЎГ­pkou. StlaДЌte medzernГ­k alebo ENTER pre vГЅber moЕѕnosti menu. Otvorte pod-menu danej moЕѕnosti s medzernГ­kom, alebo ENTER, alebo pravou ЕЎГ­pkou. VrГЎЕҐte sa spГ¤ЕҐ do poloЕѕky rodiДЌovskГ©ho menu s ESC alebo Дѕavou ЕЎГ­pkou. Zatvorte kontextovГ© menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presuЕ€te sa na ДЏalЕЎiu poloЕѕku v zozname s TAB alebo dolnou ЕЎГ­pkou. PresuЕ€te sa k predchГЎdzajГєcej poloЕѕke v zozname so SHIFT+TAB alebo hornou ЕЎГ­pkou. StlaДЌte medzernГ­k alebo ENTER pre vГЅber moЕѕnosti zoznamu. StlaДЌte ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pГЎsmo cesty prvku",legend:"StlaДЌte ${elementsPathFocus} pre navigovanie na pГЎsmo cesty elementu. PresuЕ€te sa na tlaДЌidlo ДЏalЕЎieho prvku s TAB alebo pravou ЕЎГ­pkou. PresuЕ€te sa k predchГЎdzajГєcemu tlaДЌidlu s SHIFT+TAB alebo Дѕavou ЕЎГ­pkou. StlaДЌte medzernГ­k alebo ENTER pre vГЅber prvku v editore."}]},
{name:"PrГ­kazy",items:[{name:"VrГЎtiЕҐ prГ­kazy",legend:"StlaДЌte ${undo}"},{name:"Nanovo vrГЎtiЕҐ prГ­kaz",legend:"StlaДЌte ${redo}"},{name:"PrГ­kaz na stuДЌnenie",legend:"StlaДЌte ${bold}"},{name:"PrГ­kaz na kurzГ­vu",legend:"StlaДЌte ${italic}"},{name:"PrГ­kaz na podДЌiarknutie",legend:"StlaДЌte ${underline}"},{name:"PrГ­kaz na odkaz",legend:"StlaДЌte ${link}"},{name:"PrГ­kaz na zbalenie liЕЎty nГЎstrojov",legend:"StlaДЌte ${toolbarCollapse}"},{name:"PrejsЕҐ na predchГЎdzajГєcu zamerateДѕnГє medzeru prГ­kazu",legend:"StlaДЌte ${accessPreviousSpace} pre prГ­stup na najbliЕѕЕЎie nedosiahnuteДѕnГ© zamerateДѕnГ© medzery pred vsuvkuo. NaprГ­klad: dve za sebou idГєce horizontГЎlne ДЌiary. Opakujte kombinГЎciu klГЎvesov pre dosiahnutie vzdialenГЅch zamerateДѕnГЅch medzier."},
{name:"PrejsЕҐ na ДЏalЕЎГ­ ",legend:"StlaДЌte ${accessNextSpace} pre prГ­stup na najbliЕѕЕЎie nedosiahnuteДѕnГ© zamerateДѕnГ© medzery po vsuvke. NaprГ­klad: dve za sebou idГєce horizontГЎlne ДЌiary. Opakujte kombinГЎciu klГЎvesov pre dosiahnutie vzdialenГЅch zamerateДѕnГЅch medzier."},{name:"Pomoc prГ­stupnosti",legend:"StlaДЌte ${a11yHelp}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"StrГЎnka hore",pageDown:"StrГЎnka dole",leftArrow:"Е Г­pka naДѕavo",upArrow:"Е Г­pka hore",rightArrow:"Е Г­pka napravo",
downArrow:"Е Г­pka dole",insert:"Insert",leftWindowKey:"ДЅavГ© Windows tlaДЌidlo",rightWindowKey:"PravГ© Windows tlaДЌidlo",selectKey:"TlaДЌidlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"NГЎsobenie",add:"SДЌГ­tanie",subtract:"OdДЌГ­tanie",decimalPoint:"DesatinnГЎ ДЌiarka",divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",
f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"BodkoДЌiarka",equalSign:"RovnГЎ sa",comma:"ДЊiarka",dash:"PomДєДЌka",period:"Bodka",forwardSlash:"LomГ­tko",graveAccent:"ZdГґrazЕ€ovanie prГ­zvuku",openBracket:"HranatГЎ zГЎtvorka otvГЎracia",backSlash:"Backslash",closeBracket:"HranatГЎ zГЎtvorka zatvГЎracia",singleQuote:"JednoduchГ© Гєvodzovky"});