п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"HjГ¤lpmedelsinstruktioner",contents:"HjГ¤lpinnehГҐll. FГ¶r att stГ¤nga denna dialogruta trycker du pГҐ ESC.",legend:[{name:"AllmГ¤nt",items:[{name:"Editor verktygsfГ¤lt",legend:"Tryck pГҐ ${toolbarFocus} fГ¶r att navigera till verktygsfГ¤ltet. Flytta till nГ¤sta och fГ¶regГҐende verktygsfГ¤ltsgrupp med TAB och SHIFT+TAB. Flytta till nГ¤sta och fГ¶regГҐende knapp i verktygsfГ¤ltet med HГ–GERPIL eller VГ„NSTERPIL. Tryck SPACE eller ENTER fГ¶r att aktivera knappen i verktygsfГ¤ltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB fГ¶r att navigera till nГ¤sta fГ¤lt i dialogrutan, tryck SKIFT+TAB fГ¶r att flytta till fГ¶regГҐende fГ¤lt, tryck ENTER fГ¶r att skicka. Du avbryter och stГ¤nger dialogen med ESC. FГ¶r dialogrutor som har flera flikar, tryck ALT+F10 eller TAB fГ¶r att navigera till fliklistan. med fliklistan vald flytta till nГ¤sta och fГ¶regГҐende flik med HГ–GER- eller VГ„NSTERPIL."},{name:"Editor fГ¶r innehГҐllsmeny",legend:"Tryck pГҐ $ {contextMenu} eller PROGRAMTANGENTEN fГ¶r att Г¶ppna snabbmenyn. Flytta sedan till nГ¤sta menyalternativ med TAB eller NEDPIL. Flytta till fГ¶regГҐende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER fГ¶r att vГ¤lja menyalternativ. Г–ppna undermeny av nuvarande alternativ med SPACE eller ENTER eller HГ–GERPIL. GГҐ tillbaka till Г¶verordnade menyalternativ med ESC eller VГ„NSTERPIL. StГ¤ng snabbmenyn med ESC."},
{name:"Editor fГ¶r list-box",legend:"Inuti en list-box, gГҐ till nГ¤sta listobjekt med TAB eller NEDPIL. Flytta till fГ¶regГҐende listobjekt med SHIFT+TAB eller UPPIL. Tryck SPACE eller ENTER fГ¶r att vГ¤lja listan alternativet. Tryck ESC fГ¶r att stГ¤nga list-boxen."},{name:"Editor fГ¶r elementens sГ¶kvГ¤g",legend:"Tryck pГҐ ${elementsPathFocus} fГ¶r att navigera till verktygsfГ¤ltet fГ¶r elementens sГ¶kvГ¤gar. Flytta till nГ¤sta elementknapp med TAB eller HГ–GERPIL. Flytta till fГ¶regГҐende knapp med SKIFT+TAB eller VГ„NSTERPIL. Tryck SPACE eller ENTER fГ¶r att vГ¤lja element i redigeraren."}]},
{name:"Kommandon",items:[{name:"Г…ngra kommando",legend:"Tryck pГҐ ${undo}"},{name:"GГ¶r om kommando",legend:"Tryck pГҐ ${redo}"},{name:"Kommandot fet stil",legend:"Tryck pГҐ ${bold}"},{name:"Kommandot kursiv",legend:"Tryck pГҐ ${italic}"},{name:"Kommandot understruken",legend:"Tryck pГҐ ${underline}"},{name:"Kommandot lГ¤nk",legend:"Tryck pГҐ ${link}"},{name:"VerktygsfГ¤lt DГ¶lj kommandot",legend:"Tryck pГҐ ${toolbarCollapse}"},{name:"GГҐ till fГ¶regГҐende fokus plats",legend:"Tryck pГҐ ${accessPreviousSpace} fГ¶r att gГҐ till nГ¤rmast onГҐbara utrymme fГ¶re markГ¶ren, exempel: tvГҐ intilliggande HR element. Repetera tangentkombinationen fГ¶r att gГҐ till nГ¤sta."},
{name:"TillgГҐ nГ¤sta fokuskommandots utrymme",legend:"Tryck ${accessNextSpace} pГҐ fГ¶r att komma ГҐt den nГ¤rmaste onГҐbar fokus utrymme efter cirkumflex, till exempel: tvГҐ intilliggande HR element. Upprepa tangentkombinationen fГ¶r att nГҐ avlГ¤gsna fokus utrymmen."},{name:"HjГ¤lp om tillgГ¤nglighet",legend:"Tryck ${a11yHelp}"}]}],tab:"Tab",pause:"Paus",capslock:"Caps lock",escape:"Escape",pageUp:"Sida Up",pageDown:"Sida Ned",leftArrow:"VГ¤nsterpil",upArrow:"Uppil",rightArrow:"HГ¶gerpil",downArrow:"NedГҐtpil",
insert:"Infoga",leftWindowKey:"VГ¤nster Windowstangent",rightWindowKey:"HГ¶ger Windowstangent",selectKey:"VГ¤lj tangent",numpad0:"Nummer 0",numpad1:"Nummer 1",numpad2:"Nummer 2",numpad3:"Nummer 3",numpad4:"Nummer 4",numpad5:"Nummer 5",numpad6:"Nummer 6",numpad7:"Nummer 7",numpad8:"Nummer 8",numpad9:"Nummer 9",multiply:"Multiplicera",add:"Addera",subtract:"Minus",decimalPoint:"Decimalpunkt",divide:"Dividera",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",
numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Lika med tecken",comma:"Komma",dash:"Minus",period:"Punkt",forwardSlash:"Snedstreck framГҐt",graveAccent:"Accent",openBracket:"Г–ppningsparentes",backSlash:"Snedstreck bakГҐt",closeBracket:"Slutparentes",singleQuote:"Enkelt Citattecken"});