п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"EriЕџilebilirlik TalimatlarД±",contents:"YardД±m iГ§eriДџi. Bu pencereyi kapatmak iГ§in ESC tuЕџuna basД±n.",legend:[{name:"Genel",items:[{name:"DГјzenleyici AraГ§ Г‡ubuДџu",legend:"AraГ§ Г§ubuДџunda gezinmek iГ§in ${toolbarFocus} basД±n. TAB ve SHIFT+TAB ile Г¶nceki ve sonraki araГ§ Г§ubuДџu grubuna taЕџД±yД±n. SAДћ OK veya SOL OK ile Г¶nceki ve sonraki bir araГ§ Г§ubuДџu dГјДџmesini hareket ettirin. SPACE tuЕџuna basД±n veya araГ§ Г§ubuДџu dГјДџmesini etkinleЕџtirmek iГ§in ENTER tuЕџna basД±n."},
{name:"Diyalog DГјzenleyici",legend:"Dialog penceresi iГ§inde, sonraki iletiЕџim alanД±na gitmek iГ§in SEKME tuЕџuna basД±n, Г¶nceki alana geГ§mek iГ§in SHIFT + TAB tuЕџuna basД±n, pencereyi gГ¶ndermek iГ§in ENTER tuЕџuna basД±n, dialog penceresini iptal etmek iГ§in ESC tuЕџuna basД±n. Birden Г§ok sekme sayfalarД± olan diyaloglarД±n, sekme listesine gitmek iГ§in ALT + F10 tuЕџlarД±na basД±n. Sonra TAB veya SAДћ OK sonraki sekmeye taЕџД±yД±n. SHIFT + TAB veya SOL OK ile Г¶nceki sekmeye geГ§in. Sekme sayfayД± seГ§mek iГ§in SPACE veya ENTER tuЕџuna basД±n."},
{name:"Д°Г§erik MenГј EditГ¶rГј",legend:"Д°Г§erik menГјsГјnГј aГ§mak iГ§in ${contextMenu} veya UYGULAMA TUЕћU'na basД±n. Daha sonra SEKME veya AЕћAДћI OK ile bir sonraki menГј seГ§eneДџi taЕџД±yД±n. SHIFT + TAB veya YUKARI OK ile Г¶nceki seГ§eneДџe gider. MenГј seГ§eneДџini seГ§mek iГ§in SPACE veya ENTER tuЕџuna basД±n. SeГ§ili seГ§eneДџin alt menГјsГјnГј SPACE ya da ENTER veya SAДћ OK aГ§Д±n. Гњst menГј Г¶Дџesini geГ§mek iГ§in ESC veya SOL OK ile geri dГ¶nГјn. ESC ile baДџlam menГјsГјnГј kapatД±n."},{name:"Liste Kutusu EditГ¶rГј",legend:"Liste kutusu iГ§inde, bir sonraki liste Г¶Дџesine SEKME VEYA AЕћAДћI OK ile taЕџД±yД±n. SHIFT+TAB veya YUKARI Г¶nceki liste Г¶Дџesi taЕџД±yД±n. Liste seГ§eneДџi seГ§mek iГ§in SPACE veya ENTER tuЕџuna basД±n. Liste kutusunu kapatmak iГ§in ESC tuЕџuna basД±n."},
{name:"Element Yol Г‡ubuДџu EditГ¶rГј",legend:"Elementlerin yol Г§ubuДџunda gezinmek iГ§in ${ElementsPathFocus} basД±n. SEKME veya SAДћ OK ile sonraki element dГјДџmesine taЕџД±yД±n. SHIFT+TAB veya SOL OK Г¶nceki dГјДџmeye hareket ettirin. EditГ¶r iГ§indeki elementi seГ§mek iГ§in ENTER veya SPACE tuЕџuna basД±n."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basД±n"},{name:"Komutu geri al",legend:"${redo} basД±n"},{name:" KalД±n komut",legend:"${bold} basД±n"},{name:" Д°talik komutu",legend:"${italic} basД±n"},
{name:" Alttan Г§izgi komutu",legend:"${underline} basД±n"},{name:" BaДџlantД± komutu",legend:"${link} basД±n"},{name:" AraГ§ Г§ubuДџu Toplama komutu",legend:"${toolbarCollapse} basД±n"},{name:"Г–nceki komut alanД±na odaklan",legend:"DГјzeltme imleГ§inden Г¶nce, en yakД±n uzaktaki alana eriЕџmek iГ§in ${accessPreviousSpace} basД±n, Г¶rneДџin: iki birleЕџik HR elementleri. AynД± tuЕџ kombinasyonu tekrarД±yla diДџer alanlarada ulaЕџД±n."},{name:"Sonraki komut alanД±na odaklan",legend:"DГјzeltme imleГ§inden sonra, en yakД±n uzaktaki alana eriЕџmek iГ§in ${accessNextSpace} basД±n, Г¶rneДџin: iki birleЕџik HR elementleri. AynД± tuЕџ kombinasyonu tekrarД±yla diДџer alanlarada ulaЕџД±n."},
{name:"EriЕџilebilirlik YardД±mД±",legend:"${a11yHelp}'e basД±n"}]}],tab:"Sekme tuЕџu",pause:"Durdurma tuЕџu",capslock:"BГјyГјk harf tuЕџu",escape:"VazgeГ§ tuЕџu",pageUp:"Sayfa YukarД±",pageDown:"Sayfa AЕџaДџД±",leftArrow:"Sol ok",upArrow:"YukarД± ok",rightArrow:"SaДџ ok",downArrow:"AЕџaДџД± ok",insert:"Araya gir",leftWindowKey:"Sol windows tuЕџu",rightWindowKey:"SaДџ windows tuЕџu",selectKey:"SeГ§me tuЕџu",numpad0:"NГјmerik 0",numpad1:"NГјmerik 1",numpad2:"NГјmerik 2",numpad3:"NГјmerik 3",numpad4:"NГјmerik 4",numpad5:"NГјmerik 5",
numpad6:"NГјmerik 6",numpad7:"NГјmerik 7",numpad8:"NГјmerik 8",numpad9:"NГјmerik 9",multiply:"Г‡arpma",add:"Toplama",subtract:"Г‡Д±karma",decimalPoint:"OndalД±k iЕџareti",divide:"BГ¶lme",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lk",scrollLock:"Scr Lk",semiColon:"NoktalД± virgГјl",equalSign:"EЕџittir",comma:"VirgГјl",dash:"Eksi",period:"Nokta",forwardSlash:"Д°leri eДџik Г§izgi",graveAccent:"Гњst tД±rnak",openBracket:"Parantez aГ§",backSlash:"Ters eДџik Г§izgi",
closeBracket:"Parantez kapa",singleQuote:"Tek tД±rnak"});