п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tt",{title:"Accessibility Instructions",contents:"Help Contents. To close this dialog press ESC.",legend:[{name:"Р“РѕРјСѓРјРё",items:[{name:"Editor Toolbar",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"Editor Dialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Editor Context Menu",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"РљРѕРјР°РЅРґР°Р»Р°СЂ",items:[{name:"РљР°Р№С‚Р°СЂСѓ",legend:"${undo} Р±Р°СЃС‹РіС‹Р·"},{name:"РљР°Р±Р°С‚Р»Р°Сѓ",legend:"${redo} Р±Р°СЃС‹РіС‹Р·"},{name:"РљР°Р»С‹РЅ",legend:"${bold} Р±Р°СЃС‹РіС‹Р·"},{name:"РљСѓСЂСЃРёРІ",legend:"${italic} Р±Р°СЃС‹РіС‹Р·"},{name:"РђСЃС‚С‹РЅР° СЃС‹Р·С‹Р»РіР°РЅ",legend:"${underline} Р±Р°СЃС‹РіС‹Р·"},
{name:"РЎС‹Р»С‚Р°Р»Р°РјР°",legend:"${link} Р±Р°СЃС‹РіС‹Р·"},{name:" Toolbar Collapse command",legend:"${toolbarCollapse} Р±Р°СЃС‹РіС‹Р·"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Accessibility Help",legend:"${a11yHelp} Р±Р°СЃС‹РіС‹Р·"}]}],tab:"Tab",pause:"РўС‹РЅС‹С€",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"РЎСѓР» СЏРєРєР° СѓРє",upArrow:"УЁСЃРєУ™ С‚Р°Р±Р° СѓРє",rightArrow:"РЈТЈ СЏРєРєР° СѓРє",downArrow:"РђСЃРєР° С‚Р°Р±Р° СѓРє",insert:"УЁСЃС‚У™ТЇ",leftWindowKey:"РЎСѓР» Windows С‚У©Р№РјЙ™СЃРµ",rightWindowKey:"РЈТЈ Windows С‚У©Р№РјЙ™СЃРµ",selectKey:"Select С‚У©Р№РјЙ™СЃРµ",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",
numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"РўР°РїРєС‹СЂР»Р°Сѓ",add:"РљСѓС€Сѓ",subtract:"РђР»Сѓ",decimalPoint:"РЈРЅР°СЂР»С‹ РЅРѕРєС‚Р°",divide:"Р‘ТЇР»ТЇ",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"РќРѕРєС‚Р°Р»С‹ У©С‚РµСЂ",equalSign:"РўРёРіРµР·Р»РµРє Р±РёР»РіРµСЃРµ",comma:"УЁС‚РµСЂ",dash:"РЎС‹Р·С‹Рє",period:"Р”У™СЂУ™Т—У™",forwardSlash:"РљС‹РµРє СЃС‹Р·С‹Рє",graveAccent:"Р“СЂР°РІРёСЃ",openBracket:"Т–У™СЏ Р°С‡Сѓ",backSlash:"РљРёСЂРµ РєС‹РµРє СЃС‹Р·С‹Рє",closeBracket:"Т–У™СЏ СЏР±Сѓ",
singleQuote:"Р‘РµСЂ РёТЈР»Рµ РєСѓС€С‚С‹СЂРЅР°РєР»Р°СЂ"});