п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","vi",{title:"HЖ°б»›ng dбє«n trб»Ј nДѓng",contents:"Nб»™i dung Hб»— trб»Ј. NhбєҐn ESC Д‘б»ѓ Д‘Гіng hб»™p thoбєЎi.",legend:[{name:"Chung",items:[{name:"Thanh cГґng cб»Ґ soбєЎn thбєЈo",legend:"NhбєҐn ${toolbarFocus} Д‘б»ѓ Д‘iб»Ѓu hЖ°б»›ng Д‘бєїn thanh cГґng cб»Ґ. NhбєҐn TAB vГ  SHIFT+TAB Д‘б»ѓ chuyб»ѓn Д‘бєїn nhГіm thanh cГґng cб»Ґ khГЎc. NhбєҐn MЕЁI TГЉN PHбєўI hoбє·c MЕЁI TГЉN TRГЃI Д‘б»ѓ chuyб»ѓn sang nГєt khГЎc trГЄn thanh cГґng cб»Ґ. NhбєҐn PHГЌM CГЃCH hoбє·c ENTER Д‘б»ѓ kГ­ch hoбєЎt nГєt trГЄn thanh cГґng cб»Ґ."},{name:"Hб»™p thoбєЎi BiГЄn t",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"TrГ¬nh Д‘ЖЎn Ngб»Ї cбєЈnh cBб»™ soбєЎn thбєЈo",legend:"NhбєҐn ${contextMenu} hoбє·c PHГЌM б»ЁNG Dб»¤NG Д‘б»ѓ mб»џ thб»±c Д‘ЖЎn ngб»Ї cбєЈnh. Sau Д‘Гі nhбєҐn TAB hoбє·c MЕЁI TГЉN XUб»ђNG Д‘б»ѓ di chuyб»ѓn Д‘бєїn tuб»і chб»Ќn tiбєїp theo cб»§a thб»±c Д‘ЖЎn. NhбєҐn SHIFT+TAB hoбє·c MЕЁI TГЉN LГЉN Д‘б»ѓ quay lбєЎi tuб»і chб»Ќn trЖ°б»›c. NhбєҐn Dбє¤U CГЃCH hoбє·c ENTER Д‘б»ѓ chб»Ќn tuб»і chб»Ќn cб»§a thб»±c Д‘ЖЎn. NhбєҐn Dбє¤U CГЃCH hoбє·c ENTER hoбє·c MЕЁI TГЉN SANG PHбєўI Д‘б»ѓ mб»џ thб»±c Д‘ЖЎn con cб»§a tuб»і chб»Ќn hiб»‡n tбєЎi. NhбєҐn ESC hoбє·c MЕЁI TГЉN SANG TRГЃI Д‘б»ѓ quay trб»џ lбєЎi thб»±c Д‘ЖЎn gб»‘c. NhбєҐn ESC Д‘б»ѓ Д‘Гіng thб»±c Д‘ЖЎn ngб»Ї cбєЈnh."},
{name:"Hб»™p danh sГЎch trГ¬nh biГЄn tбє­p",legend:"Trong mб»™t danh sГЎch chб»Ќn, di chuyб»ѓn Д‘б»‘i tЖ°б»Јng tiбєїp theo vб»›i phГ­m TAB hoбє·c phГ­m mЕ©i tГЄn hЖ°б»›ng xuб»‘ng. Di chuyб»ѓn Д‘бєїn Д‘б»‘i tЖ°б»Јng trЖ°б»›c Д‘Гі bбє±ng cГЎch nhбєҐn tб»• hб»Јp phГ­m SHIFT+TAB hoбє·c mЕ©i tГЄn hЖ°б»›ng lГЄn. PhГ­m khoбєЈng cГЎch hoбє·c phГ­m ENTER Д‘б»ѓ chб»Ќn cГЎc tГ№y chб»Ќn trong danh sГЎch. NhбєҐn phГ­m ESC Д‘б»ѓ Д‘Гіng lбєЎi danh sГЎch chб»Ќn."},{name:"Thanh Д‘Ж°б»ќng dбє«n cГЎc Д‘б»‘i tЖ°б»Јng",legend:"NhбєҐn ${elementsPathFocus} Д‘б»ѓ Д‘iб»Ѓu hЖ°б»›ng cГЎc Д‘б»‘i tЖ°б»Јng trong thanh Д‘Ж°б»ќng dбє«n. Di chuyб»ѓn Д‘бєїn Д‘б»‘i tЖ°б»Јng tiбєїp theo bбє±ng phГ­m TAB hoбє·c phГ­m mЕ©i tГЄn bГЄn phбєЈi. Di chuyб»ѓn Д‘бєїn Д‘б»‘i tЖ°б»Јng trЖ°б»›c Д‘Гі bбє±ng tб»• hб»Јp phГ­m SHIFT+TAB hoбє·c phГ­m mЕ©i tГЄn bГЄn trГЎi. NhбєҐn phГ­m khoбєЈng cГЎch hoбє·c ENTER Д‘б»ѓ chб»Ќn Д‘б»‘i tЖ°б»Јng trong trГ¬nh soбєЎn thбєЈo."}]},
{name:"Lб»‡nh",items:[{name:"LГ m lбєЎi lб»‡n",legend:"бє¤n ${undo}"},{name:"LГ m lбєЎi lб»‡nh",legend:"бє¤n ${redo}"},{name:"Lб»‡nh in Д‘бє­m",legend:"бє¤n ${bold}"},{name:"Lб»‡nh in nghiГЄng",legend:"бє¤n ${italic}"},{name:"Lб»‡nh gбєЎch dЖ°б»›i",legend:"бє¤n ${underline}"},{name:"Lб»‡nh liГЄn kбєїt",legend:"NhбєҐn ${link}"},{name:"Lб»‡nh hiб»ѓn thб»‹ thanh cГґng cб»Ґ",legend:"NhбєҐn${toolbarCollapse}"},{name:"Truy cбє­p Д‘бєїn lб»‡nh tбє­p trung vГ o khoбєЈng cГЎch trЖ°б»›c Д‘Гі",legend:"бє¤n ${accessPreviousSpace} Д‘б»ѓ truy cбє­p Д‘бєїn phбє§n tбє­p trung khoбєЈng cГЎch sau phбє§n cГІn sГіt lбєЎi cб»§a khoбєЈng cГЎch gбє§n nhбєҐt vб»‘n khГґng tГЎc Д‘б»™ng Д‘бєїn Д‘Ж°б»Јc , thГ­ dб»Ґ: hai yбєїu tб»‘ Д‘iб»Ѓu chб»‰nh HR. Lбє·p lбєЎi cГЎc phГ­m kбєїt hб»Ќep nГ y Д‘б»ѓ vЖ°ЖЎn Д‘бєїn phбє§n khoбєЈng cГЎch."},
{name:"Truy cбє­p phбє§n Д‘б»‘i tЖ°б»Јng lб»‡nh khoбєЈng trб»‘ng",legend:"бє¤n ${accessNextSpace} Д‘б»ѓ truy cбє­p Д‘бєїn phбє§n tбє­p trung khoбєЈng cГЎch sau phбє§n cГІn sГіt lбєЎi cб»§a khoбєЈng cГЎch gбє§n nhбєҐt vб»‘n khГґng tГЎc Д‘б»™ng Д‘бєїn Д‘Ж°б»Јc , thГ­ dб»Ґ: hai yбєїu tб»‘ Д‘iб»Ѓu chб»‰nh HR. Lбє·p lбєЎi cГЎc phГ­m kбєїt hб»Ќep nГ y Д‘б»ѓ vЖ°ЖЎn Д‘бєїn phбє§n khoбєЈng cГЎch."},{name:"Trб»Ј giГєp liГЄn quan",legend:"NhбєҐn ${a11yHelp}"}]}],tab:"PhГ­m Tab",pause:"PhГ­m Pause",capslock:"PhГ­m Caps Lock",escape:"PhГ­m Escape",pageUp:"PhГ­m Page Up",pageDown:"PhГ­m Page Down",leftArrow:"PhГ­m Left Arrow",
upArrow:"PhГ­m Up Arrow",rightArrow:"PhГ­m Right Arrow",downArrow:"PhГ­m Down Arrow",insert:"ChГЁn",leftWindowKey:"PhГ­m Left Windows",rightWindowKey:"PhГ­m Right Windows ",selectKey:"Chб»Ќn phГ­m",numpad0:"PhГ­m 0",numpad1:"PhГ­m 1",numpad2:"PhГ­m 2",numpad3:"PhГ­m 3",numpad4:"PhГ­m 4",numpad5:"PhГ­m 5",numpad6:"PhГ­m 6",numpad7:"PhГ­m 7",numpad8:"PhГ­m 8",numpad9:"PhГ­m 9",multiply:"NhГўn",add:"ThГЄm",subtract:"Trб»«",decimalPoint:"Дђiб»ѓm sб»‘ thбє­p phГўn",divide:"Chia",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",
f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"DбєҐu chбєҐm phбє©y",equalSign:"ДђДѓng nhбє­p bбє±ng",comma:"DбєҐu phбє©y",dash:"DбєҐu gбєЎch ngang",period:"PhГ­m .",forwardSlash:"PhГ­m /",graveAccent:"PhГ­m `",openBracket:"Open Bracket",backSlash:"DбєҐu gбєЎch chГ©o ngЖ°б»Јc",closeBracket:"Gбє§n giГЎ Д‘б»Ў",singleQuote:"TrГ­ch dбє«n"});