п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"PoДЌГЎteДЌnГ­ uvozovka jednoduchГЎ",rsquo:"KoncovГЎ uvozovka jednoduchГЎ",ldquo:"PoДЌГЎteДЌnГ­ uvozovka dvojitГЎ",rdquo:"KoncovГЎ uvozovka dvojitГЎ",ndash:"En pomlДЌka",mdash:"Em pomlДЌka",iexcl:"ObrГЎcenГЅ vykЕ™iДЌnГ­k",cent:"Znak centu",pound:"Znak libry",curren:"Znak mД›ny",yen:"Znak jenu",brvbar:"PЕ™eruЕЎenГЎ svislГЎ ДЌГЎra",sect:"Znak oddГ­lu",uml:"PЕ™ehlГЎska",copy:"Znak copyrightu",ordf:"ЕЅenskГЅ indikГЎtor rodu",laquo:"Znak dvojitГЅch lomenГЅch uvozovek vlevo",
not:"LogistickГЅ zГЎpor",reg:"Znak registrace",macr:"PomlДЌka nad",deg:"Znak stupnД›",sup2:"Dvojka jako hornГ­ index",sup3:"Trojka jako hornГ­ index",acute:"ДЊГЎrka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"TeДЌka uprostЕ™ed",cedil:"OcГЎsek vlevo",sup1:"JedniДЌka jako hornГ­ index",ordm:"MuЕѕskГЅ indikГЎtor rodu",raquo:"Znak dvojitГЅch lomenГЅch uvozovek vpravo",frac14:"ObyДЌejnГЅ zlomek jedna ДЌtvrtina",frac12:"ObyДЌejnГЅ zlomek jedna polovina",frac34:"ObyДЌejnГЅ zlomek tЕ™i ДЌtvrtiny",iquest:"Znak obrГЎcenГ©ho otaznГ­ku",
Agrave:"VelkГ© pГ­smeno latinky A s ДЌГЎrkou nad vlevo",Aacute:"VelkГ© pГ­smeno latinky A s ДЌГЎrkou nad vpravo",Acirc:"VelkГ© pГ­smeno latinky A s vokГЎnД›m",Atilde:"VelkГ© pГ­smeno latinky A s tildou",Auml:"VelkГ© pГ­smeno latinky A s dvД›ma teДЌkami",Aring:"VelkГ© pГ­smeno latinky A s krouЕѕkem nad",AElig:"VelkГ© pГ­smeno latinky Ae",Ccedil:"VelkГ© pГ­smeno latinky C s ocГЎskem vlevo",Egrave:"VelkГ© pГ­smeno latinky E s ДЌГЎrkou nad vlevo",Eacute:"VelkГ© pГ­smeno latinky E s ДЌГЎrkou nad vpravo",Ecirc:"VelkГ© pГ­smeno latinky E s vokГЎnД›m",
Euml:"VelkГ© pГ­smeno latinky E s dvД›ma teДЌkami",Igrave:"VelkГ© pГ­smeno latinky I s ДЌГЎrkou nad vlevo",Iacute:"VelkГ© pГ­smeno latinky I s ДЌГЎrkou nad vpravo",Icirc:"VelkГ© pГ­smeno latinky I s vokГЎnД›m",Iuml:"VelkГ© pГ­smeno latinky I s dvД›ma teДЌkami",ETH:"VelkГ© pГ­smeno latinky Eth",Ntilde:"VelkГ© pГ­smeno latinky N s tildou",Ograve:"VelkГ© pГ­smeno latinky O s ДЌГЎrkou nad vlevo",Oacute:"VelkГ© pГ­smeno latinky O s ДЌГЎrkou nad vpravo",Ocirc:"VelkГ© pГ­smeno latinky O s vokГЎnД›m",Otilde:"VelkГ© pГ­smeno latinky O s tildou",
Ouml:"VelkГ© pГ­smeno latinky O s dvД›ma teДЌkami",times:"Znak nГЎsobenГ­",Oslash:"VelkГ© pГ­smeno latinky O pЕ™eЕЎkrtnutГ©",Ugrave:"VelkГ© pГ­smeno latinky U s ДЌГЎrkou nad vlevo",Uacute:"VelkГ© pГ­smeno latinky U s ДЌГЎrkou nad vpravo",Ucirc:"VelkГ© pГ­smeno latinky U s vokГЎnД›m",Uuml:"VelkГ© pГ­smeno latinky U s dvД›ma teДЌkami",Yacute:"VelkГ© pГ­smeno latinky Y s ДЌГЎrkou nad vpravo",THORN:"VelkГ© pГ­smeno latinky Thorn",szlig:"MalГ© pГ­smeno latinky ostrГ© s",agrave:"MalГ© pГ­smeno latinky a s ДЌГЎrkou nad vlevo",aacute:"MalГ© pГ­smeno latinky a s ДЌГЎrkou nad vpravo",
acirc:"MalГ© pГ­smeno latinky a s vokГЎnД›m",atilde:"MalГ© pГ­smeno latinky a s tildou",auml:"MalГ© pГ­smeno latinky a s dvД›ma teДЌkami",aring:"MalГ© pГ­smeno latinky a s krouЕѕkem nad",aelig:"MalГ© pГ­smeno latinky ae",ccedil:"MalГ© pГ­smeno latinky c s ocГЎskem vlevo",egrave:"MalГ© pГ­smeno latinky e s ДЌГЎrkou nad vlevo",eacute:"MalГ© pГ­smeno latinky e s ДЌГЎrkou nad vpravo",ecirc:"MalГ© pГ­smeno latinky e s vokГЎnД›m",euml:"MalГ© pГ­smeno latinky e s dvД›ma teДЌkami",igrave:"MalГ© pГ­smeno latinky i s ДЌГЎrkou nad vlevo",iacute:"MalГ© pГ­smeno latinky i s ДЌГЎrkou nad vpravo",
icirc:"MalГ© pГ­smeno latinky i s vokГЎnД›m",iuml:"MalГ© pГ­smeno latinky i s dvД›ma teДЌkami",eth:"MalГ© pГ­smeno latinky eth",ntilde:"MalГ© pГ­smeno latinky n s tildou",ograve:"MalГ© pГ­smeno latinky o s ДЌГЎrkou nad vlevo",oacute:"MalГ© pГ­smeno latinky o s ДЌГЎrkou nad vpravo",ocirc:"MalГ© pГ­smeno latinky o s vokГЎnД›m",otilde:"MalГ© pГ­smeno latinky o s tildou",ouml:"MalГ© pГ­smeno latinky o s dvД›ma teДЌkami",divide:"Znak dД›lenГ­",oslash:"MalГ© pГ­smeno latinky o pЕ™eЕЎkrtnutГ©",ugrave:"MalГ© pГ­smeno latinky u s ДЌГЎrkou nad vlevo",
uacute:"MalГ© pГ­smeno latinky u s ДЌГЎrkou nad vpravo",ucirc:"MalГ© pГ­smeno latinky u s vokГЎnД›m",uuml:"MalГ© pГ­smeno latinky u s dvД›ma teДЌkami",yacute:"MalГ© pГ­smeno latinky y s ДЌГЎrkou nad vpravo",thorn:"MalГ© pГ­smeno latinky thorn",yuml:"MalГ© pГ­smeno latinky y s dvД›ma teДЌkami",OElig:"VelkГЎ ligatura latinky OE",oelig:"MalГЎ ligatura latinky OE",372:"VelkГ© pГ­smeno latinky W s vokГЎnД›m",374:"VelkГ© pГ­smeno latinky Y s vokГЎnД›m",373:"MalГ© pГ­smeno latinky w s vokГЎnД›m",375:"MalГ© pГ­smeno latinky y s vokГЎnД›m",sbquo:"DolnГ­ 9 uvozovka jednoduchГЎ",
8219:"HornГ­ obrГЎcenГЎ 9 uvozovka jednoduchГЎ",bdquo:"DolnГ­ 9 uvozovka dvojitГЎ",hellip:"TrojteДЌkovГЅ Гєvod",trade:"ObchodnГ­ znaДЌka",9658:"ДЊernГЅ ukazatel smД›Е™ujГ­cГ­ vpravo",bull:"KoleДЌko",rarr:"Е ipka vpravo",rArr:"DvojitГЎ ЕЎipka vpravo",hArr:"DvojitГЎ ЕЎipka vlevo a vpravo",diams:"ДЊernГ© piky",asymp:"TГ©mД›Е™ se rovnГЎ"});