п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","eo",{euro:"EЕ­rosigno",lsquo:"Supra 6-citilo",rsquo:"Supra 9-citilo",ldquo:"Supra 66-citilo",rdquo:"Supra 99-citilo",ndash:"Streketo",mdash:"Substreko",iexcl:"Renversita krisigno",cent:"Cendosigno",pound:"Pundosigno",curren:"Monersigno",yen:"Enosigno",brvbar:"Rompita vertikala streko",sect:"Kurba paragrafo",uml:"Tremao",copy:"Kopirajtosigno",ordf:"Adjektiva numerfinaДµo",laquo:"Duobla malplio-citilo",not:"Negohoko",reg:"Registrita marko",macr:"Superstreko",deg:"Gradosigno",
sup2:"Supra indico 2",sup3:"Supra indico 3",acute:"Dekstra korno",micro:"Mikrosigno",para:"Rekta paragrafo",middot:"Meza punkto",cedil:"Zoeto",sup1:"Supra indico 1",ordm:"Substantiva numerfinaДµo",raquo:"Duobla plio-citilo",frac14:"Kvaronosigno",frac12:"Duonosigno",frac34:"Trikvaronosigno",iquest:"renversita demandosigno",Agrave:"Latina Д‰eflitero A kun liva korno",Aacute:"Latina Д‰eflitero A kun dekstra korno",Acirc:"Latina Д‰eflitero A kun Д‰apelo",Atilde:"Latina Д‰eflitero A kun tildo",Auml:"Latina Д‰eflitero A kun tremao",
Aring:"Latina Д‰eflitero A kun superringo",AElig:"Latina Д‰eflitera ligaturo Г†",Ccedil:"Latina Д‰eflitero C kun zoeto",Egrave:"Latina Д‰eflitero E kun liva korno",Eacute:"Latina Д‰eflitero E kun dekstra korno",Ecirc:"Latina Д‰eflitero E kun Д‰apelo",Euml:"Latina Д‰eflitero E kun tremao",Igrave:"Latina Д‰eflitero I kun liva korno",Iacute:"Latina Д‰eflitero I kun dekstra korno",Icirc:"Latina Д‰eflitero I kun Д‰apelo",Iuml:"Latina Д‰eflitero I kun tremao",ETH:"Latina Д‰eflitero islanda edo",Ntilde:"Latina Д‰eflitero N kun tildo",
Ograve:"Latina Д‰eflitero O kun liva korno",Oacute:"Latina Д‰eflitero O kun dekstra korno",Ocirc:"Latina Д‰eflitero O kun Д‰apelo",Otilde:"Latina Д‰eflitero O kun tildo",Ouml:"Latina Д‰eflitero O kun tremao",times:"Multipliko",Oslash:"Latina Д‰eflitero O trastrekita",Ugrave:"Latina Д‰eflitero U kun liva korno",Uacute:"Latina Д‰eflitero U kun dekstra korno",Ucirc:"Latina Д‰eflitero U kun Д‰apelo",Uuml:"Latina Д‰eflitero U kun tremao",Yacute:"Latina Д‰eflitero Y kun dekstra korno",THORN:"Latina Д‰eflitero islanda dorno",
szlig:"Latina etlitero germana sozo (akra s)",agrave:"Latina etlitero a kun liva korno",aacute:"Latina etlitero a kun dekstra korno",acirc:"Latina etlitero a kun Д‰apelo",atilde:"Latina etlitero a kun tildo",auml:"Latina etlitero a kun tremao",aring:"Latina etlitero a kun superringo",aelig:"Latina etlitera ligaturo Г¦",ccedil:"Latina etlitero c kun zoeto",egrave:"Latina etlitero e kun liva korno",eacute:"Latina etlitero e kun dekstra korno",ecirc:"Latina etlitero e kun Д‰apelo",euml:"Latina etlitero e kun tremao",
igrave:"Latina etlitero i kun liva korno",iacute:"Latina etlitero i kun dekstra korno",icirc:"Latina etlitero i kun Д‰apelo",iuml:"Latina etlitero i kun tremao",eth:"Latina etlitero islanda edo",ntilde:"Latina etlitero n kun tildo",ograve:"Latina etlitero o kun liva korno",oacute:"Latina etlitero o kun dekstra korno",ocirc:"Latina etlitero o kun Д‰apelo",otilde:"Latina etlitero o kun tildo",ouml:"Latina etlitero o kun tremao",divide:"Dividosigno",oslash:"Latina etlitero o trastrekita",ugrave:"Latina etlitero u kun liva korno",
uacute:"Latina etlitero u kun dekstra korno",ucirc:"Latina etlitero u kun Д‰apelo",uuml:"Latina etlitero u kun tremao",yacute:"Latina etlitero y kun dekstra korno",thorn:"Latina etlitero islanda dorno",yuml:"Latina etlitero y kun tremao",OElig:"Latina Д‰eflitera ligaturo Е’",oelig:"Latina etlitera ligaturo Е“",372:"Latina Д‰eflitero W kun Д‰apelo",374:"Latina Д‰eflitero Y kun Д‰apelo",373:"Latina etlitero w kun Д‰apelo",375:"Latina etlitero y kun Д‰apelo",sbquo:"Suba 9-citilo",8219:"Supra renversita 9-citilo",
bdquo:"Suba 99-citilo",hellip:"Tripunkto",trade:"Varmarka signo",9658:"Nigra sago dekstren",bull:"Bulmarko",rarr:"Sago dekstren",rArr:"Duobla sago dekstren",hArr:"Duobla sago maldekstren",diams:"Nigra kvadrato",asymp:"PreskaЕ­ egala"});