п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"SГ­mbolo de euro",lsquo:"Comilla simple izquierda",rsquo:"Comilla simple derecha",ldquo:"Comilla doble izquierda",rdquo:"Comilla doble derecha",ndash:"GuiГіn corto",mdash:"GuiГіn medio largo",iexcl:"Signo de admiraciГіn invertido",cent:"SГ­mbolo centavo",pound:"SГ­mbolo libra",curren:"SГ­mbolo moneda",yen:"SГ­mbolo yen",brvbar:"Barra vertical rota",sect:"SГ­mbolo secciГіn",uml:"DiГ©resis",copy:"Signo de derechos de autor",ordf:"Indicador ordinal femenino",laquo:"Abre comillas angulares",
not:"Signo negaciГіn",reg:"Signo de marca registrada",macr:"GuiГіn alto",deg:"Signo de grado",sup2:"SuperГ­ndice dos",sup3:"SuperГ­ndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperГ­ndice uno",ordm:"Indicador orginal masculino",raquo:"Cierra comillas angulares",frac14:"FracciГіn ordinaria de un quarto",frac12:"FracciГіn ordinaria de una mitad",frac34:"FracciГіn ordinaria de tres cuartos",iquest:"Signo de interrogaciГіn invertido",Agrave:"Letra A latina mayГєscula con acento grave",
Aacute:"Letra A latina  mayГєscula con acento agudo",Acirc:"Letra A latina mayГєscula con acento circunflejo",Atilde:"Letra A latina mayГєscula con tilde",Auml:"Letra A latina mayГєscula con diГ©resis",Aring:"Letra A latina mayГєscula con aro arriba",AElig:"Letra Г† latina mayГєscula",Ccedil:"Letra C latina mayГєscula con cedilla",Egrave:"Letra E latina mayГєscula con acento grave",Eacute:"Letra E latina mayГєscula con acento agudo",Ecirc:"Letra E latina mayГєscula con acento circunflejo",Euml:"Letra E latina mayГєscula con diГ©resis",
Igrave:"Letra I latina mayГєscula con acento grave",Iacute:"Letra I latina mayГєscula con acento agudo",Icirc:"Letra I latina mayГєscula con acento circunflejo",Iuml:"Letra I latina mayГєscula con diГ©resis",ETH:"Letra Eth latina mayГєscula",Ntilde:"Letra N latina mayГєscula con tilde",Ograve:"Letra O latina mayГєscula con acento grave",Oacute:"Letra O latina mayГєscula con acento agudo",Ocirc:"Letra O latina mayГєscula con acento circunflejo",Otilde:"Letra O latina mayГєscula con tilde",Ouml:"Letra O latina mayГєscula con diГ©resis",
times:"Signo de multiplicaciГіn",Oslash:"Letra O latina mayГєscula con barra inclinada",Ugrave:"Letra U latina mayГєscula con acento grave",Uacute:"Letra U latina mayГєscula con acento agudo",Ucirc:"Letra U latina mayГєscula con acento circunflejo",Uuml:"Letra U latina mayГєscula con diГ©resis",Yacute:"Letra Y latina mayГєscula con acento agudo",THORN:"Letra Thorn latina mayГєscula",szlig:"Letra s latina fuerte pequeГ±a",agrave:"Letra a latina pequeГ±a con acento grave",aacute:"Letra a latina pequeГ±a con acento agudo",
acirc:"Letra a latina pequeГ±a con acento circunflejo",atilde:"Letra a latina pequeГ±a con tilde",auml:"Letra a latina pequeГ±a con diГ©resis",aring:"Letra a latina pequeГ±a con aro arriba",aelig:"Letra Г¦ latina pequeГ±a",ccedil:"Letra c latina pequeГ±a con cedilla",egrave:"Letra e latina pequeГ±a con acento grave",eacute:"Letra e latina pequeГ±a con acento agudo",ecirc:"Letra e latina pequeГ±a con acento circunflejo",euml:"Letra e latina pequeГ±a con diГ©resis",igrave:"Letra i latina pequeГ±a con acento grave",
iacute:"Letra i latina pequeГ±a con acento agudo",icirc:"Letra i latina pequeГ±a con acento circunflejo",iuml:"Letra i latina pequeГ±a con diГ©resis",eth:"Letra eth latina pequeГ±a",ntilde:"Letra n latina pequeГ±a con tilde",ograve:"Letra o latina pequeГ±a con acento grave",oacute:"Letra o latina pequeГ±a con acento agudo",ocirc:"Letra o latina pequeГ±a con acento circunflejo",otilde:"Letra o latina pequeГ±a con tilde",ouml:"Letra o latina pequeГ±a con diГ©resis",divide:"Signo de divisiГіn",oslash:"Letra o latina minГєscula con barra inclinada",
ugrave:"Letra u latina pequeГ±a con acento grave",uacute:"Letra u latina pequeГ±a con acento agudo",ucirc:"Letra u latina pequeГ±a con acento circunflejo",uuml:"Letra u latina pequeГ±a con diГ©resis",yacute:"Letra u latina pequeГ±a con acento agudo",thorn:"Letra thorn latina minГєscula",yuml:"Letra y latina pequeГ±a con diГ©resis",OElig:"Diptongo OE latino en mayГєscula",oelig:"Diptongo oe latino en minГєscula",372:"Letra W latina mayГєscula con acento circunflejo",374:"Letra Y latina mayГєscula con acento circunflejo",
373:"Letra w latina pequeГ±a con acento circunflejo",375:"Letra y latina pequeГ±a con acento circunflejo",sbquo:"Comilla simple baja-9",8219:"Comilla simple alta invertida-9",bdquo:"Comillas dobles bajas-9",hellip:"Puntos suspensivos horizontales",trade:"Signo de marca registrada",9658:"Apuntador negro apuntando a la derecha",bull:"ViГ±eta",rarr:"Flecha a la derecha",rArr:"Flecha doble a la derecha",hArr:"Flecha izquierda derecha doble",diams:"Diamante negro",asymp:"Casi igual a"});