п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","et",{euro:"EuromГ¤rk",lsquo:"Alustav Гјhekordne jutumГ¤rk",rsquo:"LГµpetav Гјhekordne jutumГ¤rk",ldquo:"Alustav kahekordne jutumГ¤rk",rdquo:"LГµpetav kahekordne jutumГ¤rk",ndash:"Enn-kriips",mdash:"Emm-kriips",iexcl:"PГ¶Г¶ratud hГјГјumГ¤rk",cent:"SendimГ¤rk",pound:"Naela mГ¤rk",curren:"ValuutamГ¤rk",yen:"Jeeni mГ¤rk",brvbar:"Katkestatud kriips",sect:"LГµigu mГ¤rk",uml:"TГ¤pid",copy:"AutoriГµiguse mГ¤rk",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Ei-mГ¤rk",reg:"Registered sign",macr:"Macron",deg:"KraadimГ¤rk",sup2:"Гњlaindeks kaks",sup3:"Гњlaindeks kolm",acute:"Acute accent",micro:"Mikro-mГ¤rk",para:"Pilcrow sign",middot:"Keskpunkt",cedil:"Cedilla",sup1:"Гњlaindeks Гјks",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Vulgar fraction one quarter",frac12:"Vulgar fraction one half",frac34:"Vulgar fraction three quarters",iquest:"Inverted question mark",Agrave:"Latin capital letter A with grave accent",
Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Ladina suur A tildega",Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"Latin Capital letter Г†",Ccedil:"Latin capital letter C with cedilla",Egrave:"Latin capital letter E with grave accent",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"Latin capital letter I with grave accent",
Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",ETH:"Latin capital letter Eth",Ntilde:"Latin capital letter N with tilde",Ograve:"Latin capital letter O with grave accent",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"TГ¤ppidega ladina suur O",times:"Multiplication sign",Oslash:"Latin capital letter O with stroke",
Ugrave:"Latin capital letter U with grave accent",Uacute:"Latin capital letter U with acute accent",Ucirc:"Kandilise katusega suur ladina U",Uuml:"TГ¤ppidega ladina suur U",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Ladina vГ¤ike terav s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Kandilise katusega ladina vГ¤ike a",atilde:"Tildega ladina vГ¤ike a",auml:"TГ¤ppidega ladina vГ¤ike a",aring:"Latin small letter a with ring above",
aelig:"Latin small letter Г¦",ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"Latin small letter eth",ntilde:"Latin small letter n with tilde",
ograve:"Latin small letter o with grave accent",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"JagamismГ¤rk",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",
thorn:"Latin small letter thorn",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"KaubamГ¤rgi mГ¤rk",9658:"Black right-pointing pointer",
bull:"Kuul",rarr:"Nool paremale",rArr:"Topeltnool paremale",hArr:"Topeltnool vasakule",diams:"Black diamond suit",asymp:"Ligikaudu vГµrdne"});