п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr-ca",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret",iexcl:"Point d'exclamation inversГ©",cent:"Symbole de cent",pound:"Symbole de Livre Sterling",curren:"Symbole monГ©taire",yen:"Symbole du Yen",brvbar:"Barre scindГ©e",sect:"Symbole de section",uml:"TrГ©ma",copy:"Symbole de copyright",ordf:"Indicateur ordinal fГ©minin",laquo:"Guillemet franГ§ais ouvrant",
not:"Indicateur de nГ©gation",reg:"Symbole de marque dГ©posГ©e",macr:"Macron",deg:"DegrГ©",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigГјe",micro:"Symbole micro",para:"Paragraphe",middot:"Point mГ©dian",cedil:"CГ©dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franГ§ais fermant",frac14:"Un quart",frac12:"Une demi",frac34:"Trois quart",iquest:"Point d'interrogation inversГ©",Agrave:"A accent grave",Aacute:"A accent aigГјe",Acirc:"A circonflexe",Atilde:"A tilde",Auml:"A trГ©ma",
Aring:"A avec un rond au dessus",AElig:"Г† majuscule",Ccedil:"C cГ©dille",Egrave:"E accent grave",Eacute:"E accent aigГјe",Ecirc:"E accent circonflexe",Euml:"E trГ©ma",Igrave:"I accent grave",Iacute:"I accent aigГјe",Icirc:"I accent circonflexe",Iuml:"I trГ©ma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N tilde",Ograve:"O accent grave",Oacute:"O accent aigГјe",Ocirc:"O accent circonflexe",Otilde:"O tilde",Ouml:"O trГ©ma",times:"Symbole de multiplication",Oslash:"O barrГ©",Ugrave:"U accent grave",Uacute:"U accent aigГјe",
Ucirc:"U accent circonflexe",Uuml:"U trГ©ma",Yacute:"Y accent aigГјe",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a accent grave",aacute:"a accent aigГјe",acirc:"a accent circonflexe",atilde:"a tilde",auml:"a trГ©ma",aring:"a avec un cercle au dessus",aelig:"Г¦",ccedil:"c cГ©dille",egrave:"e accent grave",eacute:"e accent aigГјe",ecirc:"e accent circonflexe",euml:"e trГ©ma",igrave:"i accent grave",iacute:"i accent aigГјe",icirc:"i accent circonflexe",iuml:"i trГ©ma",
eth:"Lettre minuscule islandaise ED",ntilde:"n tilde",ograve:"o accent grave",oacute:"o accent aigГјe",ocirc:"O accent circonflexe",otilde:"O tilde",ouml:"O trГ©ma",divide:"Symbole de division",oslash:"o barrГ©",ugrave:"u accent grave",uacute:"u accent aigГјe",ucirc:"u accent circonflexe",uuml:"u trГ©ma",yacute:"y accent aigГјe",thorn:"Lettre islandaise thorn minuscule",yuml:"y trГ©ma",OElig:"ligature majuscule latine Е’",oelig:"ligature minuscule latine Е“",372:"W accent circonflexe",374:"Y accent circonflexe",
373:"w accent circonflexe",375:"y accent circonflexe",sbquo:"Guillemet simple fermant",8219:"Guillemet-virgule supГ©rieur culbutГ©",bdquo:"Guillemet-virgule double infГ©rieur",hellip:"Points de suspension",trade:"Symbole de marque dГ©posГ©e",9658:"FlГЁche noire pointant vers la droite",bull:"Puce",rarr:"FlГЁche vers la droite",rArr:"FlГЁche double vers la droite",hArr:"FlГЁche double vers la gauche",diams:"Carreau",asymp:"Presque Г©gal"});