п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Symbole euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret demi-cadratin",mdash:"Tiret cadratin",iexcl:"Point d'exclamation inversГ©",cent:"Symbole cent",pound:"Symbole Livre sterling",curren:"Symbole monГ©taire",yen:"Symbole yen",brvbar:"Barre verticale scindГ©e",sect:"Signe de section",uml:"TrГ©ma",copy:"Symbole Copyright",ordf:"Indicateur ordinal fГ©minin",
laquo:"Guillemet franГ§ais ouvrant",not:"Crochet de nГ©gation",reg:"Symbole de marque dГ©posГ©e",macr:"Macron",deg:"Symbole degrГ©",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigu",micro:"Symbole micro",para:"Symbole pied-de-mouche",middot:"Point mГ©dian",cedil:"CГ©dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franГ§ais fermant",frac14:"Fraction un quart",frac12:"Fraction un demi",frac34:"Fraction trois quarts",iquest:"Point d'interrogation inversГ©",Agrave:"A accent grave majuscule",
Aacute:"A accent aigu majuscule",Acirc:"A accent circonflexe majuscule",Atilde:"A caron majuscule",Auml:"A trГ©ma majuscule",Aring:"A rond majuscule",AElig:"Ligature Г† majuscule",Ccedil:"C cГ©dille majuscule",Egrave:"E accent grave majuscule",Eacute:"E accent aigu majuscule",Ecirc:"E accent circonflexe majuscule",Euml:"E trГ©ma majuscule",Igrave:"I accent grave majuscule",Iacute:"I accent aigu majuscule",Icirc:"I accent circonflexe majuscule",Iuml:"I trГ©ma majuscule",ETH:"Lettre majuscule islandaise ED",
Ntilde:"N caron majuscule",Ograve:"O accent grave majuscule",Oacute:"O accent aigu majuscule",Ocirc:"O accent circonflexe majuscule",Otilde:"O caron majuscule",Ouml:"O trГ©ma majuscule",times:"Symbole de multiplication",Oslash:"O barrГ© majuscule",Ugrave:"U accent grave majuscule",Uacute:"U accent aigu majuscule",Ucirc:"U accent circonflexe majuscule",Uuml:"U trГ©ma majuscule",Yacute:"Y accent aigu majuscule",THORN:"Lettre islandaise thorn majuscule",szlig:"Lettre minuscule allemande S dur",agrave:"A accent grave minuscule",
aacute:"A accent aigu minuscule",acirc:"A accent circonflexe minuscule",atilde:"A tilde minuscule",auml:"A trГ©ma minuscule",aring:"A rond minuscule",aelig:"Ligature Г† minuscule",ccedil:"C cГ©dille minuscule",egrave:"E accent grave minuscule",eacute:"E accent aigu minuscule",ecirc:"E accent circonflexe minuscule",euml:"E trГ©ma minuscule",igrave:"I accent grave minuscule",iacute:"I accent aigu minuscule",icirc:"I accent circonflexe minuscule",iuml:"i minuscule trГ©ma",eth:"Lettre minuscule islandaise ED",
ntilde:"N caron minuscule",ograve:"O minuscule accent grave",oacute:"O accent aigu minuscule",ocirc:"O accent circonflexe minuscule",otilde:"O tilde minuscule",ouml:"O trГ©ma minuscule",divide:"Symbole de division",oslash:"O barrГ© minuscule",ugrave:"U accent grave minuscule",uacute:"U accent aigu minuscule",ucirc:"U accent circonflexe minuscule",uuml:"U trГ©ma minuscule",yacute:"Y accent aigu minuscule",thorn:"Lettre islandaise thorn minuscule",yuml:"Y trГ©ma minuscule",OElig:"Ligature Е’ majuscule",
oelig:"Ligature Е’ minuscule",372:"W accent circonflexe majuscule",374:"Y accent circonflexe majuscule",373:"W accent circonflexe minuscule",375:"Y accent circonflexe minuscule",sbquo:"Guillemet simple fermant infГ©rieur",8219:"Guillemet-virgule supГ©rieur culbutГ©",bdquo:"Guillemet-virgule double infГ©rieur",hellip:"Points de suspension",trade:"Symbole de marque commerciale",9658:"FlГЁche noire pointant vers la droite",bull:"Gros point mГ©dian",rarr:"FlГЁche vers la droite",rArr:"Double flГЁche vers la droite",
hArr:"Double flГЁche vers la gauche",diams:"Losange noir",asymp:"Environ Г©gal"});