п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","gl",{euro:"SГ­mbolo do euro",lsquo:"ComiГ±a simple esquerda",rsquo:"ComiГ±a simple dereita",ldquo:"ComiГ±as dobres esquerda",rdquo:"ComiГ±as dobres dereita",ndash:"GuiГіn",mdash:"Raia",iexcl:"Signo de admiraciГіn invertido",cent:"SГ­mbolo do centavo",pound:"SГ­mbolo da libra",curren:"SГ­mbolo de moeda",yen:"SГ­mbolo do yen",brvbar:"Barra vertical rota",sect:"SГ­mbolo de secciГіn",uml:"DiГ©rese",copy:"SГ­mbolo de dereitos de autorГ­a",ordf:"Indicador ordinal feminino",laquo:"ComiГ±as latinas, apertura",
not:"Signo negaciГіn",reg:"SГ­mbolo de marca rexistrada",macr:"GuiГіn alto",deg:"Signo de grao",sup2:"SuperГ­ndice dous",sup3:"SuperГ­ndice tres",acute:"Acento agudo",micro:"Signo de micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperГ­ndice un",ordm:"Indicador ordinal masculino",raquo:"ComiГ±as latinas, peche",frac14:"FracciГіn ordinaria de un cuarto",frac12:"FracciГіn ordinaria de un medio",frac34:"FracciГіn ordinaria de tres cuartos",iquest:"Signo de interrogaciГіn invertido",Agrave:"Letra A latina maiГєscula con acento grave",
Aacute:"Letra A latina maiГєscula con acento agudo",Acirc:"Letra A latina maiГєscula con acento circunflexo",Atilde:"Letra A latina maiГєscula con til",Auml:"Letra A latina maiГєscula con diГ©rese",Aring:"Letra A latina maiГєscula con aro enriba",AElig:"Letra Г† latina maiГєscula",Ccedil:"Letra C latina maiГєscula con cedilla",Egrave:"Letra E latina maiГєscula con acento grave",Eacute:"Letra E latina maiГєscula con acento agudo",Ecirc:"Letra E latina maiГєscula con acento circunflexo",Euml:"Letra E latina maiГєscula con diГ©rese",
Igrave:"Letra I latina maiГєscula con acento grave",Iacute:"Letra I latina maiГєscula con acento agudo",Icirc:"Letra I latina maiГєscula con acento circunflexo",Iuml:"Letra I latina maiГєscula con diГ©rese",ETH:"Letra Ed latina maiГєscula",Ntilde:"Letra N latina maiГєscula con til",Ograve:"Letra O latina maiГєscula con acento grave",Oacute:"Letra O latina maiГєscula con acento agudo",Ocirc:"Letra O latina maiГєscula con acento circunflexo",Otilde:"Letra O latina maiГєscula con til",Ouml:"Letra O latina maiГєscula con diГ©rese",
times:"Signo de multiplicaciГіn",Oslash:"Letra O latina maiГєscula con barra transversal",Ugrave:"Letra U latina maiГєscula con acento grave",Uacute:"Letra U latina maiГєscula con acento agudo",Ucirc:"Letra U latina maiГєscula con acento circunflexo",Uuml:"Letra U latina maiГєscula con diГ©rese",Yacute:"Letra Y latina maiГєscula con acento agudo",THORN:"Letra Thorn latina maiГєscula",szlig:"Letra s latina forte minГєscula",agrave:"Letra a latina minГєscula con acento grave",aacute:"Letra a latina minГєscula con acento agudo",
acirc:"Letra a latina minГєscula con acento circunflexo",atilde:"Letra a latina minГєscula con til",auml:"Letra a latina minГєscula con diГ©rese",aring:"Letra a latina minГєscula con aro enriba",aelig:"Letra Г¦ latina minГєscula",ccedil:"Letra c latina minГєscula con cedilla",egrave:"Letra e latina minГєscula con acento grave",eacute:"Letra e latina minГєscula con acento agudo",ecirc:"Letra e latina minГєscula con acento circunflexo",euml:"Letra e latina minГєscula con diГ©rese",igrave:"Letra i latina minГєscula con acento grave",
iacute:"Letra i latina minГєscula con acento agudo",icirc:"Letra i latina minГєscula con acento circunflexo",iuml:"Letra i latina minГєscula con diГ©rese",eth:"Letra ed latina minГєscula",ntilde:"Letra n latina minГєscula con til",ograve:"Letra o latina minГєscula con acento grave",oacute:"Letra o latina minГєscula con acento agudo",ocirc:"Letra o latina minГєscula con acento circunflexo",otilde:"Letra o latina minГєscula con til",ouml:"Letra o latina minГєscula con diГ©rese",divide:"Signo de divisiГіn",oslash:"Letra o latina minГєscula con barra transversal",
ugrave:"Letra u latina minГєscula con acento grave",uacute:"Letra u latina minГєscula con acento agudo",ucirc:"Letra u latina minГєscula con acento circunflexo",uuml:"Letra u latina minГєscula con diГ©rese",yacute:"Letra y latina minГєscula con acento agudo",thorn:"Letra Thorn latina minГєscula",yuml:"Letra y latina minГєscula con diГ©rese",OElig:"Ligadura OE latina maiГєscula",oelig:"Ligadura oe latina minГєscula",372:"Letra W latina maiГєscula con acento circunflexo",374:"Letra Y latina maiГєscula con acento circunflexo",
373:"Letra w latina minГєscula con acento circunflexo",375:"Letra y latina minГєscula con acento circunflexo",sbquo:"ComiГ±a simple baixa, de apertura",8219:"ComiГ±a simple alta, de peche",bdquo:"ComiГ±as dobres baixas, de apertura",hellip:"Elipse, puntos suspensivos",trade:"Signo de marca rexistrada",9658:"Apuntador negro apuntando ГЎ dereita",bull:"ViГ±eta",rarr:"Frecha ГЎ dereita",rArr:"Frecha dobre ГЎ dereita",hArr:"Frecha dobre da esquerda ГЎ dereita",diams:"Diamante negro",asymp:"Case igual a"});