п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","he",{euro:"Ч™Ч•ЧЁЧ•",lsquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч™Ч—Ч™Ч“ Ч©ЧћЧђЧњЧ™",rsquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч™Ч—Ч™Ч“ Ч™ЧћЧ Ч™",ldquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч›Ч¤Ч•Чњ Ч©ЧћЧђЧњЧ™",rdquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч›Ч¤Ч•Чњ Ч™ЧћЧ Ч™",ndash:"Ч§Ч• ЧћЧ¤ЧЁЧ™Ч“ Ч§Ч¦ЧЁ",mdash:"Ч§Ч• ЧћЧ¤ЧЁЧ™Ч“ ЧђЧЁЧ•Чљ",iexcl:"ЧЎЧ™ЧћЧџ Ч§ЧЁЧ™ЧђЧ” Ч”Ч¤Ч•Чљ",cent:"ЧЎЧ Ч�",pound:"Ч¤ЧђЧ•Ч Ч“",curren:"ЧћЧ�Ч‘Чў",yen:"Ч™Чџ",brvbar:"Ч§Ч• Ч©Ч‘Ч•ЧЁ",sect:"ЧЎЧ™ЧћЧџ ЧћЧ§Ч�Чў",uml:"Ч©ЧЄЧ™ Ч Ч§Ч•Ч“Ч•ЧЄ ЧђЧ•Ч¤Ч§Ч™Ч•ЧЄ (Diaeresis)",copy:"ЧЎЧ™ЧћЧџ Ч–Ч›Ч•Ч™Ч•ЧЄ Ч™Ч•Ч¦ЧЁЧ™Чќ (Copyright)",ordf:"ЧЎЧ™ЧћЧџ ЧђЧ•ЧЁЧ“Ч™Ч ЧђЧњЧ™ Ч Ч§Ч‘Ч™",laquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч–Ч•Ч•Ч™ЧЄ Ч›Ч¤Ч•ЧњЧ” ЧњЧ©ЧћЧђЧњ",not:"ЧЎЧ™ЧћЧџ Ч©ЧњЧ™ЧњЧ” ЧћЧЄЧћЧ�Ч™",reg:"ЧЎЧ™ЧћЧџ ЧЁЧ©Ч•Чќ",
macr:"ЧћЧ§ЧЁЧ•Чџ (Ч”Ч’Ч™Ч” ЧђЧЁЧ•Ч›Ч”)",deg:"ЧћЧўЧњЧ•ЧЄ",sup2:"2 Ч‘Ч›ЧЄЧ™Ч‘ ЧўЧ™ЧњЧ™",sup3:"3 Ч‘Ч›ЧЄЧ™Ч‘ ЧўЧ™ЧњЧ™",acute:"ЧЎЧ™ЧћЧџ Ч“Ч’Ч•Ч© (Acute)",micro:"ЧћЧ™Ч§ЧЁЧ•",para:"ЧЎЧ™ЧћЧ•Чџ Ч¤ЧЎЧ§Ч”",middot:"Ч Ч§Ч•Ч“Ч” ЧђЧћЧ¦ЧўЧ™ЧЄ",cedil:"ЧЎЧ“Ч™ЧњЧ™Ч”",sup1:"1 Ч‘Ч›ЧЄЧ™Ч‘ ЧўЧ™ЧњЧ™",ordm:"ЧЎЧ™ЧћЧџ ЧђЧ•ЧЁЧ“Ч™Ч ЧђЧњЧ™ Ч–Ч›ЧЁЧ™",raquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч–Ч•Ч•Ч™ЧЄ Ч›Ч¤Ч•ЧњЧ” ЧњЧ™ЧћЧ™Чџ",frac14:"ЧЁЧ‘Чў Ч‘Ч©Ч‘ЧЁ Ч¤Ч©Ч•Ч�",frac12:"Ч—Ч¦Ч™ Ч‘Ч©Ч‘ЧЁ Ч¤Ч©Ч•Ч�",frac34:"Ч©ЧњЧ•Ч©Ч” ЧЁЧ‘ЧўЧ™Чќ Ч‘Ч©Ч‘ЧЁ Ч¤Ч©Ч•Ч�",iquest:"ЧЎЧ™ЧћЧџ Ч©ЧђЧњЧ” Ч”Ч¤Ч•Чљ",Agrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ A ЧўЧќ Ч’ЧЁЧ© (Grave)",Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",
Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ Г† Ч’Ч“Ч•ЧњЧ”",Ccedil:"Latin capital letter C with cedilla",Egrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ E ЧўЧќ Ч’ЧЁЧ© (Grave)",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ I ЧўЧќ Ч’ЧЁЧ© (Grave)",Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",
ETH:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ Eth Ч’Ч“Ч•ЧњЧ”",Ntilde:"Latin capital letter N with tilde",Ograve:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ O ЧўЧќ Ч’ЧЁЧ© (Grave)",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"ЧЎЧ™ЧћЧџ Ч›Ч¤Чњ",Oslash:"Latin capital letter O with stroke",Ugrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ U ЧўЧќ Ч’ЧЁЧ© (Grave)",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",
Yacute:"Latin capital letter Y with acute accent",THORN:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ Thorn Ч’Ч“Ч•ЧњЧ”",szlig:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ s Ч—Ч“Ч” Ч§Ч�Ч Ч”",agrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ a ЧўЧќ Ч’ЧЁЧ© (Grave)",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ Г¦ Ч§Ч�Ч Ч”",ccedil:"Latin small letter c with cedilla",egrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ e ЧўЧќ Ч’ЧЁЧ© (Grave)",eacute:"Latin small letter e with acute accent",
ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ i ЧўЧќ Ч’ЧЁЧ© (Grave)",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ eth Ч§Ч�Ч Ч”",ntilde:"Latin small letter n with tilde",ograve:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ o ЧўЧќ Ч’ЧЁЧ© (Grave)",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",
divide:"ЧЎЧ™ЧћЧџ Ч—ЧњЧ•Ч§Ч”",oslash:"Latin small letter o with stroke",ugrave:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ u ЧўЧќ Ч’ЧЁЧ© (Grave)",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"ЧђЧ•ЧЄ ЧњЧ�Ч™Ч Ч™ЧЄ thorn Ч§Ч�Ч Ч”",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",
373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч ЧћЧ•Чљ Ч™Ч—Ч™Ч“",8219:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч�",bdquo:"ЧЎЧ™ЧћЧџ Ч¦Ч™Ч�Ч•Ч� Ч ЧћЧ•Чљ Ч›Ч¤Ч•Чњ",hellip:"Ч©ЧњЧ•Ч© Ч Ч§Ч•Ч“Ч•ЧЄ",trade:"ЧЎЧ™ЧћЧџ Ч�ЧЁЧ™Ч™Ч“ЧћЧђЧЁЧ§",9658:"ЧЎЧћЧџ Ч©Ч—Ч•ЧЁ ЧњЧ¦Ч“ Ч™ЧћЧ™Чџ",bull:"ЧЄЧ‘ЧњЧ™Ч� (ЧЁЧ©Ч™ЧћЧ”)",rarr:"Ч—ЧҐ ЧњЧ™ЧћЧ™Чџ",rArr:"Ч—ЧҐ Ч›Ч¤Ч•Чњ ЧњЧ™ЧћЧ™Чџ",hArr:"Ч—ЧҐ Ч›Ч¤Ч•Чњ ЧњЧ™ЧћЧ™Чџ Ч•Ч©ЧћЧђЧњ",diams:"Ч™Ч”ЧњЧ•Чќ ЧћЧњЧђ",asymp:"Ч›ЧћЧўЧ� Ч©Ч•Ч•Ч”"});