п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"EurГі jel",lsquo:"Bal szimpla idГ©zЕ‘jel",rsquo:"Jobb szimpla idГ©zЕ‘jel",ldquo:"Bal dupla idГ©zЕ‘jel",rdquo:"Jobb dupla idГ©zЕ‘jel",ndash:"RГ¶vid gondolatjel",mdash:"HosszГє gondolatjel",iexcl:"FordГ­tott felkiГЎltГіjel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"HosszГє kettЕ‘spont",sect:"Paragrafus jel",uml:"KettЕ‘s hangzГі jel",copy:"SzerzЕ‘i jog jel",ordf:"NЕ‘i sorrend mutatГіja",laquo:"Balra mutatГі duplanyГ­l",not:"FeltГ©teles kГ¶tЕ‘jel",
reg:"Bejegyzett vГ©djegy jele",macr:"HosszГєsГЎgi jel",deg:"Fok jel",sup2:"NГ©gyzeten jel",sup3:"KГ¶bГ¶n jel",acute:"Г‰les Г©kezet",micro:"Mikro-jel",para:"BekezdГ©s jel",middot:"KГ¶zГ©p pont",cedil:"CГ©dille",sup1:"ElsЕ‘n jel",ordm:"FГ©rfi sorrend mutatГіja",raquo:"Jobbra mutatГі duplanyГ­l",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"HГЎrom negyed jel",iquest:"FordГ­tott kГ©rdЕ‘jel",Agrave:"Latin nagy A fordГ­tott Г©kezettel",Aacute:"Latin nagy A normГЎl Г©kezettel",Acirc:"Latin nagy A hajtott Г©kezettel",Atilde:"Latin nagy A hullГЎmjellel",
Auml:"Latin nagy A kettЕ‘spont Г©kezettel",Aring:"Latin nagy A gyЕ±rЕ± Г©kezettel",AElig:"Latin nagy Г† betЕ±",Ccedil:"Latin nagy C cedillГЎval",Egrave:"Latin nagy E fordГ­tott Г©kezettel",Eacute:"Latin nagy E normГЎl Г©kezettel",Ecirc:"Latin nagy E hajtott Г©kezettel",Euml:"Latin nagy E dupla kettЕ‘spont Г©kezettel",Igrave:"Latin nagy I fordГ­tott Г©kezettel",Iacute:"Latin nagy I normГЎl Г©kezettel",Icirc:"Latin nagy I hajtott Г©kezettel",Iuml:"Latin nagy I kettЕ‘spont Г©kezettel",ETH:"Latin nagy Eth betЕ±",Ntilde:"Latin nagy N hullГЎmjellel",
Ograve:"Latin nagy O fordГ­tott Г©kezettel",Oacute:"Latin nagy O normГЎl Г©kezettel",Ocirc:"Latin nagy O hajtott Г©kezettel",Otilde:"Latin nagy O hullГЎmjellel",Ouml:"Latin nagy O kettЕ‘spont Г©kezettel",times:"SzorzГЎs jel",Oslash:"Latin O betЕ± ГЎthГєzГЎssal",Ugrave:"Latin nagy U fordГ­tott Г©kezettel",Uacute:"Latin nagy U normГЎl Г©kezettel",Ucirc:"Latin nagy U hajtott Г©kezettel",Uuml:"Latin nagy U kettЕ‘spont Г©kezettel",Yacute:"Latin nagy Y normГЎl Г©kezettel",THORN:"Latin nagy Thorn betЕ±",szlig:"Latin kis s betЕ±",
agrave:"Latin kis a fordГ­tott Г©kezettel",aacute:"Latin kis a normГЎl Г©kezettel",acirc:"Latin kis a hajtott Г©kezettel",atilde:"Latin kis a hullГЎmjellel",auml:"Latin kis a kettЕ‘spont Г©kezettel",aring:"Latin kis a gyЕ±rЕ± Г©kezettel",aelig:"Latin kis Г¦ betЕ±",ccedil:"Latin kis c cedillГЎval",egrave:"Latin kis e fordГ­tott Г©kezettel",eacute:"Latin kis e normГЎl Г©kezettel",ecirc:"Latin kis e hajtott Г©kezettel",euml:"Latin kis e dupla kettЕ‘spont Г©kezettel",igrave:"Latin kis i fordГ­tott Г©kezettel",iacute:"Latin kis i normГЎl Г©kezettel",
icirc:"Latin kis i hajtott Г©kezettel",iuml:"Latin kis i kettЕ‘spont Г©kezettel",eth:"Latin kis eth betЕ±",ntilde:"Latin kis n hullГЎmjellel",ograve:"Latin kis o fordГ­tott Г©kezettel",oacute:"Latin kis o normГЎl Г©kezettel",ocirc:"Latin kis o hajtott Г©kezettel",otilde:"Latin kis o hullГЎmjellel",ouml:"Latin kis o kettЕ‘spont Г©kezettel",divide:"OsztГЎsjel",oslash:"Latin kis o betЕ± ГЎthГєzГЎssal",ugrave:"Latin kis u fordГ­tott Г©kezettel",uacute:"Latin kis u normГЎl Г©kezettel",ucirc:"Latin kis u hajtott Г©kezettel",
uuml:"Latin kis u kettЕ‘spont Г©kezettel",yacute:"Latin kis y normГЎl Г©kezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kettЕ‘spont Г©kezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott Г©kezettel",374:"Latin nagy Y hajtott Г©kezettel",373:"Latin kis w hajtott Г©kezettel",375:"Latin kis y hajtott Г©kezettel",sbquo:"NyitГі nyomdai szimpla idГ©zЕ‘jel",8219:"ZГЎrГі nyomdai zГЎrГі idГ©zЕ‘jel",bdquo:"NyitГі nyomdai dupla idГ©zЕ‘jel",hellip:"HГЎrom pont",trade:"Kereskedelmi vГ©djegy jele",
9658:"Jobbra mutatГі fekete mutatГі",bull:"GolyГі",rarr:"Jobbra mutatГі nyГ­l",rArr:"Jobbra mutatГі duplanyГ­l",hArr:"Bal-jobb duplanyГ­l",diams:"Fekete gyГ©mГЎnt jel",asymp:"Majdnem egyenlЕ‘ jel"});