п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","lv",{euro:"Euro zД«me",lsquo:"KreisДЃ  vienkДЃrtД«ga pД“diЕ†a",rsquo:"LabДЃ  vienkДЃrtД«ga pД“diЕ†a",ldquo:"KreisДЃ  dubult pД“diЕ†a",rdquo:"LabДЃ dubult pД“diЕ†a",ndash:"En svД«tra",mdash:"Em svД«tra",iexcl:"Apgriezta izsaukuma zД«me",cent:"Centu naudas zД«me",pound:"SterliЕ†u mДЃrciЕ†u naudas zД«me",curren:"ValЕ«tas zД«me",yen:"Jenu naudas zД«me",brvbar:"VertikДЃla pДЃrrauta lД«nija",sect:"ParagrДЃfa zД«me",uml:"Diakritiska zД«me",copy:"AutortiesД«bu zД«me",ordf:"SieviЕЎД·as kДЃrtas rДЃdД«tДЃjs",
laquo:"KreisДЃ dubult stЕ«ra pД“diЕ†u zД«me",not:"NeparakstД«ts",reg:"ReДЈistrД“ta zД«me",macr:"GarumzД«me",deg:"GrДЃdu zД«me",sup2:"AugЕЎraksts divi",sup3:"AugЕЎraksts trД«s",acute:"AkЕ«ta uzsvara zД«me",micro:"Mikro zД«me",para:"Rindkopas zД«me ",middot:"VidД“js punkts",cedil:"ДЂД·Д«tis zem burta",sup1:"AugЕЎraksts viens",ordm:"VД«riЕЎД·Д«gas kДЃrtas rДЃdД«tДЃjs",raquo:"LabДЃ dubult stЕ«ra pД“diЕ†u zД«me",frac14:"VulgДЃra frakcija 1/4",frac12:"VulgДЃra frakcija 1/2",frac34:"VulgДЃra frakcija 3/4",iquest:"Apgriezta jautДЃjuma zД«me",Agrave:"Lielais latД«Е†u burts A ar uzsvara zД«mi",
Aacute:"Lielais  latД«Е†u burts A ar akЕ«tu uzsvara zД«mi",Acirc:"Lielais latД«Е†u burts A ar diakritisku zД«mi",Atilde:"Lielais latД«Е†u burts A ar tildi ",Auml:"Lielais latД«Е†u burts A ar diakritisko zД«mi",Aring:"Lielais latД«Е†u burts A ar aplД«ti augЕЎДЃ",AElig:"Lielais latД«Е†u burts Г†",Ccedil:"Lielais latД«Е†u burts C ar ДЃД·Д«ti zem burta",Egrave:"Lielais latД«Е†u burts E ar apostrofu",Eacute:"Lielais latД«Е†u burts E ar akЕ«tu uzsvara zД«mi",Ecirc:"Lielais latД«Е†u burts E ar diakritisko zД«mi",Euml:"Lielais latД«Е†u burts E ar diakritisko zД«mi",
Igrave:"Lielais latД«Е†u burts I ar uzsvaras  zД«mi",Iacute:"Lielais latД«Е†u burts I ar akЕ«tu uzsvara zД«mi",Icirc:"Lielais latД«Е†u burts I ar diakritisko zД«mi",Iuml:"Lielais latД«Е†u burts I ar diakritisko zД«mi",ETH:"Lielais latД«Е†u burts Eth",Ntilde:"Lielais latД«Е†u burts N ar tildi",Ograve:"Lielais latД«Е†u burts O ar uzsvara zД«mi",Oacute:"Lielais latД«Е†u burts O ar akЕ«to uzsvara zД«mi",Ocirc:"Lielais latД«Е†u burts O ar diakritisko zД«mi",Otilde:"Lielais latД«Е†u burts O ar tildi",Ouml:"Lielais latД«Е†u burts O ar diakritisko zД«mi",
times:"ReizinДЃЕЎanas zД«me ",Oslash:"Lielais latД«Е†u burts O ar iesvД«trojumu",Ugrave:"Lielais latД«Е†u burts U ar uzsvaras zД«mi",Uacute:"Lielais latД«Е†u burts U ar akЕ«to uzsvars zД«mi",Ucirc:"Lielais latД«Е†u burts U ar diakritisko zД«mi",Uuml:"Lielais latД«Е†u burts U ar diakritisko zД«mi",Yacute:"Lielais latД«Е†u burts Y ar akЕ«to uzsvaras zД«mi",THORN:"Lielais latД«Е†u burts torn",szlig:"Mazs latД«Е†u burts ar ligatЕ«ru",agrave:"Mazs latД«Е†u burts a ar uzsvara zД«mi",aacute:"Mazs latД«Е†u burts a ar akЕ«to uzsvara zД«mi",
acirc:"Mazs latД«Е†u burts a ar diakritisko zД«mi",atilde:"Mazs latД«Е†u burts a ar tildi",auml:"Mazs latД«Е†u burts a ar diakritisko zД«mi",aring:"Mazs latД«Е†u burts a ar aplД«ti augЕЎДЃ",aelig:"Mazs latД«Е†u burts Г¦",ccedil:"Mazs latД«Е†u burts c ar ДЃД·Д«ti zem burta",egrave:"Mazs latД«Е†u burts e ar uzsvara zД«mi ",eacute:"Mazs latД«Е†u burts e ar akЕ«tu uzsvara zД«mi",ecirc:"Mazs latД«Е†u burts e ar diakritisko zД«mi",euml:"Mazs latД«Е†u burts e ar diakritisko zД«mi",igrave:"Mazs latД«Е†u burts i ar uzsvara zД«mi ",iacute:"Mazs latД«Е†u burts i ar akЕ«tu uzsvara zД«mi",
icirc:"Mazs latД«Е†u burts i ar diakritisko zД«mi",iuml:"Mazs latД«Е†u burts i ar diakritisko zД«mi",eth:"Mazs latД«Е†u burts eth",ntilde:"Mazs latД«Е†u burts n ar tildi",ograve:"Mazs latД«Е†u burts o ar uzsvara zД«mi ",oacute:"Mazs latД«Е†u burts o ar akЕ«tu uzsvara zД«mi",ocirc:"Mazs latД«Е†u burts o ar diakritisko zД«mi",otilde:"Mazs latД«Е†u burts o ar tildi",ouml:"Mazs latД«Е†u burts o ar diakritisko zД«mi",divide:"DalД«ЕЎanas zД«me",oslash:"Mazs latД«Е†u burts o ar iesvД«trojumu",ugrave:"Mazs latД«Е†u burts u ar uzsvara zД«mi ",
uacute:"Mazs latД«Е†u burts u ar  akЕ«tu uzsvara zД«mi",ucirc:"Mazs latД«Е†u burts u ar diakritisko zД«mi",uuml:"Mazs latД«Е†u burts u ar diakritisko zД«mi",yacute:"Mazs latД«Е†u burts y ar  akЕ«tu uzsvaras zД«mi",thorn:"Mazs latД«Е†u burts torns",yuml:"Mazs latД«Е†u burts y ar diakritisko zД«mi",OElig:"Liela latД«Е†u ligatЕ«ra OE",oelig:"Maza latД«Е†u ligatЕ«ra oe",372:"Liels latД«Е†u burts W ar diakritisko zД«mi ",374:"Liels latД«Е†u burts Y ar diakritisko zД«mi ",373:"Mazs latД«Е†u burts w ar diakritisko zД«mi ",375:"Mazs latД«Е†u burts y ar diakritisko zД«mi ",
sbquo:"Mazas-9 vienkДЃrtД«gas pД“diЕ†as",8219:"Lielas-9 vienkДЃrtД«gas apgrieztas pД“diЕ†as",bdquo:"Mazas-9 dubultas pД“diЕ†as",hellip:"HorizontДЃli daudzpunkti",trade:"PreДЌu zД«mes zД«me",9658:"Melns pa labi pagriezts radД«tДЃjs",bull:"Lode",rarr:"Bulta pa labi",rArr:"Dubulta Bulta pa labi",hArr:"Bulta pa kreisi",diams:"Dubulta Bulta pa kreisi",asymp:"GandrД«z vienДЃds ar"});