п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","nb",{euro:"Eurosymbol",lsquo:"Venstre enkelt anfГёrselstegn",rsquo:"HГёyre enkelt anfГёrselstegn",ldquo:"Venstre dobbelt anfГёrselstegn",rdquo:"HГёyre anfГёrsesltegn",ndash:"Kort tankestrek",mdash:"Lang tankestrek",iexcl:"Omvendt utropstegn",cent:"Centsymbol",pound:"Pundsymbol",curren:"Valutategn",yen:"Yensymbol",brvbar:"Brutt loddrett strek",sect:"Paragraftegn",uml:"TГёddel",copy:"Copyrighttegn",ordf:"Feminin ordensindikator",laquo:"Venstre anfГёrselstegn",not:"Negasjonstegn",
reg:"Registrert varemerke-tegn",macr:"Makron",deg:"Gradsymbol",sup2:"Hevet totall",sup3:"Hevet tretall",acute:"Akutt aksent",micro:"Mikrosymbol",para:"Avsnittstegn",middot:"Midtstilt prikk",cedil:"Cedille",sup1:"Hevet ettall",ordm:"Maskulin ordensindikator",raquo:"HГёyre anfГёrselstegn",frac14:"FjerdedelsbrГёk",frac12:"HalvbrГёk",frac34:"Tre fjerdedelers brГёk",iquest:"Omvendt spГёrsmГҐlstegn",Agrave:"Stor A med grav aksent",Aacute:"Stor A med akutt aksent",Acirc:"Stor A med cirkumfleks",Atilde:"Stor A med tilde",
Auml:"Stor A med tГёddel",Aring:"Stor Г…",AElig:"Stor Г†",Ccedil:"Stor C med cedille",Egrave:"Stor E med grav aksent",Eacute:"Stor E med akutt aksent",Ecirc:"Stor E med cirkumfleks",Euml:"Stor E med tГёddel",Igrave:"Stor I med grav aksent",Iacute:"Stor I med akutt aksent",Icirc:"Stor I med cirkumfleks",Iuml:"Stor I med tГёddel",ETH:"Stor Edd/stungen D",Ntilde:"Stor N med tilde",Ograve:"Stor O med grav aksent",Oacute:"Stor O med akutt aksent",Ocirc:"Stor O med cirkumfleks",Otilde:"Stor O med tilde",Ouml:"Stor O med tГёddel",
times:"Multiplikasjonstegn",Oslash:"Stor Г�",Ugrave:"Stor U med grav aksent",Uacute:"Stor U med akutt aksent",Ucirc:"Stor U med cirkumfleks",Uuml:"Stor U med tГёddel",Yacute:"Stor Y med akutt aksent",THORN:"Stor Thorn",szlig:"Liten dobbelt-s/Eszett",agrave:"Liten a med grav aksent",aacute:"Liten a med akutt aksent",acirc:"Liten a med cirkumfleks",atilde:"Liten a med tilde",auml:"Liten a med tГёddel",aring:"Liten ГҐ",aelig:"Liten Г¦",ccedil:"Liten c med cedille",egrave:"Liten e med grav aksent",eacute:"Liten e med akutt aksent",
ecirc:"Liten e med cirkumfleks",euml:"Liten e med tГёddel",igrave:"Liten i med grav aksent",iacute:"Liten i med akutt aksent",icirc:"Liten i med cirkumfleks",iuml:"Liten i med tГёddel",eth:"Liten edd/stungen d",ntilde:"Liten n med tilde",ograve:"Liten o med grav aksent",oacute:"Liten o med akutt aksent",ocirc:"Liten o med cirkumfleks",otilde:"Liten o med tilde",ouml:"Liten o med tГёddel",divide:"Divisjonstegn",oslash:"Liten Гё",ugrave:"Liten u med grav aksent",uacute:"Liten u med akutt aksent",ucirc:"Liten u med cirkumfleks",
uuml:"Liten u med tГёddel",yacute:"Liten y med akutt aksent",thorn:"Liten thorn",yuml:"Liten y med tГёddel",OElig:"Stor ligatur av O og E",oelig:"Liten ligatur av o og e",372:"Stor W med cirkumfleks",374:"Stor Y med cirkumfleks",373:"Liten w med cirkumfleks",375:"Liten y med cirkumfleks",sbquo:"Enkelt lavt 9-anfГёrselstegn",8219:"Enkelt hГёyt reversert 9-anfГёrselstegn",bdquo:"Dobbelt lavt 9-anfГёrselstegn",hellip:"Ellipse",trade:"Varemerkesymbol",9658:"Svart hГёyrevendt peker",bull:"Tykk interpunkt",rarr:"HГёyrevendt pil",
rArr:"Dobbel hГёyrevendt pil",hArr:"Dobbel venstrevendt pil",diams:"Svart ruter",asymp:"Omtrent likhetstegn"});