п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","oc",{euro:"SimbГІl ГЁuro",lsquo:"Vergueta simpla dobrenta",rsquo:"Vergueta simpla tampanta",ldquo:"Vergueta dobla dobrenta",rdquo:"Vergueta dobla tampanta",ndash:"Jonhent semi-quadratin",mdash:"Jonhent quadratin",iexcl:"Punt d'exclamacion inversat",cent:"SimbГІl cent",pound:"SimbГІl Liura sterling",curren:"SimbГІl monetari",yen:"SimbГІl iГЁn",brvbar:"Barra verticala separada",sect:"Signe de seccion",uml:"TrГЁma",copy:"SimbГІl Copyright",ordf:"Indicador ordinal femenin",
laquo:"Vergueta francesa dobrenta",not:"Croquet de negacion",reg:"SimbГІl de marca depausada",macr:"Macron",deg:"SimbГІl gra",sup2:"Exponent 2",sup3:"Exponent 3",acute:"Accent agut",micro:"SimbГІl micro",para:"SimbГІl pГЁ de mГІsca",middot:"Punt median",cedil:"Cedilha",sup1:"Exponent 1",ordm:"Indicador ordenal masculin",raquo:"Vergueta francesa tampanta",frac14:"Fraccion un quart",frac12:"Fraccion un miГЁg",frac34:"Fraccion tres quarts",iquest:"Punt d'interrogacion inversat",Agrave:"A accent grГЁu majuscula",
Aacute:"A accent agut majuscula",Acirc:"A accent circonflГЁxe majuscula",Atilde:"A caron majuscula",Auml:"A trГЁma majuscula",Aring:"A redond majuscula",AElig:"Ligatura Г† majuscula",Ccedil:"C cГ©dille majuscula",Egrave:"E accent grГЁu majuscula",Eacute:"E accent agut majuscula",Ecirc:"E accent circonflГЁxe majuscula",Euml:"E trГЁma majuscula",Igrave:"I accent grГЁu majuscula",Iacute:"I accent agut majuscula",Icirc:"I accent circonflГЁxe majuscula",Iuml:"I trГЁma majuscula",ETH:"Letra majuscula islandaise ED",
Ntilde:"N caron majuscula",Ograve:"O accent grГЁu majuscula",Oacute:"O accent agut majuscula",Ocirc:"O accent circonflГЁxe majuscula",Otilde:"O caron majuscula",Ouml:"O trГЁma majuscula",times:"SimbГІl de multiplicacion",Oslash:"O raiat majuscula",Ugrave:"U accent grГЁu majuscula",Uacute:"U accent agut majuscula",Ucirc:"U accent circonflГЁxe majuscula",Uuml:"U trГЁma majuscula",Yacute:"Y accent agut majuscula",THORN:"Letra islandesa thorn majuscula",szlig:"Letra minuscula alemanda S dur",agrave:"A accent grГЁu minuscula",
aacute:"A accent agut minuscula",acirc:"A accent circonflГЁxe minuscula",atilde:"A tilda minuscula",auml:"A trГЁma minuscula",aring:"A redond minuscula",aelig:"Ligatura Г† minuscula",ccedil:"C cГ©dille minuscula",egrave:"E accent grГЁu minuscula",eacute:"E accent agut minuscula",ecirc:"E accent circonflГЁxe minuscula",euml:"E trГЁma minuscula",igrave:"I accent grГЁu minuscula",iacute:"I accent agut minuscula",icirc:"I accent circonflГЁxe minuscula",iuml:"i minuscula trГЁma",eth:"Letra minuscula islandaise ED",
ntilde:"N caron minuscula",ograve:"O minuscula accent grГЁu",oacute:"O accent agut minuscula",ocirc:"O accent circonflГЁxe minuscula",otilde:"O tilda minuscula",ouml:"O trГЁma minuscula",divide:"SimbГІl de division",oslash:"O raiat minuscula",ugrave:"U accent grГЁu minuscula",uacute:"U accent agut minuscula",ucirc:"U accent circonflГЁxe minuscula",uuml:"U trГЁma minuscula",yacute:"Y accent agut minuscula",thorn:"Letra islandaise thorn minuscula",yuml:"Y trГЁma minuscula",OElig:"Ligatura Е’ majuscula",oelig:"Ligatura Е’ minuscula",
372:"W accent circonflГЁxe majuscula",374:"Y accent circonflГЁxe majuscula",373:"W accent circonflГЁxe minuscula",375:"Y accent circonflГЁxe minuscula",sbquo:"Vergueta simpla tampanta inferior",8219:"Vergueta-virgula superior culbutГ©",bdquo:"Vergueta-virgula double inferior",hellip:"Punts de suspension",trade:"SimbГІl de marca comerciala",9658:"Sageta negra puntant cap a dreita",bull:"GrГІs punt median",rarr:"Sageta cap a dreita",rArr:"Sageta dobla cap a dreita",hArr:"Sageta dobla cap a esquГЁrra",diams:"Lausange negre",
asymp:"Environ egal"});