п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"CudzysЕ‚Гіw pojedynczy otwierajД…cy",rsquo:"CudzysЕ‚Гіw pojedynczy zamykajД…cy",ldquo:"CudzysЕ‚Гіw apostrofowy otwierajД…cy",rdquo:"CudzysЕ‚Гіw apostrofowy zamykajД…cy",ndash:"PГіЕ‚pauza",mdash:"Pauza",iexcl:"OdwrГіcony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"WskaЕєnik rodzaju ЕјeЕ„skiego liczebnika porzД…dkowego",
laquo:"Lewy cudzysЕ‚Гіw ostrokД…tny",not:"Znak negacji",reg:"ZastrzeЕјony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga potД™ga",sup3:"Trzecia potД™ga",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka Е›rodkowa",cedil:"Cedylla",sup1:"Pierwsza potД™ga",ordm:"WskaЕєnik rodzaju mД™skiego liczebnika porzД…dkowego",raquo:"Prawy cudzysЕ‚Гіw ostrokД…tny",frac14:"UЕ‚amek zwykЕ‚y jedna czwarta",frac12:"UЕ‚amek zwykЕ‚y jedna druga",frac34:"UЕ‚amek zwykЕ‚y trzy czwarte",iquest:"OdwrГіcony znak zapytania",
Agrave:"Wielka litera A z akcentem ciД™Ејkim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przeciД…gЕ‚ym",Atilde:"Wielka litera A z tyldД…",Auml:"Wielka litera A z dierezД…",Aring:"Wielka litera A z kГіЕ‚kiem",AElig:"Wielka ligatura Г†",Ccedil:"Wielka litera C z cedyllД…",Egrave:"Wielka litera E z akcentem ciД™Ејkim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przeciД…gЕ‚ym",Euml:"Wielka litera E z dierezД…",Igrave:"Wielka litera I z akcentem ciД™Ејkim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przeciД…gЕ‚ym",Iuml:"Wielka litera I z dierezД…",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tyldД…",Ograve:"Wielka litera O z akcentem ciД™Ејkim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przeciД…gЕ‚ym",Otilde:"Wielka litera O z tyldД…",Ouml:"Wielka litera O z dierezД…",times:"Znak mnoЕјenia wektorowego",Oslash:"Wielka litera O z przekreЕ›leniem",Ugrave:"Wielka litera U z akcentem ciД™Ејkim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przeciД…gЕ‚ym",Uuml:"Wielka litera U z dierezД…",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"MaЕ‚a litera ostre s (eszet)",agrave:"MaЕ‚a litera a z akcentem ciД™Ејkim",aacute:"MaЕ‚a litera a z akcentem ostrym",acirc:"MaЕ‚a litera a z akcentem przeciД…gЕ‚ym",atilde:"MaЕ‚a litera a z tyldД…",auml:"MaЕ‚a litera a z dierezД…",aring:"MaЕ‚a litera a z kГіЕ‚kiem",aelig:"MaЕ‚a ligatura Г¦",ccedil:"MaЕ‚a litera c z cedyllД…",egrave:"MaЕ‚a litera e z akcentem ciД™Ејkim",
eacute:"MaЕ‚a litera e z akcentem ostrym",ecirc:"MaЕ‚a litera e z akcentem przeciД…gЕ‚ym",euml:"MaЕ‚a litera e z dierezД…",igrave:"MaЕ‚a litera i z akcentem ciД™Ејkim",iacute:"MaЕ‚a litera i z akcentem ostrym",icirc:"MaЕ‚a litera i z akcentem przeciД…gЕ‚ym",iuml:"MaЕ‚a litera i z dierezД…",eth:"MaЕ‚a litera eth",ntilde:"MaЕ‚a litera n z tyldД…",ograve:"MaЕ‚a litera o z akcentem ciД™Ејkim",oacute:"MaЕ‚a litera o z akcentem ostrym",ocirc:"MaЕ‚a litera o z akcentem przeciД…gЕ‚ym",otilde:"MaЕ‚a litera o z tyldД…",ouml:"MaЕ‚a litera o z dierezД…",
divide:"Anglosaski znak dzielenia",oslash:"MaЕ‚a litera o z przekreЕ›leniem",ugrave:"MaЕ‚a litera u z akcentem ciД™Ејkim",uacute:"MaЕ‚a litera u z akcentem ostrym",ucirc:"MaЕ‚a litera u z akcentem przeciД…gЕ‚ym",uuml:"MaЕ‚a litera u z dierezД…",yacute:"MaЕ‚a litera y z akcentem ostrym",thorn:"MaЕ‚a litera thorn",yuml:"MaЕ‚a litera y z dierezД…",OElig:"Wielka ligatura OE",oelig:"MaЕ‚a ligatura oe",372:"Wielka litera W z akcentem przeciД…gЕ‚ym",374:"Wielka litera Y z akcentem przeciД…gЕ‚ym",373:"MaЕ‚a litera w z akcentem przeciД…gЕ‚ym",
375:"MaЕ‚a litera y z akcentem przeciД…gЕ‚ym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof gГіrny",bdquo:"PodwГіjny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wskaЕєnik wskazujД…cy w prawo",bull:"Punktor",rarr:"StrzaЕ‚ka w prawo",rArr:"PodwГіjna strzaЕ‚ka w prawo",hArr:"PodwГіjna strzaЕ‚ka obustronna",diams:"Czarny znak karo",asymp:"Znak prawie rГіwne"});