п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt-br",{euro:"Euro",lsquo:"Aspas simples esquerda",rsquo:"Aspas simples direita",ldquo:"Aspas duplas esquerda",rdquo:"Aspas duplas direita",ndash:"TraГ§o",mdash:"TravessГЈo",iexcl:"Ponto de exclamaГ§ГЈo invertido",cent:"Cent",pound:"Cerquilha",curren:"Dinheiro",yen:"Yen",brvbar:"Bara interrompida",sect:"SГ­mbolo de ParГЎgrafo",uml:"Trema",copy:"Direito de CГіpia",ordf:"Indicador ordinal feminino",laquo:"Aspas duplas angulares esquerda",not:"NegaГ§ГЈo",reg:"Marca Registrada",
macr:"MГЎcron",deg:"Grau",sup2:"2 Superscrito",sup3:"3 Superscrito",acute:"Acento agudo",micro:"Micro",para:"PГ© de mosca",middot:"Ponto mediano",cedil:"Cedilha",sup1:"1 Superscrito",ordm:"Indicador ordinal masculino",raquo:"Aspas duplas angulares direita",frac14:"Um quarto",frac12:"Um meio",frac34:"TrГЄs quartos",iquest:"InterrogaГ§ГЈo invertida",Agrave:"A maiГєsculo com acento grave",Aacute:"A maiГєsculo com acento agudo",Acirc:"A maiГєsculo com acento circunflexo",Atilde:"A maiГєsculo com til",Auml:"A maiГєsculo com trema",
Aring:"A maiГєsculo com anel acima",AElig:"Г† maiГєsculo",Ccedil:"Г‡ maiГєlculo",Egrave:"E maiГєsculo com acento grave",Eacute:"E maiГєsculo com acento agudo",Ecirc:"E maiГєsculo com acento circumflexo",Euml:"E maiГєsculo com trema",Igrave:"I maiГєsculo com acento grave",Iacute:"I maiГєsculo com acento agudo",Icirc:"I maiГєsculo com acento circunflexo",Iuml:"I maiГєsculo com crase",ETH:"Eth maiГєsculo",Ntilde:"N maiГєsculo com til",Ograve:"O maiГєsculo com acento grave",Oacute:"O maiГєsculo com acento agudo",Ocirc:"O maiГєsculo com acento circunflexo",
Otilde:"O maiГєsculo com til",Ouml:"O maiГєsculo com trema",times:"MultiplicaГ§ГЈo",Oslash:"DiГўmetro",Ugrave:"U maiГєsculo com acento grave",Uacute:"U maiГєsculo com acento agudo",Ucirc:"U maiГєsculo com acento circunflexo",Uuml:"U maiГєsculo com trema",Yacute:"Y maiГєsculo com acento agudo",THORN:"Thorn maiГєsculo",szlig:"Eszett minГєsculo",agrave:"a minГєsculo com acento grave",aacute:"a minГєsculo com acento agudo",acirc:"a minГєsculo com acento circunflexo",atilde:"a minГєsculo com til",auml:"a minГєsculo com trema",
aring:"a minГєsculo com anel acima",aelig:"Г¦ minГєsculo",ccedil:"Г§ minГєsculo",egrave:"e minГєsculo com acento grave",eacute:"e minГєsculo com acento agudo",ecirc:"e minГєsculo com acento circunflexo",euml:"e minГєsculo com trema",igrave:"i minГєsculo com acento grave",iacute:"i minГєsculo com acento agudo",icirc:"i minГєsculo com acento circunflexo",iuml:"i minГєsculo com trema",eth:"eth minГєsculo",ntilde:"n minГєsculo com til",ograve:"o minГєsculo com acento grave",oacute:"o minГєsculo com acento agudo",ocirc:"o minГєsculo com acento circunflexo",
otilde:"o minГєsculo com til",ouml:"o minГєsculo com trema",divide:"DivisГЈo",oslash:"o minГєsculo com cortado ou diГўmetro",ugrave:"u minГєsculo com acento grave",uacute:"u minГєsculo com acento agudo",ucirc:"u minГєsculo com acento circunflexo",uuml:"u minГєsculo com trema",yacute:"y minГєsculo com acento agudo",thorn:"thorn minГєsculo",yuml:"y minГєsculo com trema",OElig:"LigaГ§ГЈo tipogrГЎfica OE maiГєscula",oelig:"LigaГ§ГЈo tipogrГЎfica oe minГєscula",372:"W maiГєsculo com acento circunflexo",374:"Y maiГєsculo com acento circunflexo",
373:"w minГєsculo com acento circunflexo",375:"y minГєsculo com acento circunflexo",sbquo:"Aspas simples inferior direita",8219:"Aspas simples superior esquerda",bdquo:"Aspas duplas inferior direita",hellip:"ReticГЄncias",trade:"Trade mark",9658:"Ponta de seta preta para direita",bull:"Ponto lista",rarr:"Seta para direita",rArr:"Seta dupla para direita",hArr:"Seta dupla direita e esquerda",diams:"Ouros",asymp:"Aproximadamente"});