п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt",{euro:"SГ­mbolo de Euro",lsquo:"Aspa esquerda simples",rsquo:"Aspa direita simples",ldquo:"Aspa esquerda dupla",rdquo:"Aspa direita dupla",ndash:"TravessГЈo simples",mdash:"TravessГЈo longo",iexcl:"Ponto de exclamaГ§ГЈo invertido",cent:"SГ­mbolo de cГЄntimo",pound:"SГ­mbolo de Libra",curren:"SГ­mbolo de Moeda",yen:"SГ­mbolo de Iene",brvbar:"Barra quebrada",sect:"SГ­mbolo de secГ§ГЈo",uml:"Trema",copy:"SГ­mbolo de direitos de autor",ordf:"Indicador ordinal feminino",laquo:"Aspa esquerda Гўngulo duplo",
not:"NГЈo sГ­mbolo",reg:"SГ­mbolo de registado",macr:"MГЎcron",deg:"SГ­mbolo de graus",sup2:"Expoente 2",sup3:"Expoente 3",acute:"Acento agudo",micro:"SГ­mbolo de micro",para:"SГ­mbolo de parГЎgrafo",middot:"Ponto do meio",cedil:"Cedilha",sup1:"Expoente 1",ordm:"Indicador ordinal masculino",raquo:"Aspas Гўngulo duplo para a direita",frac14:"FraГ§ГЈo vulgar 1/4",frac12:"FraГ§ГЈo vulgar 1/2",frac34:"FraГ§ГЈo vulgar 3/4",iquest:"Ponto de interrogaГ§ГЈo invertido",Agrave:"Letra maiГєscula latina A com acento grave",Aacute:"Letra maiГєscula latina A com acento agudo",
Acirc:"Letra maiГєscula latina A com circunflexo",Atilde:"Letra maiГєscula latina A com til",Auml:"Letra maiГєscula latina A com trema",Aring:"Letra maiГєscula latina A com sinal diacrГ­tico",AElig:"Letra maiГєscula latina Г†",Ccedil:"Letra maiГєscula latina C com cedilha",Egrave:"Letra maiГєscula latina E com acento grave",Eacute:"Letra maiГєscula latina E com acento agudo",Ecirc:"Letra maiГєscula latina E com circunflexo",Euml:"Letra maiГєscula latina E com trema",Igrave:"Letra maiГєscula latina I com acento grave",
Iacute:"Letra maiГєscula latina I com acento agudo",Icirc:"Letra maiГєscula latina I com cincunflexo",Iuml:"Letra maiГєscula latina I com trema",ETH:"Letra maiГєscula latina Eth (ГђГ°)",Ntilde:"Letra maiГєscula latina N com til",Ograve:"Letra maiГєscula latina O com acento grave",Oacute:"Letra maiГєscula latina O com acento agudo",Ocirc:"Letra maiГєscula latina I com circunflexo",Otilde:"Letra maiГєscula latina O com til",Ouml:"Letra maiГєscula latina O com trema",times:"SГ­mbolo de multiplicaГ§ГЈo",Oslash:"Letra maiГєscula O com barra",
Ugrave:"Letra maiГєscula latina U com acento grave",Uacute:"Letra maiГєscula latina U com acento agudo",Ucirc:"Letra maiГєscula latina U com circunflexo",Uuml:"Letra maiГєscula latina E com trema",Yacute:"Letra maiГєscula latina Y com acento agudo",THORN:"Letra maiГєscula latina RГєnico",szlig:"Letra minГєscula latina s forte",agrave:"Letra minГєscula latina a com acento grave",aacute:"Letra minГєscula latina a com acento agudo",acirc:"Letra minГєscula latina a com circunflexo",atilde:"Letra minГєscula latina a com til",
auml:"Letra minГєscula latina a com trema",aring:"Letra minГєscula latina a com sinal diacrГ­tico",aelig:"Letra minГєscula latina Г¦",ccedil:"Letra minГєscula latina c com cedilha",egrave:"Letra minГєscula latina e com acento grave",eacute:"Letra minГєscula latina e com acento agudo",ecirc:"Letra minГєscula latina e com circunflexo",euml:"Letra minГєscula latina e com trema",igrave:"Letra minГєscula latina i com acento grave",iacute:"Letra minГєscula latina i com acento agudo",icirc:"Letra minГєscula latina i com circunflexo",
iuml:"Letra pequena latina i com trema",eth:"Letra minГєscula latina eth",ntilde:"Letra minГєscula latina n com til",ograve:"Letra minГєscula latina o com acento grave",oacute:"Letra minГєscula latina o com acento agudo",ocirc:"Letra minГєscula latina o com circunflexo",otilde:"Letra minГєscula latina o com til",ouml:"Letra minГєscula latina o com trema",divide:"SГ­mbolo de divisГЈo",oslash:"Letra minГєscula latina o com barra",ugrave:"Letra minГєscula latina u com acento grave",uacute:"Letra minГєscula latina u com acento agudo",
ucirc:"Letra minГєscula latina u com circunflexo",uuml:"Letra minГєscula latina u com trema",yacute:"Letra minГєscula latina y com acento agudo",thorn:"Letra minГєscula latina RГєnico",yuml:"Letra minГєscula latina y com trema",OElig:"Ligadura maiГєscula latina OE",oelig:"Ligadura minГєscula latina oe",372:"Letra maiГєscula latina W com circunflexo",374:"Letra maiГєscula latina Y com circunflexo",373:"Letra minГєscula latina w com circunflexo",375:"Letra minГєscula latina y com circunflexo",sbquo:"Aspa Simples inferior-9",
8219:"Aspa simples superior invertida-9",bdquo:"Aspa duplas inferior-9",hellip:"Elipse horizontal ",trade:"SГ­mbolo de marca registada",9658:"Ponteiro preto direito",bull:"Marca",rarr:"Seta para a direita",rArr:"Seta dupla para a direita",hArr:"Seta dupla direita esquerda",diams:"Naipe diamante preto",asymp:"Quase igual a "});