п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"ДЅavГЎ jednoduchГЎ Гєvodzovka",rsquo:"PravГЎ jednoduchГЎ Гєvodzovka",ldquo:"PravГЎ dvojitГЎ Гєvodzovka",rdquo:"PravГЎ dvojitГЎ Гєvodzovka",ndash:"En pomlДЌka",mdash:"Em pomlДЌka",iexcl:"ObrГЎtenГЅ vГЅkriДЌnГ­k",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"PreruЕЎenГЎ zvislГЎ ДЌiara",sect:"Znak odseku",uml:"PrehlГЎska",copy:"Znak copyrightu",ordf:"ЕЅenskГЅ indikГЎtor rodu",laquo:"Znak dvojitГЅch lomenГЅch Гєvodzoviek vДѕavo",not:"LogistickГЅ zГЎpor",
reg:"Znak registrГЎcie",macr:"PomlДЌka nad",deg:"Znak stupЕ€a",sup2:"Dvojka ako hornГЅ index",sup3:"Trojka ako hornГЅ index",acute:"DДєЕѕeЕ€",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vДѕavo",sup1:"Jednotka ako hornГЅ index",ordm:"MuЕѕskГЅ indikГЎtor rodu",raquo:"Znak dvojitГЅch lomenГЅch Гєvodzoviek vpravo",frac14:"ObyДЌajnГЅ zlomok jedna ЕЎtvrtina",frac12:"ObyДЌajnГЅ zlomok jedna polovica",frac34:"ObyДЌajnГЅ zlomok tri ЕЎtvrtiny",iquest:"OtoДЌenГЅ otГЎznik",Agrave:"VeДѕkГ© pГ­smeno latinky A s accentom",
Aacute:"VeДѕkГ© pГ­smeno latinky A s dДєЕѕЕ€om",Acirc:"VeДѕkГ© pГ­smeno latinky A s mГ¤kДЌeЕ€om",Atilde:"VeДѕkГ© pГ­smeno latinky A s tildou",Auml:"VeДѕkГ© pГ­smeno latinky A s dvoma bodkami",Aring:"VeДѕkГ© pГ­smeno latinky A s krГєЕѕkom nad",AElig:"VeДѕkГ© pГ­smeno latinky Г†",Ccedil:"VeДѕkГ© pГ­smeno latinky C s chvostom vДѕavo",Egrave:"VeДѕkГ© pГ­smeno latinky E s accentom",Eacute:"VeДѕkГ© pГ­smeno latinky E s dДєЕѕЕ€om",Ecirc:"VeДѕkГ© pГ­smeno latinky E s mГ¤kДЌeЕ€om",Euml:"VeДѕkГ© pГ­smeno latinky E s dvoma bodkami",Igrave:"VeДѕkГ© pГ­smeno latinky I s accentom",
Iacute:"VeДѕkГ© pГ­smeno latinky I s dДєЕѕЕ€om",Icirc:"VeДѕkГ© pГ­smeno latinky I s mГ¤kДЌeЕ€om",Iuml:"VeДѕkГ© pГ­smeno latinky I s dvoma bodkami",ETH:"VeДѕkГ© pГ­smeno latinky Eth",Ntilde:"VeДѕkГ© pГ­smeno latinky N s tildou",Ograve:"VeДѕkГ© pГ­smeno latinky O s accentom",Oacute:"VeДѕkГ© pГ­smeno latinky O s dДєЕѕЕ€om",Ocirc:"VeДѕkГ© pГ­smeno latinky O s mГ¤kДЌeЕ€om",Otilde:"VeДѕkГ© pГ­smeno latinky O s tildou",Ouml:"VeДѕkГ© pГ­smeno latinky O s dvoma bodkami",times:"Znak nГЎsobenia",Oslash:"VeДѕkГ© pГ­smeno latinky O preЕЎkrtnutГ©",Ugrave:"VeДѕkГ© pГ­smeno latinky U s accentom",
Uacute:"VeДѕkГ© pГ­smeno latinky U s dДєЕѕЕ€om",Ucirc:"VeДѕkГ© pГ­smeno latinky U s mГ¤kДЌeЕ€om",Uuml:"VeДѕkГ© pГ­smeno latinky U s dvoma bodkami",Yacute:"VeДѕkГ© pГ­smeno latinky Y s dДєЕѕЕ€om",THORN:"VeДѕkГ© pГ­smeno latinky Thorn",szlig:"MalГ© pГ­smeno latinky ostrГ© s",agrave:"MalГ© pГ­smeno latinky a s accentom",aacute:"MalГ© pГ­smeno latinky a s dДєЕѕЕ€om",acirc:"MalГ© pГ­smeno latinky a s mГ¤kДЌeЕ€om",atilde:"MalГ© pГ­smeno latinky a s tildou",auml:"MalГ© pГ­smeno latinky a s dvoma bodkami",aring:"MalГ© pГ­smeno latinky a s krГєЕѕkom nad",
aelig:"MalГ© pГ­smeno latinky Г¦",ccedil:"MalГ© pГ­smeno latinky c s chvostom vДѕavo",egrave:"MalГ© pГ­smeno latinky e s accentom",eacute:"MalГ© pГ­smeno latinky e s dДєЕѕЕ€om",ecirc:"MalГ© pГ­smeno latinky e s mГ¤kДЌeЕ€om",euml:"MalГ© pГ­smeno latinky e s dvoma bodkami",igrave:"MalГ© pГ­smeno latinky i s accentom",iacute:"MalГ© pГ­smeno latinky i s dДєЕѕЕ€om",icirc:"MalГ© pГ­smeno latinky i s mГ¤kДЌeЕ€om",iuml:"MalГ© pГ­smeno latinky i s dvoma bodkami",eth:"MalГ© pГ­smeno latinky eth",ntilde:"MalГ© pГ­smeno latinky n s tildou",ograve:"MalГ© pГ­smeno latinky o s accentom",
oacute:"MalГ© pГ­smeno latinky o s dДєЕѕЕ€om",ocirc:"MalГ© pГ­smeno latinky o s mГ¤kДЌeЕ€om",otilde:"MalГ© pГ­smeno latinky o s tildou",ouml:"MalГ© pГ­smeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"MalГ© pГ­smeno latinky o preЕЎkrtnutГ©",ugrave:"MalГ© pГ­smeno latinky u s accentom",uacute:"MalГ© pГ­smeno latinky u s dДєЕѕЕ€om",ucirc:"MalГ© pГ­smeno latinky u s mГ¤kДЌeЕ€om",uuml:"MalГ© pГ­smeno latinky u s dvoma bodkami",yacute:"MalГ© pГ­smeno latinky y s dДєЕѕЕ€om",thorn:"MalГ© pГ­smeno latinky thorn",yuml:"MalГ© pГ­smeno latinky y s dvoma bodkami",
OElig:"VeДѕkГЎ ligatГєra latinky OE",oelig:"MalГЎ ligatГєra latinky OE",372:"VeДѕkГ© pГ­smeno latinky W s mГ¤kДЌeЕ€om",374:"VeДѕkГ© pГ­smeno latinky Y s mГ¤kДЌeЕ€om",373:"MalГ© pГ­smeno latinky w s mГ¤kДЌeЕ€om",375:"MalГ© pГ­smeno latinky y s mГ¤kДЌeЕ€om",sbquo:"DolnГЎ jednoduchГЎ 9-Гєvodzovka",8219:"HornГЎ jednoduchГЎ otoДЌenГЎ 9-Гєvodzovka",bdquo:"DolnГЎ dvojitГЎ 9-Гєvodzovka",hellip:"TrojbodkovГЅ Гєvod",trade:"Znak ibchodnej znaДЌky",9658:"ДЊierny ukazovateДѕ smerujГєci vpravo",bull:"Kruh",rarr:"Е Г­pka vpravo",rArr:"DvojitГЎ ЕЎipka vpravo",
hArr:"DvojitГЎ ЕЎipka vДѕavo a vpravo",diams:"ДЊierne piky",asymp:"Skoro sa rovnГЎ"});