п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Znak za evro",lsquo:"Levi enojni narekovaj",rsquo:"Desni enojni narekovaj",ldquo:"Levi dvojni narekovaj",rdquo:"Desni dvojni narekovaj",ndash:"PomiЕЎljaj",mdash:"Dolgi pomiЕЎljaj",iexcl:"Obrnjen klicaj",cent:"Znak za cent",pound:"Znak za funt",curren:"Znak valute",yen:"Znak za jen",brvbar:"Zlomljena ДЌrta",sect:"Znak za ДЌlen",uml:"Diereza",copy:"Znak avtorskih pravic",ordf:"ЕЅenski zaporedni kazalnik",laquo:"Levi dvojni lomljeni narekovaj",not:"Znak za ne",
reg:"Registrirani znak",macr:"NadДЌrtano",deg:"Znak za stopinje",sup2:"Nadpisano dva",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Znak za mikro",para:"Znak za odstavek",middot:"Usredinjena pika",cedil:"Cedilla",sup1:"Nadpisano ena",ordm:"MoЕЎki zaporedni kazalnik",raquo:"Desno obrnjen dvojni kotni narekovaj",frac14:"Ena ДЌetrtina",frac12:"Ena polovica",frac34:"Tri ДЌetrtine",iquest:"Obrnjen vpraЕЎaj",Agrave:"Velika latinska ДЌrka A s krativcem",Aacute:"Velika latinska ДЌrka A z ostrivcem",Acirc:"Velika latinska ДЌrka A s streЕЎico",
Atilde:"Velika latinska ДЌrka A z tildo",Auml:"Velika latinska ДЌrka A z diaeresis-om",Aring:"Velika latinska ДЌrka A z obroДЌem",AElig:"Velika latinska ДЌrka Г†",Ccedil:"Velika latinska ДЌrka C s cedillo",Egrave:"Velika latinska ДЌrka E s krativcem",Eacute:"Velika latinska ДЌrka E z ostrivcem",Ecirc:"Velika latinska ДЌrka E s streЕЎico",Euml:"Velika latinska ДЌrka E z diaeresis-om",Igrave:"Velika latinska ДЌrka I s krativcem",Iacute:"Velika latinska ДЌrka I z ostrivcem",Icirc:"Velika latinska ДЌrka I s streЕЎico",
Iuml:"Velika latinska ДЌrka I z diaeresis-om",ETH:"Velika latinska ДЌrka Eth",Ntilde:"Velika latinska ДЌrka N s tildo",Ograve:"Velika latinska ДЌrka O s krativcem",Oacute:"Velika latinska ДЌrka O z ostrivcem",Ocirc:"Velika latinska ДЌrka O s streЕЎico",Otilde:"Velika latinska ДЌrka O s tildo",Ouml:"Velika latinska ДЌrka O z diaeresis-om",times:"Znak za mnoЕѕenje",Oslash:"Velika preДЌrtana latinska ДЌrka O",Ugrave:"Velika latinska ДЌrka U s krativcem",Uacute:"Velika latinska ДЌrka U z ostrivcem",Ucirc:"Velika latinska ДЌrka U s streЕЎico",
Uuml:"Velika latinska ДЌrka U z diaeresis-om",Yacute:"Velika latinska ДЌrka Y z ostrivcem",THORN:"Velika latinska ДЌrka Thorn",szlig:"Mala ostra latinska ДЌrka s",agrave:"Mala latinska ДЌrka a s krativcem",aacute:"Mala latinska ДЌrka a z ostrivcem",acirc:"Mala latinska ДЌrka a s streЕЎico",atilde:"Mala latinska ДЌrka a s tildo",auml:"Mala latinska ДЌrka a z diaeresis-om",aring:"Mala latinska ДЌrka a z obroДЌem",aelig:"Mala latinska ДЌrka Г¦",ccedil:"Mala latinska ДЌrka c s cedillo",egrave:"Mala latinska ДЌrka e s krativcem",
eacute:"Mala latinska ДЌrka e z ostrivcem",ecirc:"Mala latinska ДЌrka e s streЕЎico",euml:"Mala latinska ДЌrka e z diaeresis-om",igrave:"Mala latinska ДЌrka i s krativcem",iacute:"Mala latinska ДЌrka i z ostrivcem",icirc:"Mala latinska ДЌrka i s streЕЎico",iuml:"Mala latinska ДЌrka i z diaeresis-om",eth:"Mala latinska ДЌrka eth",ntilde:"Mala latinska ДЌrka n s tildo",ograve:"Mala latinska ДЌrka o s krativcem",oacute:"Mala latinska ДЌrka o z ostrivcem",ocirc:"Mala latinska ДЌrka o s streЕЎico",otilde:"Mala latinska ДЌrka o s tildo",
ouml:"Mala latinska ДЌrka o z diaeresis-om",divide:"Znak za deljenje",oslash:"Mala preДЌrtana latinska ДЌrka o",ugrave:"Mala latinska ДЌrka u s krativcem",uacute:"Mala latinska ДЌrka u z ostrivcem",ucirc:"Mala latinska ДЌrka u s streЕЎico",uuml:"Mala latinska ДЌrka u z diaeresis-om",yacute:"Mala latinska ДЌrka y z ostrivcem",thorn:"Mala latinska ДЌrka thorn",yuml:"Mala latinska ДЌrka y z diaeresis-om",OElig:"Velika latinska ligatura OE",oelig:"Mala latinska ligatura oe",372:"Velika latinska ДЌrka W s streЕЎico",
374:"Velika latinska ДЌrka Y s streЕЎico",373:"Mala latinska ДЌrka w s streЕЎico",375:"Mala latinska ДЌrka y s streЕЎico",sbquo:"Enojni nizki-9 narekovaj",8219:"Enojni visoki-obrnjen-9 narekovaj",bdquo:"Dvojni nizki-9 narekovaj",hellip:"Horizontalni izpust",trade:"Znak blagovne znamke",9658:"ДЊrni desno-usmerjen kazalec",bull:"Krogla",rarr:"Desno-usmerjena puЕЎДЌica",rArr:"Desno-usmerjena dvojna puЕЎДЌica",hArr:"Leva in desna dvojna puЕЎДЌica",diams:"ДЊrna kara",asymp:"Skoraj enako"});