п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"ThonjГ«za majtas me njГ« vi",rsquo:"ThonjГ«za djathtas me njГ« vi",ldquo:"ThonjГ«za majtas",rdquo:"ThonjГ«za djathtas",ndash:"En viza lidhГ«se",mdash:"Em viza lidhГ«se",iexcl:"PikГ«Г§uditГ«se e pГ«rmbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valutГ«s",yen:"Shenja e Jenit",brvbar:"Viza e kГ«putur",sect:"Shenja e pjesГ«s",uml:"Diaeresis",copy:"Shenja e tГ« drejtave tГ« kopjimit",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Nuk ka shenjГ«",reg:"Shenja e tГ« regjistruarit",macr:"Macron",deg:"Shenja e shkallГ«s",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mprehtГ«",micro:"Shjenja e Mikros",para:"Pilcrow sign",middot:"Pika e Mesme",cedil:"Hark nГ«n shkronja",sup1:"Super-skripta njГ«",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Thyesa njГ« tГ« katrat",frac12:"Thyesa njГ« tГ« dytat",frac34:"Thyesa tre tГ« katrat",iquest:"PikГ«pyetje e pГ«rmbysur",Agrave:"Shkronja e madhe latine A me theks tГ« rГ«ndГ«",
Aacute:"Shkronja e madhe latine A me theks akute",Acirc:"Shkronja e madhe latine A me theks lakor",Atilde:"Shkronja e madhe latine A me tildГ«",Auml:"Shkronja e madhe latine A me dy pika",Aring:"Shkronja e madhe latine A me unazГ« mbi",AElig:"Shkronja e madhe latine Г†",Ccedil:"Shkronja e madhe latine C me hark poshtГ«",Egrave:"Shkronja e madhe latine E me theks tГ« rГ«ndГ«",Eacute:"Shkronja e madhe latine E me theks akute",Ecirc:"Shkronja e madhe latine E me theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
Igrave:"Shkronja e madhe latine I me theks tГ« rГ«ndГ«",Iacute:"Shkronja e madhe latine I me theks akute",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronja e madhe latine I me dy pika",ETH:"Shkronja e madhe latine Eth",Ntilde:"Shkronja e madhe latine N me tildГ«",Ograve:"Shkronja e madhe latine O me theks tГ« rГ«ndГ«",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tildГ«",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shumГ«zimit",Oslash:"Shkronja e madhe latine O me vizГ« nГ« mes",Ugrave:"Shkronja e madhe latine U me theks tГ« rГ«ndГ«",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e vogГ« latine s e mprehtГ«",agrave:"Shkronja e vogГ« latine a me theks tГ« rГ«ndГ«",aacute:"Shkronja e vogГ« latine a me theks tГ« mprehtГ«",
acirc:"Shkronja e vogГ«l latine a me theks lakor",atilde:"Shkronja e vogГ«l latine a me tildГ«",auml:"Shkronja e vogГ«l latine a me dy pika",aring:"Shkronja e vogГ« latine a me unazГ« mbi",aelig:"Shkronja e vogГ« latine Г¦",ccedil:"Shkronja e vogГ«l latine c me hark poshtГ«",egrave:"Shkronja e vogГ« latine e me theks tГ« rГ«ndГ«",eacute:"Shkronja e vogГ« latine e me theks tГ« mprehtГ«",ecirc:"Shkronja e vogГ«l latine e me theks lakor",euml:"Shkronja e vogГ«l latine e me dy pika",igrave:"Shkronja e vogГ« latine i me theks tГ« rГ«ndГ«",
iacute:"Shkronja e vogГ« latine i me theks tГ« mprehtГ«",icirc:"Shkronja e vogГ«l latine i me theks lakor",iuml:"Shkronja e vogГ«l latine i me dy pika",eth:"Shkronja e vogГ« latine eth",ntilde:"Shkronja e vogГ«l latine n me tildГ«",ograve:"Shkronja e vogГ« latine o me theks tГ« rГ«ndГ«",oacute:"Shkronja e vogГ« latine o me theks tГ« mprehtГ«",ocirc:"Shkronja e vogГ«l latine o me theks lakor",otilde:"Shkronja e vogГ«l latine o me tildГ«",ouml:"Shkronja e vogГ«l latine o me dy pika",divide:"Shenja ndarГ«se",oslash:"Shkronja e vogГ«l latine o me vizГ« nГ« mes",
ugrave:"Shkronja e vogГ« latine u me theks tГ« rГ«ndГ«",uacute:"Shkronja e vogГ« latine u me theks tГ« mprehtГ«",ucirc:"Shkronja e vogГ«l latine u me theks lakor",uuml:"Shkronja e vogГ«l latine u me dy pika",yacute:"Shkronja e vogГ« latine y me theks tГ« mprehtГ«",thorn:"Shkronja e vogГ«l latine thorn",yuml:"Shkronja e vogГ«l latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vogГ«l e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vogГ«l latine w me theks lakor",375:"Shkronja e vogГ«l latine y me theks lakor",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Shenja e Simbolit TregtarГ«",9658:"Black right-pointing pointer",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Shenja tГ« dyfishta djathtas",hArr:"Shigjeta e dyfishГ« majtas-djathtas",diams:"Black diamond suit",asymp:"Gati e barabar me"});