п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro iЕџareti",lsquo:"Sol tek tД±rnak iЕџareti",rsquo:"SaДџ tek tД±rnak iЕџareti",ldquo:"Sol Г§ift tД±rnak iЕџareti",rdquo:"SaДџ Г§ift tД±rnak iЕџareti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters Гјnlem iЕџareti",cent:"Cent iЕџareti",pound:"Pound iЕџareti",curren:"Para birimi iЕџareti",yen:"Yen iЕџareti",brvbar:"KД±rД±k bar",sect:"BГ¶lГјm iЕџareti",uml:"Д°ki sesli harfin ayrД±lmasД±",copy:"Telif hakkД± iЕџareti",ordf:"DiЕџil sД±ralД± gГ¶sterge",laquo:"Sol-iЕџaret Г§ift aГ§Д± tД±rnak iЕџareti",
not:"Not iЕџareti",reg:"KayД±tlД± iЕџareti",macr:"Makron",deg:"Derece iЕџareti",sup2:"Д°kili Гјstsimge",sup3:"ГњГ§lГј Гјstsimge",acute:"Aksan iЕџareti",micro:"Mikro iЕџareti",para:"Pilcrow iЕџareti",middot:"Orta nokta",cedil:"Kedilla",sup1:"Гњstsimge",ordm:"Eril sД±ralД± gГ¶sterge",raquo:"SaДџ iЕџaret Г§ift aГ§Д± tД±rnak iЕџareti",frac14:"BayaДџД± kesrin dГ¶rtte biri",frac12:"BayaДџД± kesrin bir yarД±m",frac34:"BayaДџД± kesrin dГ¶rtte ГјГ§",iquest:"Ters soru iЕџareti",Agrave:"AksanlД± latin harfi",Aacute:"AЕџД±rД± aksanД±yla Latin harfi",
Acirc:"Г‡arpД±k Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayrД±lД±mlД±Д± latin harfi",Aring:"HalkalД± latin bГјyГјk A harfi",AElig:"Latin bГјyГјk Г† harfi",Ccedil:"Latin bГјyГјk C harfi ile kedilla",Egrave:"AksanlД± latin bГјyГјk E harfi",Eacute:"AЕџД±rД± vurgulu latin bГјyГјk E harfi",Ecirc:"Г‡arpД±k latin bГјyГјk E harfi",Euml:"Sesli harf ayrД±lД±mlД±Д± latin bГјyГјk E harfi",Igrave:"AksanlД± latin bГјyГјk I harfi",Iacute:"AЕџД±rД± aksanlД± latin bГјyГјk I harfi",Icirc:"Г‡arpД±k latin bГјyГјk I harfi",Iuml:"Sesli harf ayrД±lД±mlД±Д± latin bГјyГјk I harfi",
ETH:"Latin bГјyГјk Eth harfi",Ntilde:"Tildeli latin bГјyГјk N harfi",Ograve:"AksanlД± latin bГјyГјk O harfi",Oacute:"AЕџД±rД± aksanlД± latin bГјyГјk O harfi",Ocirc:"Г‡arpД±k latin bГјyГјk O harfi",Otilde:"Tildeli latin bГјyГјk O harfi",Ouml:"Sesli harf ayrД±lД±mlД± latin bГјyГјk O harfi",times:"Г‡arpma iЕџareti",Oslash:"Vurgulu latin bГјyГјk O harfi",Ugrave:"AksanlД± latin bГјyГјk U harfi",Uacute:"AЕџД±rД± aksanlД± latin bГјyГјk U harfi",Ucirc:"Г‡arpД±k latin bГјyГјk U harfi",Uuml:"Sesli harf ayrД±lД±mlД± latin bГјyГјk U harfi",Yacute:"AЕџД±rД± aksanlД± latin bГјyГјk Y harfi",
THORN:"Latin bГјyГјk Thorn harfi",szlig:"Latin kГјГ§Гјk keskin s harfi",agrave:"AksanlД± latin kГјГ§Гјk a harfi",aacute:"AЕџД±rД± aksanlД± latin kГјГ§Гјk a harfi",acirc:"Г‡arpД±k latin kГјГ§Гјk a harfi",atilde:"Tildeli latin kГјГ§Гјk a harfi",auml:"Sesli harf ayrД±lД±mlД± latin kГјГ§Гјk a harfi",aring:"HalkalД± latin kГјГ§Гјk a harfi",aelig:"Latin bГјyГјk Г¦ harfi",ccedil:"KedillalД± latin kГјГ§Гјk c harfi",egrave:"AksanlД± latin kГјГ§Гјk e harfi",eacute:"AЕџД±rД± aksanlД± latin kГјГ§Гјk e harfi",ecirc:"Г‡arpД±k latin kГјГ§Гјk e harfi",euml:"Sesli harf ayrД±lД±mlД± latin kГјГ§Гјk e harfi",
igrave:"AksanlД± latin kГјГ§Гјk i harfi",iacute:"AЕџД±rД± aksanlД± latin kГјГ§Гјk i harfi",icirc:"Г‡arpД±k latin kГјГ§Гјk i harfi",iuml:"Sesli harf ayrД±lД±mlД± latin kГјГ§Гјk i harfi",eth:"Latin kГјГ§Гјk eth harfi",ntilde:"Tildeli latin kГјГ§Гјk n harfi",ograve:"AksanlД± latin kГјГ§Гјk o harfi",oacute:"AЕџД±rД± aksanlД± latin kГјГ§Гјk o harfi",ocirc:"Г‡arpД±k latin kГјГ§Гјk o harfi",otilde:"Tildeli latin kГјГ§Гјk o harfi",ouml:"Sesli harf ayrД±lД±mlД± latin kГјГ§Гјk o harfi",divide:"BГ¶lme iЕџareti",oslash:"Vurgulu latin kГјГ§Гјk o harfi",ugrave:"AksanlД± latin kГјГ§Гјk u harfi",
uacute:"AЕџД±rД± aksanlД± latin kГјГ§Гјk u harfi",ucirc:"Г‡arpД±k latin kГјГ§Гјk u harfi",uuml:"Sesli harf ayrД±lД±mlД± latin kГјГ§Гјk u harfi",yacute:"AЕџД±rД± aksanlД± latin kГјГ§Гјk y harfi",thorn:"Latin kГјГ§Гјk thorn harfi",yuml:"Sesli harf ayrД±lД±mlД± latin kГјГ§Гјk y harfi",OElig:"Latin bГјyГјk baДџlД± OE harfi",oelig:"Latin kГјГ§Гјk baДџlД± oe harfi",372:"Г‡arpД±k latin bГјyГјk W harfi",374:"Г‡arpД±k latin bГјyГјk Y harfi",373:"Г‡arpД±k latin kГјГ§Гјk w harfi",375:"Г‡arpД±k latin kГјГ§Гјk y harfi",sbquo:"Tek dГјЕџГјk-9 tД±rnak iЕџareti",8219:"Tek yГјksek-ters-9 tД±rnak iЕџareti",
bdquo:"Г‡ift dГјЕџГјk-9 tД±rnak iЕџareti",hellip:"Yatay elips",trade:"Marka tescili iЕџareti",9658:"Siyah saДџ iЕџaret iЕџaretГ§isi",bull:"Koyu nokta",rarr:"SaДџa doДџru ok",rArr:"SaДџa doДџru Г§ift ok",hArr:"Sol, saДџ Г§ift ok",diams:"Siyah elmas takД±mД±",asymp:"Hemen hemen eЕџit"});