п»ї/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","vi",{euro:"KГЅ hiб»‡u Euro",lsquo:"DбєҐu ngoбє·c Д‘ЖЎn trГЎi",rsquo:"DбєҐu ngoбє·c Д‘ЖЎn phбєЈi",ldquo:"DбєҐu ngoбє·c Д‘Гґi trГЎi",rdquo:"DбєҐu ngoбє·c Д‘Гґi phбєЈi",ndash:"GбєЎch ngang tiбєїng anh",mdash:"GбєЎch ngang Em",iexcl:"Chuyб»ѓn Д‘б»•i dбєҐu chбєҐm than",cent:"KГЅ tб»± tiб»Ѓn Mб»№",pound:"KГЅ tб»± tiб»Ѓn Anh",curren:"KГЅ tб»± tiб»Ѓn tб»‡",yen:"KГЅ tб»± tiб»Ѓn YГЄn Nhбє­t",brvbar:"Thanh hб»Џng",sect:"KГЅ tб»± khu vб»±c",uml:"DбєҐu tГЎch Д‘Гґi",copy:"KГЅ tб»± bбєЈn quyб»Ѓn",ordf:"Phбє§n chб»‰ thб»‹ giб»‘ng cГЎi",laquo:"Chб»Ќn dбєҐu ngoбє·c Д‘Гґi trГЎi",not:"KhГґng cГі kГЅ tб»±",
reg:"KГЅ tб»± Д‘Дѓng kГЅ",macr:"DбєҐu nguyГЄn Гўm dГ i",deg:"KГЅ tб»± Д‘б»™",sup2:"Chб»Ї trб»“i lГЄn trГЄn dбєЎng 2",sup3:"Chб»Ї trб»“i lГЄn trГЄn dбєЎng 3",acute:"DбєҐu trб»Ќng Гўm",micro:"KГЅ tб»± micro",para:"KГЅ tб»± Д‘oбєЎn vДѓn",middot:"DбєҐu chбєҐm trГІn",cedil:"DбєҐu mГіc lЖ°б»›i",sup1:"KГЅ tб»± trб»“i lГЄn cбєҐp 1",ordm:"KГЅ tб»± biб»ѓu hiб»‡n giб»‘ng Д‘б»±c",raquo:"Chб»Ќn dбєҐu ngoбє·c Д‘Гґi phбєЈi",frac14:"Tб»‰ lб»‡ mб»™t phбє§n tЖ°",frac12:"Tб»‰ lб»‡ mб»™t nб»­a",frac34:"Tб»‰ lб»‡ ba phбє§n tЖ°",iquest:"Chuyб»ѓn Д‘б»•i dбєҐu chбєҐm hб»Џi",Agrave:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i dбєҐu huyб»Ѓn",Aacute:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i dбєҐu sбєЇc",
Acirc:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i dбєҐu mЕ©",Atilde:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i dбєҐu ngГЈ",Auml:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",Aring:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i biб»ѓu tЖ°б»Јng vГІng trГІn trГЄn Д‘бє§u",AElig:"KГЅ tб»± la-tinh viбєїt hoa cб»§a Г†",Ccedil:"KГЅ tб»± la-tinh viбєїt hoa C vб»›i dбєҐu mГіc bГЄn dЖ°б»›i",Egrave:"KГЅ tб»± la-tinh viбєїt hoa E vб»›i dбєҐu huyб»Ѓn",Eacute:"KГЅ tб»± la-tinh viбєїt hoa E vб»›i dбєҐu sбєЇc",Ecirc:"KГЅ tб»± la-tinh viбєїt hoa E vб»›i dбєҐu mЕ©",Euml:"KГЅ tб»± la-tinh viбєїt hoa E vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",
Igrave:"KГЅ tб»± la-tinh viбєїt hoa I vб»›i dбєҐu huyб»Ѓn",Iacute:"KГЅ tб»± la-tinh viбєїt hoa I vб»›i dбєҐu sбєЇc",Icirc:"KГЅ tб»± la-tinh viбєїt hoa I vб»›i dбєҐu mЕ©",Iuml:"KГЅ tб»± la-tinh viбєїt hoa I vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",ETH:"Viбєїt hoa cб»§a kГЅ tб»± Eth",Ntilde:"KГЅ tб»± la-tinh viбєїt hoa N vб»›i dбєҐu ngГЈ",Ograve:"KГЅ tб»± la-tinh viбєїt hoa O vб»›i dбєҐu huyб»Ѓn",Oacute:"KГЅ tб»± la-tinh viбєїt hoa O vб»›i dбєҐu sбєЇc",Ocirc:"KГЅ tб»± la-tinh viбєїt hoa O vб»›i dбєҐu mЕ©",Otilde:"KГЅ tб»± la-tinh viбєїt hoa O vб»›i dбєҐu ngГЈ",Ouml:"KГЅ tб»± la-tinh viбєїt hoa O vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",
times:"KГЅ tб»± phГ©p toГЎn nhГўn",Oslash:"KГЅ tб»± la-tinh viбєїt hoa A vб»›i dбєҐu ngГЈ xuб»‘ng",Ugrave:"KГЅ tб»± la-tinh viбєїt hoa U vб»›i dбєҐu huyб»Ѓn",Uacute:"KГЅ tб»± la-tinh viбєїt hoa U vб»›i dбєҐu sбєЇc",Ucirc:"KГЅ tб»± la-tinh viбєїt hoa U vб»›i dбєҐu mЕ©",Uuml:"KГЅ tб»± la-tinh viбєїt hoa U vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",Yacute:"KГЅ tб»± la-tinh viбєїt hoa Y vб»›i dбєҐu sбєЇc",THORN:"Phбє§n viбєїt hoa cб»§a kГЅ tб»± Thorn",szlig:"KГЅ tб»± viбєїt nhб»Џ la-tinh cб»§a chб»Ї s",agrave:"KГЅ tб»± la-tinh thЖ°б»ќng vб»›i dбєҐu huyб»Ѓn",aacute:"KГЅ tб»± la-tinh thЖ°б»ќng vб»›i dбєҐu sбєЇc",acirc:"KГЅ tб»± la-tinh thЖ°б»ќng vб»›i dбєҐu mЕ©",
atilde:"KГЅ tб»± la-tinh thЖ°б»ќng vб»›i dбєҐu ngГЈ",auml:"KГЅ tб»± la-tinh thЖ°б»ќng vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",aring:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng vб»›i biб»ѓu tЖ°б»Јng vГІng trГІn trГЄn Д‘бє§u",aelig:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng cб»§a Г¦",ccedil:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng cб»§a c vб»›i dбєҐu mГіc bГЄn dЖ°б»›i",egrave:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng e vб»›i dбєҐu huyб»Ѓn",eacute:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng e vб»›i dбєҐu sбєЇc",ecirc:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng e vб»›i dбєҐu mЕ©",euml:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng e vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",igrave:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng i vб»›i dбєҐu huyб»Ѓn",
iacute:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng i vб»›i dбєҐu sбєЇc",icirc:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng i vб»›i dбєҐu mЕ©",iuml:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng i vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",eth:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng cб»§a eth",ntilde:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng n vб»›i dбєҐu ngГЈ",ograve:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng o vб»›i dбєҐu huyб»Ѓn",oacute:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng o vб»›i dбєҐu sбєЇc",ocirc:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng o vб»›i dбєҐu mЕ©",otilde:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng o vб»›i dбєҐu ngГЈ",ouml:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng o vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",
divide:"KГЅ hiб»‡u phГ©p tГ­nh chia",oslash:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng o vб»›i dбєҐu ngГЈ",ugrave:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng u vб»›i dбєҐu huyб»Ѓn",uacute:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng u vб»›i dбєҐu sбєЇc",ucirc:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng u vб»›i dбєҐu mЕ©",uuml:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng u vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",yacute:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng y vб»›i dбєҐu sбєЇc",thorn:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng cб»§a chб»Ї thorn",yuml:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng y vб»›i dбєҐu hai chбєҐm trГЄn Д‘бє§u",OElig:"KГЅ tб»± la-tinh viбєїt hoa gбєЎch nб»‘i OE",oelig:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng gбєЎch nб»‘i OE",
372:"KГЅ tб»± la-tinh viбєїt hoa W vб»›i dбєҐu mЕ©",374:"KГЅ tб»± la-tinh viбєїt hoa Y vб»›i dбєҐu mЕ©",373:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng w vб»›i dбєҐu mЕ©",375:"KГЅ tб»± la-tinh viбєїt thЖ°б»ќng y vб»›i dбєҐu mЕ©",sbquo:"DбєҐu ngoбє·c Д‘ЖЎn thбєҐp sб»‘-9",8219:"DбєҐu ngoбє·c Д‘ЖЎn Д‘бєЈo ngЖ°б»Јc sб»‘-9",bdquo:"GбєҐp Д‘Гґi dбєҐu ngoбє·c Д‘ЖЎn sб»‘-9",hellip:"TД©nh dЖ°б»Јc chiб»Ѓu ngang",trade:"KГЅ tб»± thЖ°ЖЎng hiб»‡u",9658:"KГЅ tб»± trб»Џ vб»Ѓ hЖ°б»›ng bГЄn phбєЈi mГ u Д‘en",bull:"KГЅ hiб»‡u",rarr:"MЕ©i tГЄn hЖ°б»›ng bГЄn phбєЈi",rArr:"MЕ©i tГЄn hЖ°б»›ng bГЄn phбєЈi dбєЎng Д‘Гґi",hArr:"MЕ©i tГЄn hЖ°б»›ng bГЄn trГЎi dбєЎng Д‘Гґi",diams:"KГЅ hiб»‡u hГ¬nh thoi",
asymp:"Gбє§n bбє±ng vб»›i"});